import type { ProgCourseDef } from './types'
import { masteryCheck as q, masteryLesson as lesson } from './masteryCourse'

// Lesson keys are FROZEN: prog_progress stores
// 'cybersecurity-engineering/<lesson-key>'.
export const CYBERSECURITY_ENGINEERING_COURSE: ProgCourseDef = {
  key: 'cybersecurity-engineering',
  title: 'Cybersecurity engineering: beginner to master',
  description:
    'A self-contained defensive and offensive path through risk, cryptography, identity, application and network security, cloud defense, detection, forensics, governance, and security operations capstones.',
  lessons: [
    lesson(
      'security-risk',
      'Security goals, assets, threats, and risk',
      `Security protects valuable assets against unwanted outcomes. Confidentiality limits disclosure, integrity prevents unauthorized or undetected change, and availability preserves timely use. Authenticity establishes who or what produced an action; accountability connects actions to subjects; privacy governs appropriate personal-data use. These goals can conflict. Encrypting every field may reduce observability and recovery, while maximum availability can enlarge exposure. Begin with the mission, assets, users, legal duties, and harms rather than a list of products.

A threat is a circumstance capable of causing harm. A vulnerability is a weakness that could be exploited. An attack is an attempt to realize a threat, and a control changes likelihood or impact. Risk combines plausible scenario, affected asset, likelihood, impact, uncertainty, and existing controls. Never multiply invented numbers and call the result objective. Use calibrated categories, evidence, assumptions, and a named risk owner who has authority to accept consequences.`,
      `Model a system as trust zones, identities, data flows, components, entry points, dependencies, and administrators. Classify data by sensitivity and lifecycle. For each important flow ask who initiates it, how both ends authenticate, what is authorized, how integrity and confidentiality are protected, what is logged, and what happens when a dependency lies or fails. Defense in depth places independent controls at prevention, detection, response, and recovery boundaries.

Risk treatment has four broad choices: avoid the risky activity, reduce likelihood or impact, transfer defined consequences, or accept the residual risk. Controls may be preventive, detective, corrective, deterrent, or compensating. A firewall cannot compensate for broken authorization inside an allowed request. A backup corrects loss only if restoration works. Record control owner, evidence, failure behavior, monitoring, review date, and dependencies.`,
      `Security is an economic and human system. Eliminating all risk is impossible, and controls create friction, cost, failure modes, and concentration of privilege. Optimize for reduced expected harm within mission constraints. Distinguish compliance, which proves selected requirements at a point in time, from security, which manages changing adversaries and systems. Passing an audit does not prove an untested path is safe.

Use least privilege, secure defaults, complete mediation, separation of duties, minimized attack surface, and fail-safe behavior as design principles. Assume credentials leak and components fail. Limit blast radius, rotate authority, preserve evidence, and rehearse recovery. Measure control outcomes such as time to revoke access or contain an incident, not the raw number of tools purchased.`,
      `Choose a personal media application. List five assets, three threat actors, four concrete threat scenarios, existing controls, and the owner and evidence for each residual risk.`,
      `Assets might include the media database, filesystem, update channel, API credentials, and user activity history. Scenarios include a malicious update stealing credentials, a crafted media file exploiting a parser, and local malware reading unencrypted configuration. Controls include signed verified updates, parser isolation, least-privileged file access, encrypted secrets, backups, and audit logs. Rate each scenario from evidence, name assumptions, and assign treatment to someone able to fund or accept it. Do not call local-only operation a complete control: local malicious software and untrusted files remain inside that boundary.`,
      [
        q('What is a vulnerability?', ['A weakness that a threat could exploit', 'A guaranteed successful attack event', 'A complete inventory of valuable assets', 'A contract transferring every consequence'], 0, 'A vulnerability is a weakness; exploitation, impact, and likelihood belong to the scenario around it.'),
        q('Who should accept residual risk?', ['Any scanner that detected the issue', 'An owner with authority over the consequence', 'The developer nearest the affected file', 'An anonymous reviewer outside the mission'], 1, 'Acceptance is a business decision requiring authority and accountability for the possible impact.'),
        q('What does defense in depth require?', ['Many copies of one identical control', 'One perimeter trusted by every internal service', 'Independent controls across prevention, detection, response, and recovery', 'A policy that treats every finding as equal severity'], 2, 'Independent layers reduce the chance that one weakness or failure defeats the entire protection system.'),
        q('What does audit compliance prove?', ['That no unknown vulnerability exists', 'That every attacker has been identified', 'That recovery will meet every objective', 'That selected requirements had evidence in the assessed scope'], 3, 'Compliance evidence is scoped and time-bound; it is useful but not a guarantee of complete security.')
      ]
    ),
    lesson(
      'ethical-lab',
      'Ethics, legal boundaries, and a safe security laboratory',
      `Security techniques can inspect, disrupt, or access systems, so authorization is a technical prerequisite. Test only assets you own or have explicit permission to assess, inside the approved scope, time, source addresses, methods, and data-handling rules. A public address is not permission. A bug bounty is permission only under its published terms. Stop when impact exceeds the agreement, preserve evidence, and notify the defined contact. Laws and contracts vary; when authority is unclear, do not proceed.

Responsible disclosure gives the owner enough reproducible detail to verify and repair without unnecessarily exposing users. Record affected version, prerequisites, minimal reproduction, impact, suggested mitigation, and evidence handling. Avoid downloading more sensitive data than proof requires. Do not demand payment by threatening publication. Coordinate timelines according to policy and imminent harm.`,
      `Build an isolated lab using disposable virtual machines or containers on a host-only network. Include a test client, intentionally vulnerable target, logging sensor, and snapshot or rebuild script. Do not bridge vulnerable machines onto an untrusted or production network. Use synthetic accounts and data. Give the lab no production credentials, cloud metadata access, shared home-directory mount, clipboard, or unrestricted egress unless a specific exercise requires a controlled exception.

Create a written experiment card before each test: objective, hypothesis, target, exact authorization, tool and version, traffic or resource limit, expected evidence, stop condition, cleanup, and recovery. Capture packets and application logs from your own lab. Hash important artifacts, synchronize clocks, and keep a notebook distinguishing observation from interpretation.`,
      `Tools can damage targets through scan volume, malformed inputs, password lockouts, state changes, or exploit side effects. Begin passive, then low-rate enumeration, then narrowly scoped active checks. Never run a destructive exploit merely to prove a condition that safe evidence already establishes. Automated scanners produce false positives and miss logic flaws; validate manually and understand every command before using it.

Keep offensive code and captured data access-controlled. Test updates can change behavior, so pin lab versions and record digests. Reset to a known state between experiments. The professional habit is reproducibility with bounded harm, not collecting dramatic screenshots.`,
      `Design a lab for testing an intentionally vulnerable web application. Specify network boundaries, identities, data, logging, limits, reset, and evidence retention.`,
      `Place client, target, and sensor on a host-only network with no route to home or production systems. Use synthetic users and a seeded fake database. Bind the target only to the lab interface, restrict egress, and take a clean snapshot. Give the client no personal SSH keys or browser profile. Capture reverse-proxy, application, database, and packet evidence with synchronized clocks. Set request-rate and payload limits, stop on instability or unexpected data, and rebuild from code after each exercise. Retain only redacted findings and hashes for the documented learning period.`,
      [
        q('What establishes permission for a security test?', ['Explicit authorization covering target, methods, and conditions', 'The target responding to an unauthenticated network request', 'A scanner labeling the host as publicly reachable', 'The tester believing the result will improve security'], 0, 'Reachability and good intent are not authorization; scope and conditions must be explicitly granted.'),
        q('What data should a proof of vulnerability collect?', ['Every record reachable through the weakness', 'The minimum synthetic or redacted evidence needed', 'A complete backup copied to the tester device', 'Production secrets for future regression tests'], 1, 'Minimizing collection reduces harm while still giving the owner reproducible evidence.'),
        q('Why isolate a vulnerable lab from production networks?', ['To make logs impossible to collect', 'To prevent the target from being rebuilt', 'To contain compromise, mistakes, and unsafe traffic', 'To guarantee every exploit works unchanged'], 2, 'Isolation reduces blast radius from intentionally weak software and testing errors.'),
        q('What should happen when a test exceeds its approved impact?', ['Increase scan speed to finish sooner', 'Delete evidence and continue quietly', 'Change the scope after the test ends', 'Stop, preserve evidence, and use the agreed contact'], 3, 'A stop condition is meaningful only when the tester halts and escalates through the authorized process.')
      ]
    ),
    lesson(
      'cryptography-foundations',
      'Cryptography, hashes, signatures, PKI, and TLS',
      `Cryptography supplies specific properties under assumptions; it does not make a whole system secure. Symmetric encryption uses one shared secret and is efficient for bulk data. Authenticated encryption provides confidentiality and integrity together and requires a unique nonce under a key. Asymmetric cryptography uses related public and private keys for key agreement or signatures. It is slower and normally establishes keys or identity rather than encrypting large files directly.

A cryptographic hash maps arbitrary input to a fixed-size digest and should resist preimages and collisions for security use. Password storage requires a salted, deliberately expensive password-hashing function, not a fast general hash. A message authentication code proves integrity and authenticity to parties sharing a secret. A digital signature lets holders of a public key verify that a private-key holder signed exact bytes. Neither proves the signer was authorized for the business action.`,
      `Key management determines real security: generate with a cryptographic random source, assign purpose and scope, store behind access controls, rotate, revoke, audit, back up when recoverability requires it, and destroy according to policy. Never reuse one key for unrelated protocols. Envelope encryption generates a data key for content and protects that key with a managed key-encryption key, enabling centralized access and rotation without re-encrypting every byte.

Public-key infrastructure connects names to public keys through certificates signed by trusted certificate authorities. A TLS client validates the certificate chain, requested hostname, validity period, intended use, and policy, then negotiates protected transport. Certificates are public; private keys are secret. TLS protects the connection, not compromised endpoints or data after decryption.`,
      `Do not design new cryptographic algorithms or protocols. Use maintained libraries and high-level authenticated constructions. Nonce reuse, weak randomness, timing leaks, downgrade paths, unauthenticated encryption, hardcoded keys, and ignored certificate verification break otherwise strong primitives. Encoding such as base64 is not encryption. Hashing low-entropy identifiers without a secret is guessable and remains linkable.

Rotation requires compatibility. Introduce a new key, write or sign with it, retain old keys for necessary reads or verification, migrate, verify, and retire. Emergency compromise may require immediate revocation and accepted availability cost. Monitor certificate expiry from the client path and test renewal before deadlines.`,
      `Design encryption and signing for release artifacts stored in an untrusted object store. Include keys, identity, rotation, verification, and recovery.`,
      `Encrypt each sensitive artifact with a fresh authenticated data key and bind metadata such as artifact identity and version as authenticated associated data. Wrap the data key with a managed key-encryption key whose use is restricted and audited. Sign the artifact digest and provenance through a release identity separate from ordinary build steps. Consumers verify digest, signature, trusted signer, expected source, and authorization before decrypting or executing. Rotation adds a new wrapping or signing key while old verification and decryption keys remain only for the retention window. Recovery protects required wrapping keys separately and rehearses access; compromise revokes trust and triggers re-signing or re-encryption based on exposure.`,
      [
        q('What does authenticated encryption provide?', ['Confidentiality plus integrity for protected data', 'A public identity for every application user', 'A reversible replacement for password hashing', 'Authorization for every decrypted operation'], 0, 'Authenticated encryption protects secrecy and detects unauthorized ciphertext or associated-data changes.'),
        q('How should user passwords be stored?', ['With one unsalted fast checksum', 'With a salted expensive password-hashing function', 'As reversible ciphertext beside its decryption key', 'Inside application logs for account recovery'], 1, 'Salt and deliberate cost resist precomputed and high-speed guessing after a credential database leak.'),
        q('What must a TLS client validate?', ['Only that some certificate was presented', 'Only that response bytes are encrypted', 'Trust chain, hostname, validity, and intended use', 'That the server process is running as root'], 2, 'Encryption to an unauthenticated endpoint can protect a connection to the wrong party.'),
        q('Why is base64 not a security control?', ['It uses a key too large to rotate', 'It cannot represent arbitrary bytes', 'It destroys data integrity by design', 'It is reversible encoding without a secret'], 3, 'Anyone can decode base64; it changes representation rather than controlling disclosure.')
      ]
    ),
    lesson(
      'identity-authentication',
      'Identity, authentication, sessions, and account recovery',
      `An identity is a stable subject such as a person, workload, device, or organization. Authentication establishes evidence that a requester controls an identity; authorization decides what that identity may do. Account names are identifiers, not authenticators. Passwords, possession factors, biometrics, hardware-backed keys, client certificates, and federated assertions provide different evidence and failure modes.

Multi-factor authentication combines independent factor categories, not two passwords. Phishing-resistant public-key authenticators bind proof to the legitimate origin and are stronger than codes a user can relay. Risk-based checks can add context but must not become opaque discrimination or a bypass for weak primary authentication. Rate limits, breached-password screening, secure password storage, and lockout design must balance guessing resistance with denial-of-service risk.`,
      `Federation lets an identity provider authenticate users and issue signed assertions or tokens to relying services. Validate issuer, audience, signature, time bounds, nonce or state, redirect targets, and protocol-specific anti-replay properties. Do not accept a token merely because its signature is valid; it must be intended for this service and operation. Keep login callbacks and identity linking strict so an attacker cannot attach their external identity to a victim account.

Browser sessions normally use an opaque random identifier in a Secure, HttpOnly, appropriately SameSite cookie. Store server-side session state or carefully validate signed tokens. Rotate the session identifier after login and privilege change, expire idle and absolute lifetimes, revoke on compromise, and list active sessions for users. Never put bearer tokens in URLs.`,
      `Recovery is an alternate authentication path and often the weakest one. Protect email, support, backup codes, and device reset with strong verification, delay or notification for high-impact change, and audit. Security questions based on public facts are poor secrets. Avoid revealing whether an account exists through public login or reset responses, while still providing usable private guidance.

Workload identities should be short-lived, automatically issued, scoped, and bound to runtime context. Shared service passwords destroy attribution and rotation. Authentication logs need outcome, subject, method, source context, and correlation without recording passwords, complete tokens, or recovery secrets.`,
      `Design login and recovery for a media service with passwords, passkeys, session management, email recovery, and suspicious-login response.`,
      `Use normalized unique account identifiers while keeping public responses enumeration-resistant. Store passwords with a modern salted password hash and rate-limit by account and source without enabling trivial lockout. Offer passkeys as phishing-resistant authentication. On success rotate an opaque session cookie with Secure, HttpOnly, and deliberate SameSite settings, record device metadata, and permit session revocation. Recovery sends a single-use short-lived token whose digest is stored, invalidates it after use, notifies the account, rotates sessions after credential reset, and applies extra delay or support review to risky changes. Suspicious events trigger step-up authentication rather than trusting location alone.`,
      [
        q('What is authentication?', ['Establishing evidence that a requester controls an identity', 'Selecting every action an identity may perform', 'Encrypting all data owned by the subject', 'Publishing the account identifier to other users'], 0, 'Authentication establishes identity evidence; authorization uses that identity to make access decisions.'),
        q('What makes two checks true multi-factor authentication?', ['They use two different password fields', 'They come from independent factor categories', 'They occur on two pages of one form', 'They are stored in the same browser cookie'], 1, 'Independent categories reduce the chance one compromise defeats both factors.'),
        q('What should a service validate on a federated token?', ['Only that its text parses as JSON', 'Only that it has not been seen before', 'Signature, issuer, audience, time, and protocol context', 'That it contains the longest possible account name'], 2, 'A valid signature does not make a token intended for this relying service or current flow.'),
        q('Why is account recovery security-critical?', ['It runs only after a user is permanently deleted', 'It cannot change any authentication material', 'It is always protected by the original password', 'It is an alternate route to account control'], 3, 'An attacker can bypass strong normal login if the recovery path uses weaker evidence.')
      ]
    ),
    lesson(
      'authorization-iam',
      'Authorization, IAM, and privilege boundaries',
      `Authorization evaluates whether a subject may perform an action on a resource under context. Make the tuple explicit: subject, action, resource, environment, condition, and decision. Role-based access control groups permissions by job function; attribute-based control evaluates subject, resource, and context attributes; relationship-based control follows ownership or membership graphs. Most systems combine them.

Default deny and least privilege mean no permission exists without a justified grant. Complete mediation means every access path checks current policy, including background jobs, exports, caches, administrative APIs, and direct object references. Hiding a button is user experience, not authorization. Enforce at the trusted service boundary and constrain the database or platform beneath it where practical.`,
      `Design permissions from tasks, then separate read, create, update, delete, approve, delegate, and administer. Broad wildcards and administrator roles make initial setup easy but create excessive blast radius. Time-bound elevation and just-in-time access reduce standing privilege. Separation of duties prevents one identity from proposing and approving a critical action. Break-glass access is strongly authenticated, short, alerted, recorded, and reviewed.

Resource ownership must be checked from trusted identifiers. If a route accepts an object id, load the object under a query already scoped to the caller rather than fetch globally and compare inconsistently later. Multi-tenant systems carry tenant identity through every query, cache key, job, log, and storage path. Test cross-tenant negative cases systematically.`,
      `Policy data can become stale. Group removal, account disablement, or role change must propagate within an explicit maximum. Long-lived self-contained tokens may retain revoked rights; shorten lifetime or consult current state for high-risk operations. Cache decisions only with versioning and bounded lifetime.

Privilege escalation often comes indirectly: ability to edit a policy, create a workload that mounts a secret, pass a role to a service, modify a trusted pipeline, or impersonate another subject. Review the transitive authority graph, not only obvious read and write verbs. Log grants, denials for sensitive actions, delegation, policy changes, and elevated sessions without exposing protected data.`,
      `Model authorization for a team media library with owners, editors, viewers, invitation management, exports, and account deletion. Include negative tests and revocation.`,
      `Define resources at organization, library, item, invitation, and export levels. Owners manage membership and deletion; editors change items but cannot alter roles or export private history; viewers read permitted items. Invitations grant only the selected role after acceptance and expire. Queries always scope library and organization before returning an object. Export is a separate permission and produces an audited job. Deletion requires recent authentication and perhaps two-person approval for shared organizations. Tests cover every role-action pair, guessed ids across tenants, stale cache, removed membership, delegated admin, and background jobs. Revocation invalidates active elevated sessions or propagates within a documented short bound.`,
      [
        q('What does default deny mean?', ['Access requires an explicit applicable grant', 'Every authenticated identity becomes an administrator', 'Failed requests are retried with greater privilege', 'Resources are public until a policy is written'], 0, 'Default deny makes absence of a matching authorization rule a refusal rather than accidental access.'),
        q('Where must object authorization be enforced?', ['Only in the visual button state', 'At the trusted service and data access boundary', 'Only in client-side route navigation', 'Inside a user-editable local preference'], 1, 'Clients are untrusted; the service must scope data and actions to the authenticated subject.'),
        q('Why can long-lived tokens delay revocation?', ['They cannot contain any authorization claims', 'They require the subject to stay logged out', 'They may preserve old grants until expiry', 'They always query current policy on every use'], 2, 'Self-contained claims remain valid unless checked, revoked, or allowed to expire.'),
        q('Which permission can indirectly escalate privilege?', ['Reading a public status page', 'Changing an unprivileged display preference', 'Listing one owned media item', 'Passing an administrator role to a new workload'], 3, 'Delegating or attaching a powerful role can grant the resulting service authority to the caller-controlled workload.')
      ]
    ),
    lesson(
      'threat-modeling',
      'Threat modeling and security architecture',
      `Threat modeling is structured reasoning about how a system could be harmed and where controls belong. Do it while designs are cheap to change, update it when trust boundaries or assets change, and use it to derive tests. A diagram is a means, not the deliverable. The output is prioritized scenarios, requirements, decisions, owners, and residual risk.

Start with scope and assumptions. Inventory assets, actors, entry points, components, data stores, administrators, external dependencies, and data flows. Draw trust boundaries wherever identity, control, privilege, ownership, or exposure changes. Include build, deployment, support, backups, analytics, and deletion, not only normal requests. Record what the system intentionally does not protect against.`,
      `STRIDE is a useful prompt: spoofing identity, tampering, repudiation, information disclosure, denial of service, and elevation of privilege. Attack trees start with an attacker goal and decompose alternative paths. Misuse cases describe malicious or accidental flows. Privacy modeling asks linkability, identifiability, disclosure, detectability, and user control. These methods generate questions; they do not calculate risk automatically.

Turn scenarios into requirements with verification: authenticate service callbacks; authorize every object under tenant scope; sign update manifests; rate-limit expensive unauthenticated work; redact secrets from telemetry; restore deleted data within the retention policy. Connect each requirement to design, implementation, and a test or operational control.`,
      `Avoid generic lists disconnected from architecture. "Use encryption" is incomplete without data, threat, endpoints, keys, and verification. Do not score every theoretical issue as critical. Consider attacker capability, reachability, preconditions, blast radius, detectability, reversibility, and user harm. Include abuse of valid features, insider access, dependency compromise, and operational mistakes.

Review after major data flow, identity, dependency, exposure, or recovery changes and after incidents reveal invalid assumptions. Keep the model concise enough to use but detailed enough that a new reviewer can challenge it.`,
      `Threat-model a public file-upload and media-processing feature. Include browser, API, object store, queue, worker, metadata database, and download path.`,
      `Assets include service availability, other tenants' files, worker credentials, object integrity, and user devices. Boundaries occur at browser to edge, API to storage, queue to worker, and worker to metadata and output. Scenarios include oversized upload exhaustion, path confusion, parser exploit, polyglot content served with an unsafe type, guessed object ids, malicious archive expansion, queue replay, and worker credential theft. Controls include authenticated scoped upload grants, size and count limits, random server-side object ids, quarantine, isolated non-root workers without broad egress, parser deadlines, content disposition and type policy, idempotent jobs, malware scanning as one signal, tenant-scoped download authorization, and lifecycle deletion. Test every scenario and preserve a safe reject reason.`,
      [
        q('What is the useful output of threat modeling?', ['Prioritized scenarios, requirements, evidence, owners, and risk', 'A diagram with no decisions or follow-up actions', 'A universal score produced without system context', 'A list containing only known software vulnerabilities'], 0, 'The model should change design, tests, or accepted risk rather than end as an isolated picture.'),
        q('Where should a trust boundary be drawn?', ['Only at the public internet edge', 'Where identity, privilege, control, or ownership changes', 'Around every source-code function regardless of data flow', 'Only around components using symmetric encryption'], 1, 'Trust changes at internal and external boundaries, including deployment and administrative systems.'),
        q('What does STRIDE provide?', ['A complete quantitative risk calculation', 'A replacement for architecture diagrams', 'Prompts for categories of security failure', 'A guarantee that every abuse case is discovered'], 2, 'STRIDE is a mnemonic for asking systematic questions, not proof of completeness or severity.'),
        q('When should a threat model be revisited?', ['Only once after the service is retired', 'Only when an external auditor requests it', 'Never after implementation begins', 'When flows, identities, dependencies, or assumptions change'], 3, 'Security reasoning must follow material architecture changes and lessons from incidents.')
      ]
    ),
    lesson(
      'secure-coding',
      'Secure coding, validation, parsing, and memory safety',
      `Treat every external value as untrusted data, including headers, filenames, database content, queue messages, configuration, and dependency responses. Validation establishes whether data belongs to the business domain: type, syntax, length, range, encoding, allowed values, relationships, and state transition. Normalize only when the specification defines one canonical representation, then validate. Confusable or multiply encoded values can bypass inconsistent checks.

Injection occurs when data becomes code in an interpreter. Use parameterized database queries, argument arrays for processes, safe templating with context-aware escaping, and structured APIs. Allowlists help for identifiers that cannot be parameters. Escaping is context-specific: HTML text, HTML attribute, URL, JavaScript, CSS, shell, SQL identifier, and LDAP each differ. Avoid dynamic code generation.`,
      `Parsing hostile files and protocols needs size, depth, count, time, recursion, decompression, and allocation limits. Reject ambiguous encodings and trailing data when the format disallows it. Parse into a typed representation before acting. Use memory-safe languages for exposed components when feasible. In C or native libraries, use bounds-checked design, integer-overflow checks, sanitizers, fuzzing, and process isolation.

Error handling must fail safely without leaking internals. Return stable public categories and log protected causal context. Ensure authorization and transaction failures do not leave partial side effects. Generate randomness through cryptographic APIs for tokens. Compare secrets with constant-time primitives when timing exposure matters.`,
      `Dependencies are part of the program. Pin and verify them, minimize them, monitor advisories, and remove unused packages. A type-safe wrapper can centralize a dangerous interface, but it must not hide errors. Code review should trace attacker-controlled data to sensitive sinks, examine state transitions, and ask what happens on timeout, retry, concurrency, and partial failure.

Security tests include negative cases, boundary values, properties, fuzzing, static analysis, dynamic testing, dependency review, and manual logic review. A scanner can find patterns but cannot decide whether one user may approve another user's payment. Preserve regression tests for every confirmed vulnerability.`,
      `Review an endpoint that accepts a URL, downloads a ZIP, extracts it, and imports JSON. List validations and containment from request through commit.`,
      `Authorize the caller and bind the operation to a tenant and quota. Parse the URL, allow only required schemes and destinations, resolve and recheck addresses to block internal or metadata targets, set connect and total deadlines, response size, redirect, and content-type policy. Store in quarantine under a generated name. Inspect ZIP entry counts, compressed and expanded totals, path traversal, links, duplicate names, and nesting before extraction into an isolated directory. Parse JSON with depth and field limits into a schema, validate relationships, and write in one idempotent transaction. Run the fetch and parser without production credentials or broad egress, preserve safe diagnostics, and delete quarantine by lifecycle.`,
      [
        q('What is the best defense against SQL value injection?', ['Parameterized queries with data bound separately', 'Removing spaces from the submitted value', 'Escaping values with an HTML encoder', 'Hiding database errors in the browser'], 0, 'Parameters preserve the code and data boundary understood by the database driver.'),
        q('Why is output escaping context-specific?', ['Every context uses the same control characters', 'HTML, URL, script, and shell interpreters have different grammars', 'Escaping always decrypts the protected value', 'It replaces the need for authorization checks'], 1, 'A transformation safe for one interpreter may be unsafe or corrupt in another.'),
        q('What limits should a hostile archive parser enforce?', ['Only the original filename length', 'Only the compressed byte count', 'Entry, expansion, path, nesting, memory, and time bounds', 'No limits when the archive has a familiar extension'], 2, 'Archives can consume resources or escape paths through several independent dimensions.'),
        q('What should happen after fixing a confirmed vulnerability?', ['Remove all evidence of the original failure', 'Depend only on the scanner that missed it', 'Publish the production secret used to reproduce it', 'Add a regression test for the broken security property'], 3, 'A focused test keeps the discovered failure from returning during later changes.')
      ]
    ),
    lesson(
      'web-security',
      'Web security: injection, requests, and server trust',
      `Web applications cross browser, edge, application, database, cache, and external-service boundaries. Begin every request with transport protection, host and route selection, authentication, authorization, content-type and size limits, schema validation, and a controlled state transition. Reverse proxies and applications must agree about path decoding, hostnames, forwarded headers, and request length or an attacker can exploit interpretation differences.

SQL and command injection are code-data boundary failures. Parameterize values and avoid dynamic identifiers. Server-side request forgery turns the server into an attacker-controlled network client. A URL allowlist must consider scheme, credentials, redirects, DNS rebinding, IPv4 and IPv6 forms, alternate encodings, internal ranges, cloud metadata, and post-resolution policy. Prefer brokered access to named integrations over arbitrary URLs.`,
      `File upload controls include authorization, count and size quotas, generated storage keys, safe content disposition, quarantine, parser isolation, and download authorization. File extensions and declared MIME types are hints. Storing outside the executable web root reduces one class of execution. Antivirus is a supplemental signal, not proof that an active document is harmless.

Path traversal arises when attacker data influences filesystem paths. Resolve against an intended root, reject absolute and parent traversal, handle symlinks, and verify the final path remains within the root. Race-free APIs and isolated storage are stronger than a string prefix check. Deserialization of native object graphs can invoke code or create unexpected types; accept simple data formats and explicit schemas.`,
      `HTTP request smuggling, cache poisoning, and host-header attacks exploit disagreement among layers. Keep edge and origin parsing current and consistent, reject ambiguous framing, allow known hostnames, and build absolute URLs from trusted configuration. Cache keys must include every response-varying security dimension, and private authenticated responses should not enter a shared public cache.

Business logic failures include coupon reuse, negative quantities, race conditions, workflow skipping, and mass assignment. Model allowed state transitions, choose server-owned fields explicitly, enforce invariants transactionally, and test concurrency. Rate limit scarce operations by meaningful identities while retaining abuse detection and recovery for shared networks.`,
      `Security-review a password-protected media download endpoint behind a reverse proxy and CDN. Include cache, range requests, links, and logs.`,
      `Use an opaque download id scoped to the authenticated user or a short-lived signed capability with resource, audience, expiry, and optional disposition. The origin reauthorizes or verifies the capability on every request, including ranges. CDN cache keys cannot mix private principals; use private signed delivery or disable shared caching. Validate Host and trusted forwarded headers only from the proxy. Normalize one path representation. Set safe Content-Type, nosniff, Content-Disposition, and range bounds. Rate-limit abusive transfer without breaking resume. Logs record account, object, bytes, range, decision, and correlation but not passwords or complete signed URLs. Revocation and deletion invalidate future access.`,
      [
        q('What is SSRF?', ['Attacker control of server-side network requests', 'Browser execution of trusted static CSS', 'Encryption of a session cookie at rest', 'A database replica falling behind its leader'], 0, 'SSRF abuses the server network position and credentials by influencing its outbound requests.'),
        q('Why are uploaded file extensions insufficient?', ['Extensions cannot contain any letters', 'Declared names do not establish safe content or behavior', 'Extensions automatically execute only on servers', 'A familiar extension guarantees parser memory safety'], 1, 'Names and claimed types are attacker-controlled hints; handling needs isolation, limits, and serving policy.'),
        q('What creates cache poisoning risk?', ['Using a cache for public immutable images', 'Setting an explicit maximum response size', 'Omitting an input that changes response or security from the cache key', 'Recording the exact artifact digest in a release'], 2, 'If security-relevant request dimensions are not keyed, one response can be served to the wrong context.'),
        q('How should mass assignment be prevented?', ['Accept every submitted object property', 'Hide the form field with CSS', 'Rename administrative fields periodically', 'Map only explicitly allowed client fields to server state'], 3, 'A server-owned allowlist prevents clients from setting privileged or internal properties.')
      ]
    ),
    lesson(
      'browser-security',
      'Browser security, XSS, CSRF, CORS, and isolation',
      `The browser isolates origins, where an origin is scheme, host, and port. The same-origin policy limits one origin reading another origin's data, while still allowing many cross-origin sends and embeds. Cross-Origin Resource Sharing is a response-header protocol that lets a server relax read restrictions for selected origins. It is not authentication and does not stop nonbrowser clients. Never reflect arbitrary Origin with credentials.

Cross-site scripting makes attacker-controlled data execute as script in a trusted origin. Stored, reflected, and DOM-based XSS differ in where the data lives and which code creates the sink. Prevent it with framework-safe text rendering, context-aware output encoding, safe URL policy, sanitizer libraries for deliberately allowed HTML, and avoidance of dangerous DOM APIs. HttpOnly cookies reduce token theft but XSS can still perform authenticated actions.`,
      `A Content Security Policy restricts script, style, connection, framing, and other sources. A strict nonce or hash-based policy can contain some injection, but broad unsafe directives and allowlists weaken it. Deploy in report-only mode, inspect violations, then enforce. Trusted Types can restrict dangerous DOM sinks in supporting browsers. Subresource Integrity pins expected bytes for selected external resources, though dependency ownership and update remain necessary.

Cross-site request forgery exploits ambient credentials such as cookies to make an unwanted request. Use SameSite cookie policy, unpredictable server-validated CSRF tokens for relevant flows, origin checks, and non-simple content types where appropriate. GET must not change state. Reauthentication protects high-impact actions.`,
      `Clickjacking overlays a target page to trick interaction; prevent framing with CSP frame-ancestors or compatible headers. Opener relationships, postMessage, redirects, and URL fragments are additional boundaries. Verify exact postMessage origins and message schemas and avoid target wildcard for sensitive data. New-window links to untrusted sites should not retain unnecessary opener control.

Cookies need Secure, HttpOnly when script access is unnecessary, narrow Path and Domain, deliberate SameSite, expiration, and prefixes where supported. Local storage is readable by any script in the origin and is not a safe place for long-lived bearer tokens under XSS. Browser extensions and supply-chain scripts share considerable page authority; minimize third-party code.`,
      `Design a browser session and content policy for a React media app that renders user reviews and embeds selected trailers.`,
      `Keep the session in an opaque Secure, HttpOnly cookie with narrow domain, deliberate SameSite, rotation, and server revocation. React renders reviews as text; if formatted markup is needed, parse a restricted format and sanitize with a maintained allowlist. State-changing requests carry a CSRF token and verify Origin. CSP uses per-response nonces for owned scripts, forbids object embedding, restricts connections and images, and permits framing only for explicitly selected trailer providers through sandboxed iframes. The app validates postMessage origin and schema. No third-party analytics receives review text or session identifiers. Automated tests inject common payloads, but manual DOM-flow review remains required.`,
      [
        q('What does the same-origin policy primarily restrict?', ['Cross-origin reading and interaction by browser code', 'All network requests made by a web server', 'Database queries containing user input', 'Operating-system access by native applications'], 0, 'The browser isolates origins, particularly their ability to read each other, with defined exceptions.'),
        q('What is the default safe way to render user text?', ['Insert it into an HTML string', 'Use a text-rendering API that does not interpret markup', 'Evaluate it as a template expression', 'Place it into an inline script block'], 1, 'Text APIs preserve data as text rather than letting it become active HTML or script.'),
        q('What attack do CSRF tokens help prevent?', ['An attacker reading a public image', 'A server using too much CPU', 'Unwanted authenticated requests using ambient credentials', 'A user forgetting their account identifier'], 2, 'CSRF binds a state-changing request to a value the attacking site cannot obtain.'),
        q('How should sensitive postMessage data be sent?', ['To every window with a wildcard target', 'Without checking the received data shape', 'Through a URL fragment shared with third parties', 'To an exact expected origin with schema validation'], 3, 'Both sender and receiver should constrain origin and message structure at the cross-window boundary.')
      ]
    ),
    lesson(
      'api-security',
      'API security, object scope, abuse, and protocol safety',
      `An API exposes business capabilities, not just data. Define authentication, authorization, resource ownership, schema, idempotency, rate and cost limits, pagination, error behavior, versioning, and audit for every operation. Machine clients can send combinations no user interface offers. Treat documentation as a contract and negative tests as first-class examples.

Broken object-level authorization occurs when a caller changes an identifier and reaches another subject's object. Scope the lookup to the caller's permitted tenant and relationship in one data-access operation. Broken function-level authorization exposes administrative actions under guessable routes. Enforce policy centrally but preserve operation-specific decisions. Random identifiers reduce guessing but never replace access checks.`,
      `Accept only declared fields, types, sizes, nesting, formats, and counts. Reject unknown fields for security-sensitive requests when compatibility permits. Mass assignment lets a client write internal fields. Excessive data exposure returns fields the current client does not need. Build response models explicitly and classify sensitive data.

Rate limiting should reflect scarce resources and abuse units: requests, authentication attempts, expensive searches, exports, bytes, recipients, or jobs. Apply per account, token, tenant, source, and global bounds as appropriate. Return retry guidance without revealing internal capacity. Quotas need reset, visibility, exception, and protection against parallel-race bypass.`,
      `Bearer tokens grant whoever holds them authority. Use TLS, short lifetime, audience and scope restrictions, secure storage, rotation, and revocation. For service callbacks, verify message signatures or mutual identity, timestamp and replay window, exact body bytes, and destination. Never authenticate a webhook from a source IP alone.

Graph query APIs need depth, complexity, field authorization, persisted queries where useful, and response bounds. Bulk APIs need item-level authorization and atomicity semantics. File and URL inputs inherit parser and SSRF risks. Inventory every API version and retire abandoned endpoints; an undocumented older route remains attack surface. Log denied and high-impact actions with correlation while minimizing sensitive content.`,
      `Design a secure bulk API that lets editors update up to 100 media items and optionally upload covers through pre-signed storage URLs.`,
      `Authenticate a short-lived token scoped to the organization and bulk-edit permission. Validate at most 100 unique item ids and explicitly allowed fields, then load all items under the caller's organization and verify the returned set matches. Define whether the operation is all-or-nothing; for atomic behavior validate first and update in one transaction with an idempotency key. Issue cover upload capabilities only for generated object keys, exact size and type bounds, short expiry, and one tenant. Uploaded objects remain quarantined until isolated validation succeeds and an authorized finalize operation attaches them. Rate-limit items and bytes, audit before and after identities without storing cover contents, and make retry return the prior result.`,
      [
        q('How should object-level authorization be enforced?', ['Query the object inside the caller permitted scope', 'Trust a random object identifier as sufficient proof', 'Hide the identifier field in the browser interface', 'Check access only after returning the response'], 0, 'Scoping the lookup prevents another tenant object from becoming an authorized candidate.'),
        q('What prevents API mass assignment?', ['Allowing every JSON property through a generic mapper', 'Explicit request models containing writable fields only', 'Changing internal field names once per release', 'Encrypting the HTTP status code'], 1, 'A narrow input model stops clients from selecting server-owned privilege or state fields.'),
        q('What should an expensive API rate limit measure?', ['Only source IP regardless of authenticated identity', 'The number of letters in the route name', 'The scarce work unit such as jobs, bytes, or query cost', 'The current source-code line count'], 2, 'Limits are effective when aligned with the resource and abuse impact being protected.'),
        q('What makes a webhook replay-resistant?', ['A public callback path with no authentication', 'Trusting any request from a cloud address', 'Logging the payload after processing it', 'A verified signature plus timestamp, nonce, and deduplication'], 3, 'Authenticity must bind exact content, while freshness and stable event identity prevent reuse.')
      ]
    ),
    lesson(
      'network-defense',
      'Network architecture, segmentation, and defensive monitoring',
      `Network security controls reachability and observes communication, but network location alone does not establish trust. Model flows from user to edge, service to service, administrator to control plane, workload to dependency, and system to internet. For each, declare source identity, destination, protocol, port, direction, purpose, data sensitivity, authentication, encryption, and owner. Deny paths without a business need and review changes as code.

Segmentation limits blast radius. Separate public edges, application workloads, data stores, management planes, build systems, and security tooling. Microsegmentation can narrow workload flows, but excessive brittle rules create outages and emergency bypasses. Firewalls are stateful or stateless policy engines depending on implementation; understand return traffic, address translation, load balancers, IPv6, and cloud-provider semantics.`,
      `DNS, DHCP, routing, time, certificates, and identity providers are foundational dependencies and high-value attack targets. Restrict administrative access, use authenticated protocols, monitor change, and retain known-good configuration. Protect cloud metadata endpoints and control egress so a compromised workload cannot freely reach credentials or command infrastructure.

Network telemetry includes flow records, DNS queries, proxy logs, firewall decisions, packet capture, and endpoint connection events. Full packet capture is expensive and sensitive; collect it selectively with legal and retention controls. Baseline expected flows by service identity and investigate novel destinations, unusual data volume, beacon timing, impossible protocols, and denied-path spikes.`,
      `Encryption reduces passive inspection but does not eliminate metadata or endpoint telemetry. TLS interception creates another trusted decryption point and can weaken privacy and protocol integrity; use only with explicit need and governance. Prefer endpoint and service instrumentation for content-aware detection.

Detection without response is incomplete. Every high-confidence network alert needs scope, owner, enrichment, containment choices, and false-positive review. Avoid automatic blocking from a weak signal that an attacker can spoof to deny service. Test segmentation from permitted and forbidden source contexts, including DNS and health checks.`,
      `Design network zones and flows for a public API, workers, database, CI builder, administrator access, monitoring, and update downloads.`,
      `Put the edge in a narrowly exposed zone, application and workers in private workload zones, database in a data zone, build runners in an isolated supply-chain zone, and management through a strongly authenticated audited access plane. Permit edge to API on the service port, API and workers to exact database or queue ports, workloads to controlled DNS, time, telemetry, and an egress proxy for approved updates. CI can publish to the registry but cannot reach production data. Administrators receive time-bound access through the management plane, not public database exposure. Default deny both directions, log important decisions, test every allowed flow, and alert on unexpected egress and policy drift.`,
      [
        q('What is the primary purpose of segmentation?', ['Limit reachable paths and compromise blast radius', 'Authenticate every application user automatically', 'Replace encryption for sensitive network traffic', 'Guarantee that endpoints contain no malware'], 0, 'Segmentation narrows communication and lateral movement but remains one layer of defense.'),
        q('Which network dependency deserves control-plane protection?', ['A decorative static image', 'DNS and time infrastructure used by authentication', 'A local text editor theme', 'An expired test fixture outside runtime'], 1, 'Compromising name or time services can redirect traffic or invalidate security decisions across systems.'),
        q('Why collect flow records?', ['They contain every decrypted application payload', 'They automatically remove malicious connections', 'They summarize who communicated, when, and how much', 'They eliminate the need for endpoint evidence'], 2, 'Flow metadata supports baselines and investigation without retaining complete packet contents.'),
        q('Why avoid automatic blocking on a weak signal?', ['All network signals are legally prohibited', 'Blocking cannot affect availability', 'Attackers never generate false indicators', 'Spoofed or noisy evidence can become denial of service'], 3, 'Automated containment needs confidence and safe failure behavior because the control itself can harm service.')
      ]
    ),
    lesson(
      'endpoint-hardening',
      'Operating-system, endpoint, and workload hardening',
      `Hardening reduces attack surface and constrains compromise. Begin from a maintained minimal baseline, then remove unnecessary services, packages, accounts, listeners, kernel features, and administrative tools. Record ownership and required function before removal. A minimal system that cannot be diagnosed or patched is not secure, so keep controlled observability and recovery paths.

Patch operating systems, browsers, runtimes, firmware, and security tools through a measured process with inventory, severity deadlines, canaries, restart or reboot handling, rollback, and end-of-life policy. Vulnerability age and actual deployed version matter more than the intended image. Emergency patches still need compatibility evidence and post-change verification.`,
      `Use separate nonadministrator accounts, strong device authentication, screen locking, encrypted storage, secure boot where appropriate, and centrally managed configuration. Application services run under dedicated identities, write only owned state, and receive narrow capabilities. Mandatory access controls, sandboxing, system-call restrictions, process limits, and application allowlisting can reduce post-exploit power.

Endpoint detection collects process starts, modules, network connections, file and registry or configuration changes, authentication, and security-control status. Protect the agent and its telemetry but avoid treating it as infallible. Attackers can disable, evade, or abuse security software. Monitor missing agents, stale policy, clock problems, and gaps.`,
      `Developer endpoints are supply-chain assets because they hold source access, signing capability, browser sessions, and credentials. Separate personal and privileged work, use hardware-backed keys, prevent secrets in local files, and avoid building releases from ordinary laptops. Mobile and remote devices need loss, offline, untrusted-network, and privacy policies.

Backups protect endpoint data only when restoration and credential recovery work. Remote wipe is not guaranteed for an offline device. On suspected compromise, isolate network access without destroying volatile evidence, capture triage according to policy, rotate exposed authority from a clean system, and rebuild from trusted media rather than relying on superficial cleanup.`,
      `Create a hardening baseline and compromise response for a developer laptop that can access source repositories but cannot deploy directly.`,
      `Require supported OS and firmware, automatic encrypted storage, secure boot, nonadmin daily account, phishing-resistant authentication, short sessions, host firewall, maintained browser, endpoint telemetry, and rapid critical patching. Source access uses a hardware-backed key scoped to repositories; no production credential or signing key is present. Build output from the laptop is untrusted until CI rebuilds it. Back up user work to protected storage and test restore. On compromise, isolate the device, preserve volatile and disk evidence under the incident policy, revoke sessions and source keys from a clean device, inspect repository and workflow activity, then wipe and reinstall from a trusted image before reissuing authority.`,
      [
        q('What is the first goal of endpoint hardening?', ['Reduce unnecessary attack surface and privilege', 'Install every available administrative utility', 'Keep unsupported software for compatibility forever', 'Disable logging to reduce local disk use'], 0, 'Removing unused exposure and constraining required behavior reduces paths available to attackers.'),
        q('What makes patch deployment trustworthy?', ['Applying every update to all production hosts simultaneously', 'Inventory, canaries, verification, and recovery evidence', 'Assuming the intended version equals the deployed version', 'Avoiding reboots even when the update requires one'], 1, 'A controlled fleet process establishes actual coverage and catches compatibility or restart failures.'),
        q('What should be monitored about endpoint agents?', ['Only their vendor name', 'Only the number originally purchased', 'Missing telemetry, disabled controls, and stale policy', 'No status because agents cannot be attacked'], 2, 'A silent or outdated sensor creates false confidence and can be an incident signal itself.'),
        q('How should a strongly suspected compromised endpoint recover?', ['By deleting one suspicious file and continuing', 'By keeping all old sessions active for investigation', 'By trusting scans run under the compromised system', 'By rotating authority and rebuilding from trusted media'], 3, 'A clean rebuild and external credential response provide a stronger trust reset than in-place cleanup.')
      ]
    ),
    lesson(
      'vulnerability-management',
      'Vulnerability discovery, prioritization, and remediation',
      `Vulnerability management is the lifecycle from asset inventory through discovery, validation, prioritization, ownership, remediation, verification, exception, and learning. A scanner report is an input, not the program. You cannot protect unknown assets or unsupported versions, so inventory internet exposure, software, dependencies, images, infrastructure, identities, data stores, and owners continuously.

Sources include vendor advisories, dependency and image scanners, configuration checks, code analysis, penetration tests, bug reports, threat intelligence, and incidents. Normalize findings to the actual deployed component and preserve provenance. Duplicate identifiers may describe the same underlying risk. False positives need evidence and expiry, not permanent suppression.`,
      `Prioritize from exploitability, reachability, attacker prerequisites, privilege gained, data and user impact, known exploitation, exposure, compensating controls, and asset importance. A high base severity in unreachable test code may rank below a moderate internet-facing authentication bypass. Time-bound remediation targets should vary by risk class and active exploitation.

Remediation may update, remove, reconfigure, isolate, add a compensating control, or redesign. Test updates through normal delivery and verify the deployed version. When no patch exists, reduce exposure, disable the feature, add detection, and monitor the vendor. Exceptions identify affected assets, justification, controls, risk owner, and expiry.`,
      `Dependency fixes can introduce breaking changes, and blind automatic merging transfers risk rather than removing it. Group routine compatible updates, keep locks and tests, and preserve an emergency path. Reachability analysis helps but can miss dynamic behavior. A vulnerability being hard to exploit today does not justify indefinite neglect if the component is abandoned.

Measure age of open risk by severity and exposure, remediation lead time, recurrence, unsupported assets, exception expiry, and verification failure. Counting all findings rewards noisy scanning. Root-cause reviews identify why vulnerable components entered, stayed, or could not be updated.`,
      `Triage three findings: a critical library in an unused build tool, a high known-exploited edge-server flaw, and a medium authorization bug exposing another tenant title.`,
      `Validate deployment and reachability first. The known-exploited internet edge flaw receives emergency mitigation and patch with traffic verification. The authorization bug has direct cross-tenant confidentiality impact and should be treated as urgent even if its generic score is medium: restrict the route, fix scoped lookup, inspect access logs, notify incident/privacy owners, and add regression tests. The critical build-tool library may be lower runtime risk but still threatens the supply chain if invoked on untrusted source; update or remove it promptly and isolate builds meanwhile. Record owners, deadlines, evidence, deployed versions, and any exposure investigation.`,
      [
        q('What must vulnerability management begin with?', ['An owned inventory of actual assets and versions', 'A promise that every scanner result is exploitable', 'A permanent exception for unsupported systems', 'A public list of all internal credentials'], 0, 'Discovery and prioritization require knowing what exists, where it runs, and who owns it.'),
        q('How should remediation priority be decided?', ['Only from the longest vulnerability description', 'From exploitability, exposure, controls, and impact', 'Only from the package download count', 'By fixing findings in alphabetical order'], 1, 'Context turns a generic severity into risk for a particular deployed asset and mission.'),
        q('What belongs in a vulnerability exception?', ['No expiry because risk was already discussed', 'Only the scanner finding identifier', 'Owner, justification, controls, assets, and expiry', 'A rule suppressing all future findings for the product'], 2, 'A bounded exception makes residual risk explicit and forces reevaluation.'),
        q('What confirms a vulnerability was remediated?', ['A developer changed a version in one local file', 'The vendor published a patch announcement', 'A scanner job was temporarily disabled', 'The deployed asset and security property are verified'], 3, 'The program closes risk only when the production reality and relevant behavior have changed.')
      ]
    ),
    lesson(
      'cloud-container-security',
      'Cloud, container, and Kubernetes security',
      `Cloud security begins with organization boundaries, federated human identity, workload identity, least privilege, network design, resource policy, audit, and data protection. Separate production and lower environments by accounts or projects and credentials, not names alone. Deny public storage and unrestricted administrative access by default. Centralize audit in a protected account and monitor policy changes, root or break-glass use, disabled logs, and new public exposure.

Managed services divide responsibility. Providers operate selected infrastructure while customers still own identity, configuration, data, application, backup requirements, and many network controls. Encrypt data in transit and at rest according to threat model, protect key use separately, and test recovery. Cloud metadata and instance roles are credential boundaries; restrict workload access and egress.`,
      `Container images are supply-chain artifacts. Build from trusted minimal bases, pin and update digests, create a software inventory and provenance, scan, sign or attest, and verify at admission. Run non-root, drop capabilities, prevent privilege escalation, apply a system-call profile, make roots read-only, bound resources, and avoid host namespaces, privileged mode, broad mounts, and runtime sockets.

Kubernetes uses human and workload authentication, RBAC, admission, Pod security, network policy, secrets, node hardening, and audit. Namespace RoleBindings are preferable to broad cluster grants. Workload creation can indirectly expose secrets or nodes, so analyze transitive privilege. Enforce Restricted Pod security and exact image identity progressively with audited exceptions.`,
      `Infrastructure as code and policy as code make cloud controls reviewable but can distribute one bad change rapidly. Require protected plans, saved artifact identities, state locking, short-lived deployment authority, policy tests, and deletion protection. Detect drift and decide whether to adopt or revert emergency changes.

Cloud security incidents often require rapid identity revocation, snapshot or log preservation, account isolation, and provider coordination. Do not destroy a compromised workload before preserving needed volatile evidence unless containment urgency outweighs it. Rebuild rather than clean, investigate the control plane and credentials, and review other workloads built from the same source.`,
      `Harden a Kubernetes deployment that currently runs a mutable image as root with cluster-admin, public database access, and a secret in environment variables.`,
      `Replace cluster-admin with a dedicated service account and no API permission or token if unnecessary. Deploy a verified digest built with provenance. Require non-root, no privilege escalation, dropped capabilities, RuntimeDefault seccomp, read-only root, narrow temporary volume, and measured resources. Place database privately, allow network only from the application identity and port, and authenticate it separately. Deliver a short-lived database credential through workload identity or a tightly scoped mounted secret with rotation. Enforce policy in audit then deny, protect deployment workflow with federated least privilege, centralize audit, and test that unauthorized Pods, images, networks, and secret access fail.`,
      [
        q('What is a cloud customer still responsible for?', ['Identity, configuration, data use, and recovery requirements', 'Physical security of every provider datacenter', 'Manufacturing disks used by managed storage', 'Writing the provider hypervisor scheduler'], 0, 'Managed services shift selected tasks, not responsibility for customer configuration, access, and data outcomes.'),
        q('Why pin a deployed container by digest?', ['It grants the container more runtime capabilities', 'It identifies exact immutable image content', 'It prevents the image from containing dependencies', 'It replaces the need for build provenance'], 1, 'A digest prevents a movable tag from silently selecting different bytes.'),
        q('What is a Kubernetes privilege-escalation path?', ['Reading a public ConfigMap', 'Viewing one owned Pod log', 'Creating a Pod that mounts a powerful credential', 'Using a readiness probe on a service endpoint'], 2, 'Workload creation can convert available mount or runtime privileges into effective secret or node access.'),
        q('How should cloud incident workloads be restored?', ['By trusting the compromised instance after one scan', 'By reusing every exposed credential unchanged', 'By deleting centralized audit logs for privacy', 'By rebuilding clean and rotating affected authority'], 3, 'Reconstruction from trusted artifacts and external identity response provide a defensible recovery boundary.')
      ]
    ),
    lesson(
      'secrets-key-management',
      'Secrets, keys, rotation, and privileged access',
      `A secret is information whose disclosure grants capability or causes harm: passwords, API tokens, private keys, recovery codes, signing material, and some personal data. Every secret needs owner, purpose, subjects, resource scope, creation, storage, distribution, rotation, revocation, expiry, audit, backup, and deletion. If those cannot be named, the credential is unmanaged.

Prefer eliminating secrets through workload identity, federated short-lived tokens, or public-key authentication. Static shared credentials weaken attribution and accumulate copies. Where a secret remains, generate it with adequate entropy, scope it to one service and environment, store it in a dedicated system, release it only to authenticated workloads, and never expose it through source, images, CI caches, arguments, logs, crash reports, or support bundles.`,
      `Secret managers protect values at rest and control retrieval but do not make broad read access safe. Separate administration, value reading, and policy change. Audit access and alert unusual bulk reads or new principals. Applications should receive the minimum value at the latest useful time and keep it in memory only as needed. Mounted files often support rotation more safely than fixed environment variables when applications reopen them correctly.

Rotation normally creates a new credential, updates consumers, verifies new use, and revokes the old. Dual-valid periods require bounded lifetime. Emergency compromise may revoke first and accept service interruption. Design protocols and applications for multiple verification keys or database credentials so rotation is not a crisis.`,
      `Signing and encryption keys have different lifecycle needs. Losing an encryption key can lose data; retaining a compromised signing key lets attackers forge trust. Hardware-backed or managed keys reduce export but still require access policy, recovery, and provider trust. Root keys and break-glass credentials should be offline or strongly isolated, used rarely, and exercised under dual control.

Secret scanning finds patterns after exposure and cannot identify all secrets. On leak, revoke first, investigate access and use, clean history if policy requires, and improve the originating workflow. Redaction should use exact known secret values and credential-shaped patterns, but preventing emission is stronger.`,
      `Design database credential rotation for ten application replicas with no downtime and an emergency compromise variant.`,
      `Use workload identity to request short-lived database credentials if supported. Otherwise create a new database role secret with the same narrow grants, publish it as a new version, and make applications watch or reopen a protected file and establish new connections while old ones drain. Observe authentication by credential version, then revoke the old role after every replica has switched and the rollback window closes. Never log either value. For compromise, revoke the exposed role immediately, isolate suspicious workloads, issue clean credentials through a trusted control plane, restart or reload consumers, inspect database audit and queries during exposure, and rotate any authority that could mint more credentials.`,
      [
        q('What is the best secret when architecture permits it?', ['No stored secret because short-lived identity replaces it', 'One shared token copied to every workload', 'A password committed in encrypted source text', 'A permanent administrator key in a CI cache'], 0, 'Removing static secret distribution reduces copies, lifetime, and rotation burden.'),
        q('What should a secret manager separate?', ['Every secret into a public URL', 'Policy administration from value retrieval', 'Production and test values into one shared token', 'Authentication from all access decisions'], 1, 'Separating powers reduces the chance one identity can both grant and consume unrestricted access.'),
        q('What is the normal safe rotation sequence?', ['Revoke the only credential before preparing consumers', 'Keep both old and new credentials valid forever', 'Issue new, migrate and verify, then revoke old', 'Print both values to confirm they differ'], 2, 'A bounded overlap supports availability while verification proves every consumer moved.'),
        q('What is the first response to a leaked credential?', ['Rename the source file containing it', 'Add a comment saying it is private', 'Wait for evidence of malicious use', 'Revoke or rotate the exposed authority'], 3, 'The value may already be copied, so invalidating its power is more urgent than history cleanup.')
      ]
    ),
    lesson(
      'detection-engineering',
      'Security logging, detection, and threat hunting',
      `Detection engineering turns threat scenarios into observable, testable analytics and response. Begin with a behavior to detect, affected assets, required data, attacker alternatives, expected false positives, severity, owner, and action. Collecting logs without questions creates cost; writing rules without reliable telemetry creates false confidence.

Useful sources include identity events, endpoint processes and connections, application authorization, cloud control-plane audit, DNS and proxy traffic, email, vulnerability state, data access, and deployment history. Normalize timestamps, identities, hosts, resources, actions, outcomes, and correlation while preserving raw evidence where policy requires. Monitor source health, delay, parsing failures, volume, and schema drift.`,
      `A detection can be a deterministic rule, sequence, statistical baseline, graph relation, or enrichment. Favor attacker behavior over one brittle indicator. For example, a new access key followed by unusual bulk secret reads and outbound transfer is stronger than an unfamiliar IP alone. Enrich with asset criticality, identity role, vulnerability, known maintenance, and prior behavior.

Every alert has a title, hypothesis, scope, severity logic, evidence fields, triage steps, containment choices, false-positive notes, owner, and test. Version detections as code, review them, replay representative benign and malicious fixtures, deploy gradually, and measure firing. Tune by understanding causes rather than suppressing broad categories.`,
      `Threat hunting is hypothesis-driven investigation across available evidence, not browsing random dashboards. A hunt may ask whether any workload used a newly disclosed exploit pattern before the signature existed. Define population and time, query multiple sources, validate samples, record gaps, and turn durable findings into detection or hardening.

Metrics include coverage of prioritized techniques and assets, telemetry health, precision, time from behavior to alert, triage time, escalation quality, and detection gaps found in exercises. A high alert count is not success. Purple-team exercises let controlled attackers and defenders validate the full path from action to response.`,
      `Build a detection for a workload credential used outside its normal runtime, including telemetry, rule, triage, and test.`,
      `Inventory the workload identity, expected issuer, audience, source network, runtime attributes, APIs, and schedule. Collect identity-provider token issuance and cloud API audit with immutable principal identifiers, source, user agent, resource, result, and session linkage. Alert when the principal authenticates without the expected federation claims or from outside approved runtime paths, with stronger severity for policy change, secret access, or unusual region. Triage validates deployment changes, token source, actions, and affected resources. Containment disables the session or role path and isolates the workload. Test with a safe simulated issuance and verify telemetry-loss monitoring so silence cannot masquerade as protection.`,
      [
        q('What should a detection begin with?', ['A threat behavior, needed evidence, and response action', 'The noisiest available log source', 'A goal to maximize daily alert count', 'A permanent suppression for unknown events'], 0, 'A behavioral hypothesis connects telemetry and logic to a meaningful defensive decision.'),
        q('What makes a detection higher confidence?', ['One unfamiliar source address alone', 'Multiple related behaviors enriched with identity and asset context', 'A rule that cannot be tested safely', 'An alert lacking affected resource identity'], 1, 'Correlated behavior and context reduce ambiguity and help prioritize impact.'),
        q('How should detections be maintained?', ['As undocumented console queries owned by nobody', 'By disabling any rule that creates one false positive', 'As versioned tested code with telemetry-health checks', 'By changing severity after each individual alert'], 2, 'Review, fixtures, controlled rollout, and source monitoring make detection behavior reproducible.'),
        q('What is threat hunting?', ['A replacement for all continuous detection', 'Random searching until something looks unusual', 'A process that requires known malware hashes', 'A hypothesis-driven investigation across scoped evidence'], 3, 'Hunts test a defined concern, document gaps, and convert repeatable knowledge into controls.')
      ]
    ),
    lesson(
      'incident-forensics',
      'Security incident response and digital forensics',
      `Security incident response protects systems while preserving enough evidence to understand scope, eradicate persistence, meet legal duties, and restore trust. Prepare contacts, severity, authority, isolation methods, clean communication, evidence storage, legal and privacy escalation, provider support, and recovery before an incident. Use channels and identities that may survive compromise of normal collaboration.

Declare based on credible impact or coordination need, not confirmed attribution. Assign command, technical operations, communications, and scribe. Track facts, hypotheses, decisions, actions, owners, and timestamps. Containment can isolate accounts, hosts, tokens, routes, or features; choose the smallest action that safely limits harm, while recognizing an active attacker may respond.`,
      `Digital forensics preserves and analyzes evidence with provenance. Document who collected what, when, where, how, tool version, hash, transfer, and access. Order of volatility often favors memory, active connections, processes, temporary data, disk, and remote logs, but containment urgency and platform design may change order. Never run untrusted tools on original evidence; acquire defensibly and analyze copies in an isolated environment.

Create a timeline from identity, endpoint, network, application, cloud, and deployment sources normalized to reliable time. Look for initial access, execution, persistence, privilege change, discovery, lateral movement, collection, exfiltration, impact, and cleanup. Absence of logs is not proof an action did not occur.`,
      `Eradication removes attacker access, persistence, vulnerable paths, and compromised artifacts. Rotate authority from clean systems and inspect parent identities that could reissue credentials. Recovery rebuilds from trusted sources, restores validated data, adds temporary monitoring, and returns in phases. A host that looks quiet may remain untrusted.

Communication and notification follow impact, contracts, law, and user harm. Do not speculate about attacker identity or overstate certainty. Afterward, preserve lessons, close temporary access, validate corrective actions, and update threat models and detections. Forensic data is highly sensitive and needs access, retention, and deletion policy.`,
      `Respond to evidence that a CI token downloaded source and secrets from an unusual location and produced an unrecognized release artifact.`,
      `Declare a supply-chain incident and move coordination to a clean channel. Disable the token and related sessions, freeze releases, protect registries and signing systems, and preserve identity, repository, runner, secret-manager, provenance, registry, and deployment logs. Determine token origin, accessible repositories and secrets, commits or workflows changed, artifacts produced, signatures or attestations, and environments reached. Rotate secrets the token could read and authority that could mint it. Mark suspect artifacts and prevent admission by digest. Rebuild clean from verified source on trusted builders, compare provenance and dependency inputs, then restore delivery gradually. Notify affected owners and users from confirmed scope and add federation, runner isolation, and artifact verification controls.`,
      [
        q('When should a security incident be declared?', ['When credible impact or coordination need justifies response', 'Only after the attacker identity is legally proven', 'Only after every affected record is counted', 'When all ordinary logs have been deleted'], 0, 'Early declaration creates roles and evidence discipline while the incident can still be downgraded later.'),
        q('What does chain of custody record?', ['Only the final analyst conclusion', 'Evidence collection, hashes, transfers, and access history', 'The public severity score of one vulnerability', 'A list of tools not used during response'], 1, 'Provenance supports evidence integrity, reproducibility, and legal or organizational trust.'),
        q('Why analyze forensic copies rather than originals?', ['Copies automatically decrypt every artifact', 'Original media cannot contain timestamps', 'Analysis can alter or contaminate evidence', 'Only copies can be hashed'], 2, 'Preserving originals protects integrity while repeatable analysis occurs on controlled duplicates.'),
        q('What is required to restore a compromised host?', ['One antivirus scan reporting no findings', 'Keeping its previous tokens to avoid disruption', 'Deleting central logs that show attacker activity', 'A trusted rebuild plus rotation and validation'], 3, 'Recovery reestablishes trust from clean artifacts and invalidates authority that may have escaped.')
      ]
    ),
    lesson(
      'penetration-testing',
      'Penetration testing and adversarial validation',
      `A penetration test evaluates whether realistic attack paths defeat security objectives under written authorization. It is not a competition to obtain maximum access, a substitute for secure development, or proof that untested paths are safe. Define business goals, assets, target ranges, identities, exclusions, hours, rate limits, allowed techniques, data handling, stop conditions, contacts, and reporting before work.

Methodology moves from passive understanding to active enumeration, vulnerability analysis, safe exploitation where necessary, privilege and lateral path validation, impact proof, cleanup, and reporting. Preserve exact requests, responses, timestamps, tool versions, source addresses, and affected identities. Use the least harmful evidence sufficient to prove a finding.`,
      `Reconnaissance maps exposed assets, technologies, names, certificates, endpoints, and relationships. Enumeration asks the service directly under controlled rates. Validation separates scanner hypotheses from exploitable conditions. Exploitation should demonstrate the violated property without unnecessary persistence, denial of service, or sensitive-data collection. Post-exploitation is permitted only when the scope explicitly authorizes it.

Findings include title, affected assets and versions, prerequisites, reproducible steps, evidence, technical and business impact, likelihood context, root cause, remediation, compensating controls, and retest status. Group related symptoms under the control failure rather than inflating counts. Distinguish observation, inference, and untested possibility.`,
      `Credentials supplied for testing need role coverage and synthetic data. Include unauthenticated, normal user, privileged user, cross-tenant, expired, revoked, and concurrency paths. Test business workflows, not only known vulnerability signatures. Review source when authorized because logic and hidden flows may be impractical to discover externally.

After remediation, retest the exact path and nearby variants, verify no new bypass, and add durable automated checks. Remove accounts, files, payloads, callbacks, and access granted for the engagement. A good report enables repair and learning; withholding reproducibility to make the tester indispensable is unprofessional.`,
      `Plan a two-week assessment of a media API and web client handling private libraries, invitations, imports, and exports.`,
      `Set goals around cross-tenant access, account takeover, unsafe imports, and export abuse. Scope named environments and domains, prohibit production denial of service and real-user data collection, provide synthetic organizations with owner, editor, viewer, invited, revoked, and support roles, and define request limits and emergency contacts. Review architecture and source, enumerate endpoints and old versions, test authentication, object and function authorization, browser flows, file and URL import, race conditions, rate limits, webhook trust, and export lifecycle. Report root causes with minimal evidence and retest. Delete test exports, accounts, callbacks, and payloads and deliver a coverage and limitation statement.`,
      [
        q('What gives a penetration test legitimacy?', ['Explicit authorization and bounded scope', 'The tester finding an open network port', 'A belief that the target has weak security', 'The use of a commercially licensed scanner'], 0, 'Authorization defines what can be tested, how, and under which safety and data conditions.'),
        q('What is the goal of exploitation in a test?', ['Collect as much real data as possible', 'Prove the violated property with minimum harm', 'Maintain hidden persistence after the engagement', 'Cause downtime so impact is visible'], 1, 'Impact can usually be demonstrated safely without maximizing compromise.'),
        q('What should a finding report distinguish?', ['Only high and critical scanner labels', 'Only source and destination IP addresses', 'Observed fact, supported inference, and untested possibility', 'Public details and all captured secrets'], 2, 'Clear epistemic status lets owners reproduce and prioritize without overstating certainty.'),
        q('What follows remediation?', ['Assume the patch works from its commit message', 'Keep tester accounts active indefinitely', 'Delete the regression test to avoid disclosure', 'Retest the path, nearby variants, and cleanup'], 3, 'Validation establishes that the security property changed and engagement artifacts no longer add exposure.')
      ]
    ),
    lesson(
      'governance-privacy',
      'Security governance, privacy, assurance, and culture',
      `Governance connects security decisions to organizational purpose, authority, law, ethics, and accountability. Define policies for identity, data, software, vendors, vulnerability, incident response, continuity, and acceptable use, but keep them short enough to follow and pair them with standards, procedures, and evidence. A policy without owner, enforcement, exception, review, and consequence is aspiration.

Classify systems and data by potential harm so controls scale with risk. High-impact services may require separation of duties, stronger recovery, independent assessment, and shorter remediation. Applying maximum control to every experiment creates shadow systems and weakens respect for policy. Exceptions record scope, reason, risk owner, compensating controls, expiry, and review.`,
      `Privacy engineering limits collection to a specific purpose, informs users, controls access and sharing, keeps data accurate, supports rights, and deletes according to retention. Pseudonymous data remains personal when linkable. Hashing low-entropy identifiers does not anonymize them. Threat models include inference, reidentification, secondary use, overbroad analytics, and sensitive logs or backups.

Vendor risk considers the service, data, access, sub-processors, development practices, incidents, continuity, deletion, audit evidence, and exit. Certifications and questionnaires are signals, not guarantees. Contract requirements need technical enforcement and an owner who can migrate or contain failure.`,
      `Assurance combines design review, code review, automated tests, configuration evidence, exercises, audits, and independent testing. Map controls to risks and preserve evidence continuously rather than staging screenshots once a year. Metrics should drive decisions: privileged-access age, restore success, vulnerability exposure, detection coverage, incident recurrence, and exception expiry.

Culture improves when teams receive usable paved paths, early threat support, blameless learning, and clear accountability. Annual awareness slides are weaker than phishing-resistant authentication, safe defaults, relevant simulations, and rapid help. Security teams should enable routine safe delivery while concentrating judgment on novel high-risk work.`,
      `Create governance for a new recommendation feature using viewing history and optional demographic information.`,
      `Document the user purpose, legal basis or consent, data fields, source, retention, access, model use, outputs, sharing, and deletion. Default to viewing history only and collect demographic data only for a justified fairness purpose with separate consent and access. Separate raw identifiers from analysis, prohibit unrelated advertising use, test reidentification and group harm, and let users inspect and delete history. Threat-model model extraction, sensitive inference, insider queries, logs, exports, and backups. Require a privacy and security launch review, owner, SLO for deletion propagation, incident procedure, vendor restrictions, and scheduled necessity review. Measure outcome without retaining unnecessary raw data.`,
      [
        q('What makes a security policy operational?', ['Owner, enforcement, evidence, exceptions, and review', 'Maximum length and legal vocabulary', 'A rule that no exception can ever exist', 'Publication without implementation guidance'], 0, 'Policy becomes real through authority, controls, evidence, and lifecycle.'),
        q('What does data minimization require?', ['Collect every field in case it is useful later', 'Collect only data necessary for a declared purpose', 'Retain raw data forever to support audits', 'Share identifiers with every service by default'], 1, 'Purpose limitation reduces exposure, secondary use, and deletion burden.'),
        q('Why is a vendor certification insufficient alone?', ['Certifications cannot describe any control', 'Vendors never operate shared infrastructure', 'Actual service scope and customer configuration still matter', 'Certification always transfers all customer liability'], 2, 'Assurance evidence must match the consumed service, access, data, and responsibility boundary.'),
        q('What is a stronger security-culture investment?', ['One generic annual slide deck', 'Punishment for reporting near misses', 'A hidden policy known only to auditors', 'Safe defaults and rapid expert help in normal workflows'], 3, 'Usable systems make correct action easier and encourage early, truthful engagement.')
      ]
    ),
    lesson(
      'capstone-security-operations',
      'Capstones: secure service, detection program, and incident exercise',
      `The final work integrates design, implementation, attack validation, detection, response, and governance. Build a small multi-user media service with private libraries, invitations, file import, export, and an administrative support role. Use synthetic data and a local isolated lab. The goal is to prove security properties and recovery, not merely run scanners.

Capstone A is the secure service. Produce an asset and data inventory, trust-boundary diagram, threat model, authorization matrix, privacy record, cryptographic and secret design, logging schema, and recovery objectives. Implement phishing-resistant or strong local authentication, secure sessions, tenant-scoped authorization, CSRF and XSS defenses, parameterized data access, safe file parsing, SSRF-resistant integration, rate limits, idempotency, protected exports, and deletion.`,
      `Build the service through a trusted pipeline into a non-root container by digest with dependency lock, inventory, provenance, vulnerability policy, and no embedded secrets. Deploy it on a segmented local environment with exact flows, workload identity or narrowly scoped credentials, encrypted transport, backups, and restore instructions.

Capstone B is a detection program. Select ten prioritized threat behaviors across identity, application, endpoint, network, cloud-like control plane, and supply chain. Define required events, health checks, normalized fields, analytics, triage, containment, and fixtures. Implement at least five rules and two hunts. Measure precision on benign traffic and detect missing telemetry.`,
      `Capstone C is an authorized adversarial and incident exercise. Test cross-tenant ids, role escalation, session fixation, CSRF, stored and DOM XSS, injection, unsafe upload, archive traversal, SSRF, webhook replay, rate-limit races, dependency tampering, and secret leakage. Use safe proofs and document coverage.

Then inject one realistic compromise: a stolen workload credential produces an unauthorized export and modified release. Declare the incident, preserve evidence, contain identities and artifacts, investigate scope, rotate authority, rebuild clean, restore or correct data, communicate, and write a learning review. Demonstrate that every corrective action has an owner and regression test or detection.`,
      `Before building, write a security acceptance plan listing each promised property, its prevention control, detection evidence, response, recovery, and exact verification.`,
      `A complete plan maps authentication to passkey or password tests, session rotation and revocation logs; tenant isolation to scoped queries and cross-tenant negative tests; import safety to parser limits and malicious fixtures; supply chain to digest and provenance verification; secrets to runtime delivery and rotation exercise; availability to rate limits, backup, and restore; and incident readiness to immutable audit and a game day. For each property state who owns failure, how long detection and recovery may take, and what evidence closes the claim. The capstones pass only when another person can reproduce the tests, break a control safely, follow the runbook, and recover without hidden credentials or undocumented steps.`,
      [
        q('What is the capstone security deliverable?', ['Verified prevention, detection, response, and recovery properties', 'A scanner report with every finding accepted', 'An application with no documented threat model', 'A public archive of test credentials and evidence'], 0, 'Security mastery connects architecture and implementation to observed behavior under attack and recovery.'),
        q('What should each detection rule include?', ['Only a memorable alert title', 'Telemetry health, test fixtures, triage, and action', 'A permanent exemption for administrative users', 'A requirement to store every payload indefinitely'], 1, 'A detection is an operated control with evidence sources and a response path.'),
        q('How should offensive capstone tests prove impact?', ['By collecting all accessible sensitive records', 'By leaving persistent access for later review', 'With minimal synthetic evidence inside the authorized lab', 'By attacking a similar public service without permission'], 2, 'Bounded synthetic proof establishes the property without expanding harm or scope.'),
        q('When are the capstones complete?', ['When the first container starts successfully', 'When no scanner can connect to the test host', 'When the author can run the happy path once', 'When another person can verify, break, and recover the system'], 3, 'Reproducible independent operation and recovery demonstrate integrated mastery.')
      ]
    )
  ]
}
