import type { ProgQuestion } from './types'

interface LessonPractice {
  practice: string
  solution: string
  questions: ProgQuestion[]
}

const text = (...lines: string[]): string => lines.join('\n')

export const DATABASE_ENGINEERING_PRACTICE: Record<string, LessonPractice> = {
  'relational-model': {
    practice: text('Write SQL DDL for organizations, users, memberships, media, and tracking. One membership is unique per organization and user; one tracking row is unique per membership and media; role is `owner`, `editor`, or `viewer`; score is null or 0 through 100. Add two invalid inserts and predict which constraint rejects each.'),
    solution: text('Use separate tables because each has a different row grain. `membership(id, organization_id REFERENCES organization, user_id REFERENCES user, role CHECK (...), UNIQUE(organization_id,user_id))` represents one user’s role in one organization. `tracking(membership_id REFERENCES membership, media_id REFERENCES media, score CHECK(score BETWEEN 0 AND 100), PRIMARY KEY(membership_id,media_id))` represents current personal state. A duplicate organization/user membership fails `UNIQUE`; score 140 fails `CHECK`. A foreign key protects identity existence, while authorization still belongs in the write path.'),
    questions: [
      { prompt: 'What is the grain of the membership relation?', options: ['One role held by one user inside one organization', 'One organization containing every user and media row', 'One mutable role shared by all organization members', 'One login event emitted whenever a user authenticates'], correct: 0, explain: 'The composite organization and user identity describes one membership fact, with role as an attribute of that fact.' },
      { prompt: 'Which constraint prevents two memberships for the same organization and user?', options: ['CHECK score BETWEEN zero and one hundred', 'UNIQUE on organization_id and user_id', 'FOREIGN KEY from media to organization name', 'DEFAULT role equal to the viewer string'], correct: 1, explain: 'Composite uniqueness enforces the candidate key for the stated membership grain.' },
      { prompt: 'Why should comma-separated media ids not be stored in membership?', options: ['They require more bytes than every normalized model', 'They prevent the database from storing any null value', 'They defeat references, constraints, and useful joins', 'They automatically create duplicate organization rows'], correct: 2, explain: 'Packing several identities into one scalar removes relational constraints and makes membership queries fragile.' },
      { prompt: 'What does the tracking primary key represent?', options: ['One score shared by every member of one tenant', 'One immutable progress event with occurrence time', 'One canonical media title across all organizations', 'One current state per membership and media pair'], correct: 3, explain: 'The pair matches the row grain and prevents two current tracking records for the same member and title.' }
    ]
  },
  'sql-querying': {
    practice: text('Given members M1, M2 and tracking rows `(M1,A)`, `(M1,B)`, write one SQL query returning every member, title count, last event time, and rank by count. M2 has no tracking or events. Show the two output rows and preserve M2.'),
    solution: text('Pre-aggregate before joining: `WITH tc AS (SELECT membership_id, count(*) n FROM tracking GROUP BY membership_id), le AS (SELECT membership_id, max(at) last_at FROM progress_event GROUP BY membership_id) SELECT m.id, coalesce(tc.n,0) AS title_count, le.last_at, dense_rank() OVER (PARTITION BY m.organization_id ORDER BY coalesce(tc.n,0) DESC) AS rank FROM membership m LEFT JOIN tc ON tc.membership_id=m.id LEFT JOIN le ON le.membership_id=m.id`. M1 yields count 2 and rank 1; M2 yields count 0, null time, and rank 2. Separate aggregates prevent event rows multiplying tracking counts.'),
    questions: [
      { prompt: 'Where should a nullable-side predicate stay to preserve a left join?', options: ['In the ON condition when it limits the optional row', 'In a final WHERE clause requiring the optional value', 'Inside LIMIT without an explicit ordering expression', 'In a string concatenated from untrusted request input'], correct: 0, explain: 'A predicate in ON filters optional matches while retaining the required left-side row with nulls.' },
      { prompt: 'Why aggregate tracking and events before joining them?', options: ['It forces the optimizer to use nested loops only', 'It prevents two one-to-many joins multiplying rows', 'It converts every missing timestamp into current time', 'It removes the need to state the output row grain'], correct: 1, explain: 'Each pre-aggregate produces one row per member, so their join preserves the intended member grain.' },
      { prompt: 'Which anti-join behaves clearly when the subquery may contain null?', options: ['value NOT IN followed by a nullable subquery', 'LIMIT one without a deterministic sort key', 'NOT EXISTS with an explicit correlated predicate', 'A dynamic table name passed as a value parameter'], correct: 2, explain: 'NOT EXISTS tests matching rows directly and avoids the unknown result caused by null inside NOT IN.' },
      { prompt: 'What makes cursor pagination deterministic for tied timestamps?', options: ['Ordering only by the non-unique timestamp value', 'Applying DISTINCT after returning an arbitrary page', 'Increasing OFFSET whenever a row is inserted', 'Ordering by timestamp and a unique tie-breaker'], correct: 3, explain: 'A complete unique ordering gives every row one stable position and a cursor that resumes without ambiguity.' }
    ]
  },
  'storage-pages': {
    practice: text('Estimate space for 1,000,000 fixed-size event rows: 80 bytes per row, 16 bytes row overhead, one 24-byte index entry, and 20% page free space for table and index. Ignore page headers. Then predict whether updating an indexed status on every row increases log and index work.'),
    solution: text('Raw table bytes are `1,000,000 × 96 = 96 MB`; with 20% free space, allocate `96 / 0.8 = 120 MB`. Raw index bytes are 24 MB and allocate `24 / 0.8 = 30 MB`. Estimated combined space is 150 MB before page headers, tree overhead, versions, and backups. Updating an indexed status writes row versions or pages, index entries, and recovery log; the actual amplification must be loaded and measured under the selected engine.'),
    questions: [
      { prompt: 'What is the estimated table allocation before page headers?', options: ['120 MB after allowing twenty percent free space', '96 MB after removing all per-row overhead', '80 MB because only payload bytes occupy pages', '150 MB including an index that was not requested'], correct: 0, explain: 'The 96 MB encoded rows occupy 80% of allocated pages, so 96 divided by 0.8 gives 120 MB.' },
      { prompt: 'What is the estimated combined table and index allocation?', options: ['126 MB by adding raw index bytes to raw rows', '150 MB after applying free space to both structures', '104 MB because index entries replace row overhead', '174 MB by multiplying every byte count by twenty percent'], correct: 1, explain: 'The table estimate is 120 MB and the index estimate is 30 MB, totaling 150 MB.' },
      { prompt: 'Why can one logical update write more than one structure?', options: ['The database stores each row in every available table', 'The operating system converts SQL into duplicated files', 'Row, index, and recovery-log state may all change', 'A commit always rewrites the complete database image'], correct: 2, explain: 'Physical durability and access structures create write amplification beyond the changed logical value.' },
      { prompt: 'Which observation best checks the estimate?', options: ['A source-code count of INSERT statement characters', 'A file timestamp immediately after one transaction', 'A row count without index or version statistics', 'Measured table, index, log, and backup growth'], correct: 3, explain: 'Representative loaded data and engine statistics expose encoding, page, version, and maintenance overhead omitted by estimation.' }
    ]
  },
  indexes: {
    practice: text('For `SELECT id,title FROM event WHERE tenant_id=? AND occurred_at<? ORDER BY occurred_at DESC,id DESC LIMIT 50`, propose one B-tree index. Explain which predicate uses equality, which uses range/order, and why `id` belongs last. Compare with an index beginning on `status` where 90% of rows share one status.'),
    solution: text('Use `(tenant_id, occurred_at DESC, id DESC)` and include `title` only if measured lookup savings justify duplication. Tenant is the equality prefix; occurred_at supplies the range and primary order; id completes deterministic order and cursor comparison. A status-leading index is weak for this query and low selectivity means scanning most entries. Validate with realistic tenant skew and write volume, not an empty-table plan.'),
    questions: [
      { prompt: 'Which index best supports the stated tenant cursor query?', options: ['tenant_id, occurred_at descending, id descending', 'occurred_at alone without tenant or a stable tie-breaker', 'status followed by title and no event identity', 'id alone in ascending order for every tenant'], correct: 0, explain: 'Equality on tenant followed by ordered range and unique tie-breaker matches filtering and pagination.' },
      { prompt: 'Why place the unique id after occurred_at?', options: ['It makes tenant authorization unnecessary in SQL', 'It breaks timestamp ties for stable cursor order', 'It prevents every update from touching the index', 'It lets value parameters replace column identifiers'], correct: 1, explain: 'The id provides a unique final ordering component when several events share the same timestamp.' },
      { prompt: 'When is a partial index especially useful?', options: ['When every row always satisfies its predicate', 'When clients choose arbitrary indexed expressions', 'When queries target a stable selective row subset', 'When no workload query contains the indexed columns'], correct: 2, explain: 'A stable selective predicate can exclude terminal or irrelevant rows, shrinking both reads and write maintenance.' },
      { prompt: 'What is the main cost of adding another covering index?', options: ['It disables all constraints on the base relation', 'It makes every query use the same join algorithm', 'It removes cached pages after each read operation', 'It adds storage and maintenance to affected writes'], correct: 3, explain: 'Included data can avoid lookups, but duplicates bytes and must be updated whenever indexed values change.' }
    ]
  },
  'query-planning': {
    practice: text('A plan estimates 100 tenant rows but reads 1,000,000; its hash join spills 800 MB and latency is 18 seconds for one large tenant. Write a diagnosis sequence and compare two fixes: tenant-first composite index versus forcing nested loops. State the evidence required before deployment.'),
    solution: text('Capture large and ordinary tenant parameter cases, actual rows, I/O, waits, memory, and plan identity. The 10,000-fold underestimate points to skew or correlated stale statistics. Refresh or improve statistics and test a tenant-first composite path matching the filter. Do not force nested loops: one million inner lookups may worsen the large case and freeze a brittle plan. Benchmark mixed concurrency, verify estimates and spill fall, then canary on tail latency, throughput, lock time, and regression for small tenants.'),
    questions: [
      { prompt: 'What does 100 estimated versus 1,000,000 actual rows indicate?', options: ['A severe cardinality estimate error worth investigating', 'A guaranteed storage corruption in the heap file', 'Proof that the SQL result contains duplicate columns', 'A network timeout before the optimizer ran'], correct: 0, explain: 'Join and memory choices depend on estimated cardinality; a 10,000-fold miss can explain the spill and bad plan.' },
      { prompt: 'Why is forcing nested loops risky for the large tenant?', options: ['Nested loops cannot execute equality predicates', 'They may perform a million repeated inner lookups', 'They always require more memory than a hash join', 'They make all transaction isolation levels serializable'], correct: 1, explain: 'A nested loop often excels with a small outer input but can amplify work catastrophically when the outer side is huge.' },
      { prompt: 'Which benchmark protects ordinary tenants from the proposed fix?', options: ['One cold execution using only the largest tenant', 'An EXPLAIN estimate without running the read query', 'Mixed concurrent traffic with small and large tenants', 'A microbenchmark of string formatting outside SQL'], correct: 2, explain: 'The real workload mix reveals whether a large-tenant improvement steals resources or regresses common requests.' },
      { prompt: 'Which canary signal most directly detects recurrence?', options: ['Total number of source files in the release', 'Average host CPU with no query attribution', 'Database size measured once before deployment', 'Plan identity, cardinality error, spill, and tail latency'], correct: 3, explain: 'These signals connect the changed plan to the misestimate, resource consequence, and user-visible latency.' }
    ]
  },
  transactions: {
    practice: text('Write a seat claim transaction for event E with `remaining=1`. Two requests R1 and R2 run concurrently. Use one conditional update, reservation insertion, and outbox insertion. Trace affected-row counts and final rows when R1 wins.'),
    solution: text('Each request begins a transaction and runs `UPDATE event SET remaining=remaining-1 WHERE id=\'E\' AND remaining>0`. R1 affects one row, inserts reservation unique on R1 plus its outbox event, and commits. R2 then affects zero rows and rolls back or stores a sold-out result without inserting a reservation. Final remaining is 0, with one reservation and one corresponding outbox event. A repeated R1 retrieves its idempotency result rather than decrementing again.'),
    questions: [
      { prompt: 'Which statement atomically decides the last-seat race?', options: ['A conditional decrement requiring remaining greater than zero', 'A SELECT committed in a transaction before the UPDATE', 'An application counter cached separately by each process', 'A nightly query that removes excess reservations'], correct: 0, explain: 'The conditional write makes availability testing and decrement one database decision under concurrency.' },
      { prompt: 'What should R2 do after its conditional update affects zero rows?', options: ['Insert a reservation and let remaining become negative', 'Return sold out without creating the reservation', 'Retry the final INSERT outside the transaction', 'Call payment first and check capacity afterward'], correct: 1, explain: 'Zero affected rows means the capacity predicate was false; no reservation side effect should be committed.' },
      { prompt: 'Why keep the outbox insert in the reservation transaction?', options: ['It causes email to be sent before commit completes', 'It gives the message broker a lock on event rows', 'It prevents committed reservation without recorded event', 'It guarantees every consumer processes exactly once'], correct: 2, explain: 'Atomic recording ensures a publisher can eventually emit every committed business change.' },
      { prompt: 'After R1 wins, what is the valid final database state?', options: ['Remaining 1 with two reservations and no event', 'Remaining -1 with both requests marked successful', 'Remaining 0 with no durable reservation record', 'Remaining 0 with one reservation and one outbox row'], correct: 3, explain: 'The transaction couples the successful capacity decrement, reservation fact, and publishable event.' }
    ]
  },
  'isolation-mvcc': {
    practice: text('Team T has active admins A and B. Under snapshot isolation, transactions X and Y each read count 2; X deactivates A while Y deactivates B, then both commit. Trace the invariant. Redesign with a team guard row and state the lock order.'),
    solution: text('X and Y update different membership rows, so ordinary write-conflict detection may allow both commits. The final active-admin count is 0: a write-skew anomaly. Add a stable team guard row. Each role-removal transaction locks that row first, then counts active admins and updates one membership only if another remains. X commits, then Y obtains the guard and sees count 1, so Y refuses. Serializable isolation with full transaction retry is another valid engine-specific solution.'),
    questions: [
      { prompt: 'What anomaly occurs when X and Y both commit their disjoint updates?', options: ['Write skew violates the cross-row administrator rule', 'Dirty read exposes one transaction’s uncommitted row', 'A lost update overwrites the same membership column', 'A phantom inserts an unrelated organization record'], correct: 0, explain: 'Each transaction makes a valid decision from its snapshot but their disjoint writes jointly violate the predicate.' },
      { prompt: 'Why does locking one stable team guard row help?', options: ['It deletes every old MVCC version immediately', 'It serializes decisions about the shared team invariant', 'It changes both membership ids into one primary key', 'It lets readers ignore every transaction boundary'], correct: 1, explain: 'The common lock creates a conflict point for transactions that otherwise update different member rows.' },
      { prompt: 'What must happen after a serialization failure?', options: ['Retry only the last UPDATE using old reads', 'Ignore the error because no deadlock occurred', 'Retry the complete idempotent transaction with bounds', 'Lower isolation until the same schedule can commit'], correct: 2, explain: 'The original reads and decisions are invalidated, so the full transaction must be re-executed from a fresh view.' },
      { prompt: 'Which final state is valid after guarded concurrent removals?', options: ['Both A and B inactive because each saw count two', 'Neither transaction records whether it committed', 'Both active because every concurrent write is rejected', 'Exactly one remains active and the other removal fails'], correct: 3, explain: 'Serializing the check and update preserves at least one active administrator while allowing one valid removal.' }
    ]
  },
  'schema-evolution': {
    practice: text('Migrate populated `task.status TEXT NOT NULL` values `todo` and `done` to `status_id` referencing a status table while old and new application versions overlap. Write six ordered deployment steps, a resumable backfill statement shape, and the rollback point.'),
    solution: text('First add the status table and nullable `status_id`; seed fixed ids. Deploy code that writes both and reads id with text fallback. Backfill bounded primary-key ranges with `UPDATE ... SET status_id=(SELECT id ...) WHERE id>? AND id<=? AND status_id IS NULL`, recording each watermark. Report unknown text rather than guessing. Validate zero unmapped rows and equivalent results, then add the reference and required constraint using the engine’s low-lock path. Switch all readers, stop text writes, and retain the old column through the rollback window; drop it only in a later release.'),
    questions: [
      { prompt: 'Why add status_id as nullable during expansion?', options: ['Old rows and old code can coexist during migration', 'Null automatically maps every legacy status string', 'It forces the entire table to rewrite immediately', 'It permits deleting the text column in the same release'], correct: 0, explain: 'The compatible shape lets existing rows and binaries operate while the new representation is populated and adopted.' },
      { prompt: 'What makes the backfill safely resumable?', options: ['One unbounded update inside a day-long transaction', 'Stable primary-key chunks plus recorded watermarks', 'Random row selection repeated until counts look close', 'Dropping every constraint before transforming values'], correct: 1, explain: 'Deterministic chunks and progress state let interruption resume without restarting or skipping unknown ranges.' },
      { prompt: 'When is it safe to require status_id?', options: ['Immediately after adding the empty column', 'Before identifying unknown legacy text values', 'After complete mapping and invariant validation', 'Only after deleting all previous database backups'], correct: 2, explain: 'The required constraint should follow proof that every existing row maps correctly and writers populate it.' },
      { prompt: 'Why retain the old text column through a rollback window?', options: ['It permanently becomes the source of truth again', 'It improves every index built on status_id', 'It removes the need to monitor dual-write drift', 'An older application may still need its compatible shape'], correct: 3, explain: 'Rollback remains possible while old binaries can read the representation they understand.' }
    ]
  },
  'partitioning-retention': {
    practice: text('Assign events at `2026-01-31 23:59:59Z`, `2026-02-01 00:00:00Z`, and `2026-02-28 23:59:59Z` to half-open monthly partitions. A seven-year legal hold covers the February tenant. Write the January retention decision and tests for a missing March partition.'),
    solution: text('Use half-open ranges: January `[2026-01-01,2026-02-01)` receives the first event; February `[2026-02-01,2026-03-01)` receives the latter two. January may be detached after the approved retention cutoff, backup, count validation, and recovery window if it has no hold. February cannot be dropped while the hold applies. A March event with no partition must fail visibly or enter an explicit quarantine, trigger an alert, and never disappear into an unexamined default partition.'),
    questions: [
      { prompt: 'Which partition receives 2026-02-01 at exactly midnight UTC?', options: ['February under a half-open monthly range', 'January because the timestamp touches its end', 'Both months so retention keeps a duplicate copy', 'No month because boundary instants are unsupported'], correct: 0, explain: 'A half-open January range excludes its upper bound, which is exactly the inclusive start of February.' },
      { prompt: 'What does the February legal hold change?', options: ['It changes every event timestamp to the hold date', 'It blocks normal deletion of the held February data', 'It requires dropping the partition before taking backup', 'It removes tenant filtering from all February queries'], correct: 1, explain: 'A hold overrides the ordinary lifecycle cutoff for covered data until governed release.' },
      { prompt: 'How should a missing future partition surface?', options: ['Silently discard events beyond known boundaries', 'Route them to last month and repair eventually', 'Reject or quarantine visibly and alert the owner', 'Create an unbounded number of partitions per event'], correct: 2, explain: 'Visible failure prevents silent loss or misplacement and gives operations a bounded repair path.' },
      { prompt: 'What is a safe first step before permanent partition deletion?', options: ['Remove every backup that still contains the data', 'Disable the legal-hold check to simplify retention', 'Delete the catalog entry before validating row counts', 'Detach it for a documented recovery window'], correct: 3, explain: 'Detachment makes the lifecycle operation fast and reversible while validation and recovery time remain.' }
    ]
  },
  'replication-ha': {
    practice: text('Primary P has log sequence 105. Replica R1 replayed 105; R2 replayed 102. P becomes isolated but still runs. Choose a promotion candidate, list fencing and routing order, and state possible data loss under asynchronous acknowledgement if commits 103-105 reached only P.'),
    solution: text('First revoke P’s write authority through the independent control plane; process health alone is not fencing. R1 is the best candidate because it has replayed through 105. Promote it once, update write routing, validate recent commits and invariants, then rebuild redundancy. If only P had records 103-105 and the reachable candidate were R2, asynchronous failover could lose those three log positions. Preserve P for reconciliation and never permit it to rejoin as writer automatically.'),
    questions: [
      { prompt: 'Which replica is the stated best promotion candidate?', options: ['R1 because it has replayed through sequence 105', 'R2 because its lower sequence means fewer writes', 'Either replica because process health implies equality', 'The isolated primary without changing its authority'], correct: 0, explain: 'R1 has the most complete confirmed replay position and therefore minimizes acknowledged-data risk.' },
      { prompt: 'What must happen before promoting R1?', options: ['Delete all logs from the former primary immediately', 'Fence P so it can no longer accept valid writes', 'Route half of new writes to P and half to R1', 'Declare R2 a backup without checking its replay state'], correct: 1, explain: 'Fencing prevents two writers after network recovery, which would create split brain and divergent histories.' },
      { prompt: 'If failover can reach only R2, how many listed log positions may be lost?', options: ['Zero because every acknowledged write is synchronous', 'One because only the latest log position is vulnerable', 'Three positions: 103, 104, and 105', 'One hundred and two positions already replayed by R2'], correct: 2, explain: 'R2 ends at 102, so the three later positions are absent if no other durable copy has them.' },
      { prompt: 'Why is a replica insufficient as the only recovery mechanism?', options: ['It cannot retain any transaction log positions', 'It always serves data from a different schema version', 'It prevents the primary from acknowledging commits', 'It can replay accidental deletion and corruption'], correct: 3, explain: 'High-availability copies follow the live change stream, including harmful changes that independent backups must recover.' }
    ]
  },
  'distributed-databases': {
    practice: text('Route tenant ids with `hash(id) mod 4`: T1=0, T2=1, T3=2, T4=3, while T2 owns 60% of rows. Design an order write spanning customer and inventory facts, then explain why a cross-shard transaction or saga is required and how to split T2 safely.'),
    solution: text('Simple hashing puts each tenant on one shard but leaves T2 as a hotspot despite nominally even tenant counts. If customer and inventory share no shard key, a single atomic order needs distributed transaction support; otherwise model a saga with reserved inventory, compensating release, durable state, idempotent steps, and reconciliation. Split T2 by a stable subkey such as account or region only after confirming access locality. Use virtual partitions, copy plus change capture, checksum, versioned routing cutover, and rollback retention.'),
    questions: [
      { prompt: 'Why is the four-shard tenant mapping still unbalanced?', options: ['T2 alone owns sixty percent of all rows', 'Modulo routing stores every tenant on shard zero', 'Four shards require at least five tenant identities', 'Hash routing duplicates each row across all shards'], correct: 0, explain: 'Uniform key counts do not imply uniform data or traffic when one tenant is much larger than the others.' },
      { prompt: 'When does an order need cross-shard coordination?', options: ['Whenever its response contains more than one field', 'When one invariant changes facts on separate shards', 'Whenever a replica serves a read-only query', 'When all changed rows share one shard key'], correct: 1, explain: 'An invariant spanning independently committed stores needs a distributed atomic mechanism or explicit workflow semantics.' },
      { prompt: 'What makes a saga compensating release safe to retry?', options: ['A new random reservation identity on each attempt', 'An in-memory flag owned by one worker process', 'A stable step identity and conditional transition', 'A fixed delay assumed longer than every failure'], correct: 2, explain: 'Durable identity and state conditions make repeated workflow messages converge without returning inventory twice.' },
      { prompt: 'Which evidence supports deleting T2’s old shard copy?', options: ['The initial bulk copy process exited successfully', 'One client read succeeded through the new router', 'The destination has more free disk than the source', 'Caught-up changes, checksums, cutover health, and expired rollback'], correct: 3, explain: 'Data validation, observed routing, and a completed rollback window are needed before cleanup becomes irreversible.' }
    ]
  },
  'backup-recovery': {
    practice: text('A full backup was taken Sunday 00:00, incrementals daily at 00:00, and continuous logs exist. A deletion committed Wednesday 14:20 and was discovered at 15:00. Choose the restore chain and recovery timestamp, then list checks before selectively restoring the affected tenant.'),
    solution: text('Restore Sunday’s full backup into an isolated secured environment, apply Monday-through-Wednesday incremental state as the backup format requires, then replay logs to immediately before 14:20. Never overwrite production wholesale while other tenants keep writing. Validate database integrity, schema version, tenant row counts, references, object dependencies, and the exact deletion boundary. Export the affected tenant with stable ids and merge through an idempotent reviewed repair that reconciles legitimate post-14:20 events.'),
    questions: [
      { prompt: 'To what point should the isolated recovery copy replay logs?', options: ['Immediately before the Wednesday 14:20 deletion', 'Wednesday 15:00 when the deletion was discovered', 'The end of all available logs including deletion', 'Sunday 00:00 without any later incremental data'], correct: 0, explain: 'Point-in-time recovery stops just before the harmful transaction so the desired tenant state still exists.' },
      { prompt: 'Why restore into an isolated environment first?', options: ['It lets backups bypass encryption and access controls', 'It avoids overwriting valid writes from other tenants', 'It guarantees every external object is already consistent', 'It removes the need to identify the deletion boundary'], correct: 1, explain: 'Isolation allows validation and selective extraction while production continues to contain legitimate later work.' },
      { prompt: 'What converts stored backups into evidence of recoverability?', options: ['A green scheduled-copy job with no restore attempt', 'Replication lag below one second in normal traffic', 'Repeated restore drills with invariant validation', 'Retention of encrypted files after losing every key'], correct: 2, explain: 'Only a restore proves artifacts, keys, procedures, dependencies, and expected application state work together.' },
      { prompt: 'Which artifact must remain independently recoverable?', options: ['The source database connection pool size', 'The application process identifier at backup time', 'The cache contents present during the deletion', 'The encryption keys needed to read backup data'], correct: 3, explain: 'Perfect backup ciphertext is useless if all copies of the required decryption keys are lost with the primary system.' }
    ]
  },
  'observability-tuning': {
    practice: text('After release R2, checkout p95 rises from 200 ms to 1.8 s. Database CPU stays 45%, pool wait rises from 5 ms to 900 ms, and lock wait rises from 10 ms to 700 ms. Form a hypothesis, name the trace evidence, propose one change, and define canary rollback thresholds.'),
    solution: text('Moderate CPU does not clear the database: increased pool and lock wait indicate transactions occupy connections while blocked or doing remote work. Trace checkout through transaction begin/end and dependency spans; compare R1 and R2 query counts and transaction duration. Remove a newly introduced remote call from the transaction or shorten its scope, then reproduce at representative concurrency. Canary R2 with abort thresholds such as p95 above 400 ms, pool wait above 100 ms, increased lock wait, or business-success regression; retain immediate rollback.'),
    questions: [
      { prompt: 'Which evidence most strongly points to transaction contention?', options: ['Pool wait 900 ms and lock wait 700 ms', 'Database CPU remaining at forty-five percent', 'A release identifier changing from R1 to R2', 'Checkout having a human-readable operation name'], correct: 0, explain: 'The sharp rises in connection acquisition and lock waiting directly explain latency without saturated CPU.' },
      { prompt: 'What trace change would support the remote-call hypothesis?', options: ['Fewer source files packaged in release R2', 'A dependency span nested inside the SQL transaction', 'A lower cache-hit ratio on an unrelated endpoint', 'A new dashboard color for successful checkouts'], correct: 1, explain: 'A slow remote span between transaction begin and commit shows locks and a pool slot held during network delay.' },
      { prompt: 'How should one tuning change be evaluated?', options: ['Change memory, pool size, and query shape together', 'Compare only average latency on an empty database', 'Test one hypothesis under representative concurrency', 'Keep the change even when business success declines'], correct: 2, explain: 'A controlled change under realistic load makes cause and effect interpretable and retains safe rollback.' },
      { prompt: 'Which result should abort the canary?', options: ['Database CPU remains below one hundred percent', 'One fast request completes during warm-up', 'The release produces fewer informational log lines', 'Pool wait crosses the declared 100 ms threshold'], correct: 3, explain: 'A predeclared user-related saturation threshold gives the rollout an objective stop condition.' }
    ]
  },
  'security-governance': {
    practice: text('Create an access matrix for app-runtime, migration, analyst, backup, and support roles over private library rows. Then trace deletion of user U7 through primary tables, search index, export files, analytics, logs, and a backup later restored. State one verification query or artifact per copy.'),
    solution: text('Runtime receives parameterized tenant-scoped read/write only; migration gets time-limited schema rights; analyst reads minimized pseudonymous views; backup reads encrypted snapshots but cannot serve queries; support has no default content access and receives approved expiring grants. Deletion removes or anonymizes primary and derived rows, deletes exports, preserves only non-sensitive audit proof, and emits a tombstone. Search and analytics acknowledge that identity; logs follow redaction and retention. A restored backup must replay tombstones before service. Verify zero scoped rows, absent index ids and files, analytics deletion receipt, and restore rehearsal results.'),
    questions: [
      { prompt: 'Which role should normally alter production schema?', options: ['A time-limited migration identity with audited scope', 'The application runtime used by every request', 'An analyst role reading pseudonymous aggregates', 'A support role created for user conversations'], correct: 0, explain: 'Separating migration authority from runtime access limits compromise impact and preserves accountability.' },
      { prompt: 'What should support access to private library content require?', options: ['A permanent shared administrator password', 'Approved purpose, expiry, and recorded reads', 'An exported production copy on a laptop', 'Membership in the same network security group'], correct: 1, explain: 'Time-bounded approval and auditing enforce purpose limitation instead of giving support standing content access.' },
      { prompt: 'How should a restored old backup handle U7’s prior deletion?', options: ['Serve immediately because the backup predates closure', 'Restore search but omit only the relational user row', 'Replay durable deletion tombstones before serving', 'Keep U7 until the ordinary retention period restarts'], correct: 2, explain: 'Deletion intent must survive restore, or recovery silently resurrects data the system promised to remove.' },
      { prompt: 'Why is encryption at rest insufficient against an overprivileged analyst?', options: ['It prevents the engine from reading authorized pages', 'It removes identity from every derived dataset', 'It automatically applies tenant scope to each query', 'Authorized queries can still return decrypted private data'], correct: 3, explain: 'Storage encryption protects lost media, while database authorization governs what a connected principal may read.' }
    ]
  },
  'capstone-database': {
    practice: text('For a multi-organization media platform, write a traceability row for invariant “one current tracking row per membership and media.” Include grain, constraint, transaction race, query, metric, alert, repair, and restore check. Then run a schedule where two clients insert the same pair.'),
    solution: text('Grain is one current state per `(membership_id,media_id)` and a composite primary key enforces it. Both clients may attempt insertion, but exactly one succeeds; the loser handles the uniqueness result by reading or conditionally updating the existing row under the operation contract. Queries always scope organization through membership. Monitor uniqueness conflicts by operation and release, alert on unexpected rate, and repair only after reconciling event history. Restore validation groups by the pair and expects maximum count one, then checks current state against immutable progress events.'),
    questions: [
      { prompt: 'Which mechanism directly enforces the capstone tracking invariant?', options: ['A composite key on membership_id and media_id', 'A dashboard counting rows once each morning', 'A client check before sending the insert request', 'A repair script remembered by the primary operator'], correct: 0, explain: 'The database constraint decides concurrent attempts at the durable boundary where the duplicate could be stored.' },
      { prompt: 'What should the losing concurrent insert do?', options: ['Disable the unique constraint and insert again', 'Handle the conflict under the documented operation contract', 'Assume the winner belongs to the same tenant', 'Delete the winner before checking its identity'], correct: 1, explain: 'A uniqueness race is an expected outcome; the service must read or update only under correct scoped semantics.' },
      { prompt: 'Which restore query checks the row-count part of this invariant?', options: ['Count every media row without grouping identities', 'Select the newest backup filename from storage', 'Group by the pair and find counts greater than one', 'Order tracking by title and inspect the first page'], correct: 2, explain: 'Grouping by the candidate key exposes any restored duplicate that violates the one-row grain.' },
      { prompt: 'What makes the traceability row operationally complete?', options: ['A schema diagram without failure or recovery behavior', 'One successful query plan on an empty database', 'A list of tools with no ownership or expected result', 'Constraint, race test, signal, owner, repair, and restore proof'], correct: 3, explain: 'Production mastery connects each promise to enforcement, adversarial evidence, detection, responsibility, and recovery.' }
    ]
  }
}
