import type { ProgCourseDef, ProgQuestion } from './types'
import { masteryLesson } from './masteryCourse'
import { FULL_STACK_WEB_APPLIED } from './fullStackWebApplied'

const TOPIC_KEYS: Record<string, string> = {
  'web platform': 'web-platform',
  'semantic HTML': 'semantic-html',
  'CSS engineering': 'css-cascade',
  'responsive layout': 'layout-responsive',
  'JavaScript language': 'javascript-language',
  'DOM and events': 'dom-events',
  'asynchronous web code': 'async-web-apis',
  'TypeScript tooling': 'typescript-tooling',
  'accessible forms': 'accessibility-forms',
  'React components': 'react-components',
  'application state': 'state-routing',
  'server API design': 'server-api',
  'web identity and data': 'auth-data',
  'full-stack testing': 'testing-quality',
  'web performance and delivery': 'performance-delivery',
  'full-stack mastery': 'capstone-fullstack'
}

const authoredQuestions = (topic: string): ProgQuestion[] => {
  const key = TOPIC_KEYS[topic]
  if (!key) throw new Error(`Missing authored questions for ${topic}`)
  return FULL_STACK_WEB_APPLIED[key].questions
}

const lesson = (
  key: string,
  title: string,
  foundations: string,
  engineering: string,
  judgment: string,
  practice: string,
  solution: string,
  questions: ProgQuestion[]
) => {
  const applied = FULL_STACK_WEB_APPLIED[key]
  if (!applied) throw new Error(`Missing applied lesson for ${key}`)
  return masteryLesson(
    key,
    title,
    foundations,
    engineering,
    judgment,
    `${practice}\n\n### Concrete exercise\n\n${applied.practice}`,
    `${solution}\n\n### Worked trace and troubleshooting\n\n${applied.solution}`,
    questions
  )
}


export const FULL_STACK_WEB_COURSE: ProgCourseDef = {
  key: 'full-stack-web',
  title: 'Full-stack web engineering: beginner to master',
  description:
    'A self-contained path through web standards, accessible interfaces, TypeScript and React, servers, APIs, authentication, data, testing, performance, and a production capstone.',
  lessons: [
    lesson('web-platform', 'How the web works', `A URL selects a scheme, authority, path, query, and fragment. DNS resolves names, TCP or QUIC carries bytes, TLS authenticates and protects transport, and HTTP exchanges requests and responses. Browsers then parse HTML, CSS, and JavaScript into document, style, layout, paint, and compositing work. Learn these boundaries before choosing a framework: every web application ultimately ships through them.`, `Use semantic server responses, explicit status codes, cache metadata, content types, character encoding, and progressive enhancement. Separate origin, site, and URL concepts. Inspect requests in developer tools and reproduce them with a command-line client. Treat redirects, cookies, caches, proxies, service workers, and browser history as observable state rather than magic.`, `A page can work on one machine while failing through stale DNS, certificate mismatch, cache variance, blocked mixed content, incorrect base path, or a JavaScript error. Diagnose from navigation to response to rendering. Preserve useful content when scripts are slow or unavailable, and never disable transport verification to hide an identity problem.`, `Trace one page load from typed URL to painted content and name the evidence available at every boundary.`, `Resolve the hostname, establish protected transport for the exact name, send an HTTP request, validate status and headers, parse HTML into the DOM, fetch referenced assets under origin and cache rules, calculate CSS, lay out boxes, paint, and run deferred scripts. Use network timing, console, DOM, accessibility tree, performance trace, and server logs to locate failure without guessing.`, authoredQuestions('web platform')),
    lesson('semantic-html', 'Semantic HTML and document structure', `HTML describes meaning and relationships: headings form an outline, landmarks divide navigation and main content, links navigate, buttons perform actions, labels name controls, lists group peers, tables express tabular relationships, and media includes alternatives. Native elements carry keyboard and accessibility behavior that generic containers do not. Valid nesting and a meaningful source order benefit every presentation.`, `Build content-first documents with language, title, metadata, one clear main region, ordered headings, descriptive links, correct lists, and forms whose labels and errors are programmatically connected. Use images with purpose-appropriate alternative text and width and height to reserve layout. Tables need headers and scope; decorative images use empty alternatives.`, `Do not recreate buttons or links from clickable divs. ARIA can expose semantics but does not add keyboard behavior, focus, validation, or state management. Use it only when native HTML cannot express the interface. Heading size is CSS, not a reason to choose the wrong level. Test the DOM and accessibility tree with CSS removed and keyboard only.`, `Mark up a media-detail page containing navigation, title, cover, facts, actions, cast list, progress form, and related titles.`, `Use a header and navigation landmark, main element, one page heading, a figure only if the cover has a caption, definition list for facts, real buttons for mutations, labeled progress inputs with described validation, section headings for cast and relations, and lists of links to details. Keep DOM order logical before arranging columns with CSS, and announce saved status through an appropriate live region rather than moving focus unexpectedly.`, authoredQuestions('semantic HTML')),
    lesson('css-cascade', 'CSS cascade, boxes, and maintainable styling', `CSS rules select elements and assign property values. The cascade resolves origin, importance, layer, specificity, scope, and source order; inheritance then supplies selected properties to descendants. Every visible element participates in the box model of content, padding, border, and margin. With border-box sizing, declared width includes padding and border, reducing layout surprises.`, `Use custom properties for semantic design tokens such as surface, text, spacing, radius, and motion. Organize intentional cascade layers for reset, base, components, and utilities. Prefer class and attribute selectors with modest specificity. Use logical properties so layout adapts to writing direction. Let content determine height and handle overflow deliberately.`, `Avoid global important declarations, deep descendant selectors, arbitrary z-index escalation, fixed heights for variable text, and color as the only state signal. A selector that depends on the entire DOM is brittle. Test zoom, long translations, forced colors, reduced motion, and missing media. Inspect computed styles to identify the winning declaration instead of adding stronger rules blindly.`, `Create tokens and component styles for cards, buttons, fields, validation, and a dark theme without duplicating every rule.`, `Define semantic color and spacing properties at the root, override token values under a theme attribute, and have components consume tokens. Give buttons shared structure plus explicit variants and states. Associate fields and messages structurally, use currentColor where useful, preserve focus visibility, and meet contrast. Place component rules in a predictable layer so variants override by design rather than specificity tricks.`, authoredQuestions('CSS engineering')),
    lesson('layout-responsive', 'Layout, responsive design, and media', `Normal flow, flexbox, and grid solve different layout problems. Flexbox distributes items along one primary axis; grid coordinates rows and columns; positioning removes or offsets boxes relative to containing blocks. Responsive design adapts to available space, user settings, input method, and content rather than targeting a fixed catalog of devices.`, `Start mobile and content-first, then add breakpoints where layout actually fails. Use fluid sizing, minmax, wrapping, container queries where component space matters, responsive images with source choices, and media queries for preferences. Reserve media dimensions, crop with object-fit intentionally, and avoid loading huge images into small slots.`, `Viewport width is not the only capability: hover, pointer accuracy, motion preference, contrast, and reduced data can matter. Hiding essential content on small screens is not adaptation. Avoid horizontal scrolling for normal text, tiny touch targets, inaccessible hover-only controls, and layouts whose DOM order differs dangerously from visual order.`, `Design a library grid that becomes a compact list in narrow containers and supports large text without clipped actions.`, `Use a grid with repeat, auto-fill, and a minmax track sized from readable content. At a container threshold change each item to a horizontal layout while keeping the same DOM order. Let text wrap, give actions minimum target size, use aspect ratio and responsive source sizes for covers, and cap decorative media rather than content. Test 200 percent zoom, keyboard focus, long titles, missing images, touch, and reduced motion.`, authoredQuestions('responsive layout')),
    lesson('javascript-language', 'JavaScript values, functions, modules, and state', `JavaScript has primitives, objects, lexical scope, closures, prototypes, modules, exceptions, and garbage collection. Values are passed by value; object values are references to mutable objects. Equality, coercion, null, undefined, number precision, and property lookup cause subtle bugs when left implicit. Prefer clear conversion and model absent states deliberately.`, `Write small functions with explicit inputs and returned outputs. Keep pure transformations separate from DOM, network, storage, clock, and randomness. Use const for bindings that do not change, immutable update patterns for shared state, and modules with narrow public exports. Classes are one organization tool; composition and plain functions often express behavior more directly.`, `Mutation through aliases can change distant code. Floating-point arithmetic is unsuitable for exact money without a defined integer or decimal model. Catch errors only where you can add context, recover, or translate them; silent catch creates corrupted flow. Avoid eval and dynamic code construction. Understand closure lifetime before retaining large objects or event listeners.`, `Implement filtering, sorting, and grouping media records without mutating caller data and with explicit missing values.`, `Accept readonly records, normalize a search term once, filter by defined title and tags, copy before sorting, use a comparator that returns zero for equality, and group into a new Map. Decide whether missing year sorts last and preserve stable identity. Unit-test empty input, accents or locale policy, duplicate titles, null years, and caller arrays after execution. Keep UI effects outside these functions.`, authoredQuestions('JavaScript language')),
    lesson('dom-events', 'DOM, events, focus, and browser state', `The DOM is a live object model of the document. Query narrowly, create nodes with safe APIs, update text as text, and remove listeners and observers with component lifecycle. Events travel through capture, target, and bubble phases. Delegation handles related dynamic children through one ancestor while checking the actual target and intended element.`, `Choose the event matching semantics: submit for forms, input for live value changes, change for committed selection, click for activated buttons, and keydown only for interface-specific keyboard behavior. Do not duplicate native Enter and Space handling. Manage focus when opening and closing dialogs, after route changes, and when removing focused content.`, `Preventing default behavior or propagation globally breaks browser and assistive technology expectations. DOM injection occurs when untrusted content reaches HTML-parsing sinks. Long synchronous handlers block rendering and input. Persistent storage can be unavailable, cleared, or shared by scripts in the origin; validate stored data and never treat it as trusted authorization.`, `Build an accessible filter dialog with delegated option handling, Escape close, focus containment, and restoration.`, `Open from a real button, remember it, focus the dialog heading or first control, label the modal, keep Tab within its controls, close on Escape and explicit control, and restore focus if the opener remains. Listen on the dialog for option activation but resolve the closest expected button and validate its data. Update results without replacing the dialog DOM. Remove listeners on close and avoid storing sensitive state in local storage.`, authoredQuestions('DOM and events')),
    lesson('async-web-apis', 'Asynchronous JavaScript, fetch, workers, and streams', `The event loop runs tasks and drains microtasks before rendering opportunities. Promises represent eventual completion; async functions return promises and throw as rejection. Concurrency starts operations before awaiting them, while sequential awaits intentionally order dependencies. Parallel work still consumes network, memory, server, and browser limits and needs bounds.`, `Fetch resolves for HTTP error statuses, so check response status and expected content type. Use AbortController for cancellation, explicit deadlines, and request identity so stale results cannot overwrite current state. Parse streams when payload size demands it. Web Workers move CPU work off the main thread but communicate by cloned or transferred messages.`, `An unhandled rejection is not recovery. Retrying non-idempotent requests after timeout can duplicate effects. Promise.all fails fast but does not cancel siblings; allSettled preserves every result. Microtask loops can starve rendering. Avoid updating an unmounted component or displaying an older search response after a newer query.`, `Implement debounced search with cancellation, loading and error states, and protection against out-of-order responses.`, `Keep query text as controlled state, wait a short debounce, create a new AbortController, and abort the previous request. Encode the query through URL APIs, set a deadline, validate status and schema, and associate the response with its request generation. Show loading without erasing prior useful results, distinguish abort from failure, and render an empty state. Cleanup aborts on unmount. The server also limits query cost and does not rely on debounce as security.`, authoredQuestions('asynchronous web code')),
    lesson('typescript-tooling', 'TypeScript, modules, builds, and dependency discipline', `TypeScript checks a static model before JavaScript runs. It cannot validate unknown network, storage, or user data without runtime parsing. Use unknown at trust boundaries, narrow with schemas or guards, and model variants with discriminated unions. Avoid any because it disables evidence exactly where uncertainty exists.`, `Keep strict checking enabled. Prefer small domain types, readonly inputs, exhaustive switches, and explicit nullability. Separate browser, server, and shared contracts so environment-only APIs cannot leak across builds. Package scripts define formatting, checking, testing, development, and production build through locked dependencies.`, `Type assertions do not convert data and can lie. Generated clients and schemas drift unless one source and synchronization test owns them. Bundlers can hide oversized dependencies or unsafe environment substitution. Never put server secrets in variables exposed to client bundles. Treat package install scripts and build plugins as executable supply-chain code.`, `Define a runtime-validated API result and a build process that prevents server configuration from entering the client.`, `Describe the response with a runtime schema, parse fetched unknown data, and derive or mirror a static type under a drift guard. Return a Result-like success or structured failure rather than asserted casts. Expose only explicitly public build variables through a client prefix and scan output for known secret values. Lock dependencies, pin trusted build actions, produce source maps under access policy, and record artifact digest and source revision.`, authoredQuestions('TypeScript tooling')),
    lesson('accessibility-forms', 'Accessibility, forms, validation, and inclusive interaction', `Accessibility means people with varied vision, hearing, mobility, cognition, devices, and contexts can perceive and operate the product. Begin with semantic HTML, logical source order, keyboard access, programmatic names, visible focus, sufficient contrast, text alternatives, captions, scalable text, and reduced-motion support. Automated audits find only part of the problem.`, `Forms need persistent visible labels, instructions before input, suitable input types and autocomplete, grouped related controls, and errors connected with aria-describedby or native mechanisms. Validate on client for fast feedback and again on server for trust. Summaries help long forms; focus the summary after submission and keep entered values.`, `Placeholder text is not a label. Color alone cannot express error. Focus should not jump on every keystroke, and disabling submit without explanation hides recovery. Custom widgets require complete keyboard, focus, role, name, state, and announcement behavior. Test zoom, keyboard, screen reader, high contrast, and users when possible.`, `Design an accessible registration form with password guidance, server errors, and a successful transition.`, `Use labeled email and password controls with autocomplete, show password requirements as text, expose the toggle as a real button with state, and validate without announcing every keystroke. On submit, server-check uniqueness and policy, return field error codes without account enumeration, render an error summary linked to fields, and focus the summary. Preserve email, clear sensitive password, and on success move to a titled confirmation or authenticated route with focus and announcement handled.`, authoredQuestions('accessible forms')),
    lesson('react-components', 'React components, rendering, and effects', `A React component maps props and state to UI. Rendering must be pure: do not mutate external state, start network calls, or depend on random side effects inside it. Keys identify sibling continuity across renders and should come from stable entity identity, not array position when items reorder. Props communicate down; callbacks communicate intent up.`, `Use local state for transient UI, derived values computed during render, and context for stable cross-cutting dependencies with controlled scope. Effects synchronize with external systems such as network subscriptions, media, timers, or imperative widgets. Each effect declares dependencies and returns cleanup. If no external system exists, an effect is often unnecessary.`, `Duplicating derived state creates inconsistent sources of truth. Updating state unconditionally from an effect can loop. Missing dependencies capture stale values; unstable object dependencies rerun work. Memoization is a measured optimization, not correctness. Error boundaries handle rendering failures in a subtree but not every event or async failure.`, `Build a media queue component with reorder, selected item, persisted external subscription, and cleanup.`, `Keep queue records in one owner, derive selected record from selected id, and use stable item ids as keys. Reorder with an immutable array operation and keep selection by identity. A focused effect subscribes to the external player using a stable adapter and cleans up on adapter or component change. Persist only through a separate debounced external synchronization whose failure is visible. Test reorder, deletion of selected item, duplicate titles, subscription replacement, and unmount.`, authoredQuestions('React components')),
    lesson('state-routing', 'Application state, routing, caching, and architecture', `Classify state by owner and lifetime: server state, URL state, navigation-entry state, persistent user preference, form draft, and ephemeral component interaction. Putting every value in one global store erases useful boundaries. The URL should represent shareable or navigable choices; server caches represent remote data with freshness and invalidation; local component state represents nearby interaction.`, `Routes map URL structure to screens and loaders. Use stable identifiers, nested layouts, explicit not-found and error states, and navigation that preserves browser Back behavior. Validate route parameters. Client caches need query keys containing every input, stale policy, deduplication, cancellation, and targeted invalidation after mutation.`, `A cache is not authorization and may contain stale or cross-user data if identity is missing from its boundary. Optimistic updates need rollback or reconciliation. Persisted state needs schema version and safe fallback. Avoid redirect loops and history pollution from replace versus push mistakes. Code-split by route when measurement supports it while preserving loading accessibility.`, `Map state ownership for a searchable library with filters, detail routes, editable score, theme preference, and Back-preserved scroll.`, `Place query and durable filters in URL parameters when sharing matters, validate defaults, and keep transient popover state local. Fetch library and detail through keys including account and parameters. Mutation updates the server then invalidates relevant prefixes or safely patches normalized data. Theme is a versioned local preference; score draft stays in the form until saved. Store scroll and temporary filters in the navigation entry when Back should restore them. Use push for new detail navigation and replace after deleting the current route.`, authoredQuestions('application state')),
    lesson('server-api', 'Node servers, HTTP APIs, and background work', `A server accepts untrusted requests, authenticates identity, authorizes an operation, validates a bounded schema, performs a transaction or side effect, and returns a stable response contract. Separate transport routing, domain decisions, persistence, and external adapters so core behavior is testable. One process should not keep indispensable state only in memory if replicas or restarts matter.`, `Use middleware narrowly for cross-cutting request identity, limits, authentication, and logging; hidden ordering can create security gaps. Define API resources and actions from domain semantics, choose idempotency, pagination, filtering, status codes, and error types deliberately, and document version evolution. Background jobs carry stable identity, payload schema, retries, deadlines, and idempotent commit.`, `Unbounded bodies, regex, queries, concurrency, queues, and logs become denial of service. A successful queue publish after a failed database commit or the reverse creates inconsistency; use an outbox or reconciled workflow. Do not retry validation errors. Graceful shutdown stops admission and settles or returns work before deadline.`, `Design an endpoint that creates a media export asynchronously and allows polling, cancellation, and safe retry.`, `Authenticate and authorize export separately, validate format and scope, and accept an idempotency key. In one transaction create an export row and outbox event. Return 202 with stable job URL. A worker claims by lease, writes a versioned candidate, checks cancellation, validates output, publishes atomically, and marks terminal state conditionally. Polling returns status and bounded diagnostics; download uses a short capability. Retry reuses the job, cancellation is best effort and idempotent, shutdown releases leases, and retention deletes outputs by policy.`, authoredQuestions('server API design')),
    lesson('auth-data', 'Authentication, authorization, and relational data', `Web authentication establishes identity; authorization scopes every operation and query. Use secure transport, strong password hashing or passkeys, enumeration-resistant login, bounded attempts, session rotation, revocation, and protected recovery. Browser sessions fit opaque Secure, HttpOnly cookies with deliberate SameSite more safely than long-lived tokens in script-readable storage.`, `Model relational data with explicit grain, primary and unique keys, foreign keys, checks, and transactions. Parameterize queries and map only allowed fields. Scope reads and writes to the caller tenant in the query itself. Migrations use additive compatibility, backfill, validation, constraint, and later cleanup so old and new application versions can coexist.`, `An ORM does not guarantee efficient or authorized queries. Inspect generated SQL, avoid N-plus-one access, and constrain result size. CSRF still matters with ambient cookies; XSS can perform actions despite HttpOnly. Current-user endpoints and caches must vary by identity. Account deletion needs authorization, recent authentication, dependency handling, retention, and backup policy.`, `Implement teams, memberships, private media rows, invitations, and sessions with cross-tenant protection.`, `Use organization, user, membership, media, invitation, and session tables with unique membership and invitation constraints. Every media query joins or filters through active membership and checks action role. Invitation tokens store only a digest, expire, bind organization and role, and become one membership transactionally. Login rotates the session id and CSRF secret; role removal invalidates elevated sessions within a short bound. Tests guess ids across organizations, replay invitations, race duplicate acceptance, use revoked sessions, and verify deletion and export rules.`, authoredQuestions('web identity and data')),
    lesson('testing-quality', 'Full-stack testing and quality strategy', `Tests provide evidence for risks at different scopes. Pure unit tests cover transformations and domain rules; component tests cover rendered behavior; integration tests exercise database, protocol, and browser boundaries; contract tests protect API agreement; end-to-end tests verify a few critical user journeys. Static checks, accessibility audits, security tests, and load tests cover other properties.`, `Control clock, randomness, identity, and network. Use readable fixtures and factories with explicit differences. Test loading, empty, failure, unauthorized, stale, concurrent, duplicate, retry, cancellation, and recovery states. Browser tests should select by accessible role and name where possible, reflecting user semantics rather than CSS structure.`, `A flaky test is missing evidence. Retrying until green hides it. Giant snapshots approve changes mechanically, mocks can diverge from real dependencies, and only happy-path end-to-end tests are slow and shallow. Test the real query and migration where data integrity matters. Keep production observability as the final release assertion.`, `Create a test portfolio for invitations and membership role changes across browser, API, and database.`, `Unit-test role-transition rules and token expiry. Database tests use the real schema for unique active invitation and membership constraints, transactional acceptance, and tenant-scoped queries. API tests cover enumeration-resistant errors, authorization matrix, idempotent replay, and revoked sessions. Browser tests cover labeled form, keyboard errors, acceptance, and visible role changes. A concurrency test races two acceptances. Security tests guess ids and alter role fields. A migration test upgrades prior populated data. Production synthetic checks invite only a dedicated synthetic account and clean it safely.`, authoredQuestions('full-stack testing')),
    lesson('performance-delivery', 'Web performance, observability, and delivery', `User performance spans DNS, transport, server response, asset transfer, parsing, rendering, main-thread work, and interaction. Measure distributions on representative devices and networks. Core user-centric metrics and custom journey timings identify experience, while server traces and resource metrics locate causes. Set budgets for JavaScript, CSS, images, requests, and interaction work.`, `Serve compressed cacheable immutable assets by digest, responsive images, minimal critical CSS, and deferred or split JavaScript. Preload only truly critical resources. Avoid long main-thread tasks, layout thrashing, oversized hydration, and unnecessary client rendering. Server pagination, indexes, caching, and bounded serialization matter as much as frontend bundles.`, `Lab scores are controlled clues, not field truth. Caches can serve private or stale data, code splitting can create request waterfalls, and aggressive lazy loading can harm primary content. Observe errors, latency, availability, release identity, and business success after deploying one immutable artifact. Roll out gradually with predeclared abort and recovery.`, `Set a delivery and performance plan for the capstone under a slow mobile profile and production canary.`, `Budget initial compressed script, stylesheet, cover bytes, request count, largest content render, and interaction delay from a tested low-end profile. Render meaningful HTML early, size media, load the primary cover responsively, split secondary routes, and cache digest assets for a year while keeping HTML revalidated. Trace API and database latency. CI builds once, records bundle analysis and artifact digest, deploys a staging smoke path, then canaries production. Compare field user metrics, errors, accessibility synthetic, and server saturation; pause or roll back on declared thresholds.`, authoredQuestions('web performance and delivery')),
    lesson('capstone-fullstack', 'Capstone: an accessible production web application', `Build a multi-user media club from an empty directory. Users create organizations, invite members, track titles, upload covers, comment, filter, export data, and receive live job status. The application must remain useful with slow scripts, keyboard only, zoom, reduced motion, and constrained network. Document users, journeys, data, trust boundaries, architecture, and acceptance criteria.`, `Implement semantic responsive HTML, tokenized CSS, TypeScript runtime schemas, React components with deliberate state ownership, accessible forms and dialogs, a Node API, relational constraints and migrations, secure cookie sessions, tenant authorization, CSRF and XSS controls, quarantined uploads, idempotent exports, and structured telemetry. Build once through CI and deploy by digest with tested configuration.`, `Prove failure behavior: duplicate invitation, raced role change, stale cache, aborted search, unavailable database, worker crash after output, oversized archive, revoked session, slow device, missing image, failed migration, and bad canary. Restore a backup and validate organization and membership invariants. Measure user performance and accessibility rather than treating a framework build as success.`, `Write the traceability matrix from each user promise to code, test, telemetry, owner, and recovery before implementation.`, `Map invitation privacy to tenant-scoped queries, unique constraints, negative tests, audit events, and revocation; accessible navigation to semantic landmarks, route focus, keyboard tests, and user review; safe uploads to capability scope, quarantine, parser limits, and cleanup; export reliability to idempotency, outbox, worker leases, atomic publication, and restore; performance to budgets, field metrics, traces, and rollback. The capstone is complete when another person can set it up, use every journey, inspect its contracts, inject failures, and recover without outside instruction.`, authoredQuestions('full-stack mastery'))
  ]
}
