import type { ProgCourseDef } from './types'

// Go for Python developers — the flagship course. Written for an engineer who
// is fluent in Python and wants working Go, so every lesson leans on the
// Python mental model and shows where it breaks.

export const GO_COURSE: ProgCourseDef = {
  key: 'go-from-python',
  title: 'Go for Python developers',
  description:
    'Working Go for someone fluent in Python: the type system, the error culture, the concurrency model, and the idioms — taught by contrast.',
  lessons: [
    {
      key: 'why-go',
      title: 'Why Go, and the toolchain',
      body: `# Why Go

Go trades Python's flexibility for three things: a single static binary, real concurrency, and a type system fast enough that you never wait for it. There is no interpreter to ship, no virtualenv, no \`requirements.txt\` drift — \`go build\` produces one file you can \`scp\` to a server and run.

The language is deliberately small. Where Python accumulated four ways to format strings and three ways to make a class, Go usually has one way. You will sometimes miss the expressiveness; you will never spend a day deciding between metaclass approaches.

## The toolchain replaces half your Python stack

- \`go run .\` — run the current package (like \`python main.py\`, but it compiles first)
- \`go build .\` — compile this package; the binary lands in the current directory
- \`go build ./...\` — compile *everything* as a check. Building several packages, or one that isn't \`main\`, throws the result away — it tells you it compiles, it does not give you a binary
- \`go test ./...\` — the test runner is built in; no pytest to install
- \`go fmt ./...\` — THE formatter. There is exactly one Go style and nobody argues about it
- \`go vet ./...\` — built-in static analysis
- \`go mod init\` / \`go mod tidy\` — dependency management, replacing pip + venv + setuptools

One binary, \`go\`, does all of it. Compare pip, venv, black, flake8, mypy, pytest, build — seven tools, each with a config file.

## Your first program

\`\`\`go
package main

import "fmt"

func main() {
    fmt.Println("hello from a compiled binary")
}
\`\`\`

Three things Python does not have: every file declares a \`package\`; the entry point is the \`main\` function of the \`main\` package; and imports are per-file, checked by the compiler — an unused import is a compile ERROR, not a linter nag. So is an unused local variable. Go refuses to compile code that has started to rot.

## Modules in one paragraph

A module is a directory tree with a \`go.mod\` file naming it (usually a repo path like \`github.com/you/tool\`). \`go get example.com/pkg\` adds a dependency at a pinned version into \`go.mod\` and its checksum into \`go.sum\`; \`go mod tidy\` removes what you stopped importing. There is no global site-packages and no activation step — versions live with the project, and two projects never fight.

## What to unlearn

The biggest shift is cultural: Go code is boring on purpose. You will write more lines than in Python, most of them explicit error handling, and the payoff is that any Go programmer can read any Go codebase. Cleverness is a code smell here.`,
      questions: [
        {
          prompt: 'What does an unused import do in Go?',
          options: [
            'Nothing — the linter may warn about it',
            'It fails the compile',
            'It slows startup while the module loads anyway',
            'It is stripped automatically by go build'
          ],
          correct: 1,
          explain:
            'Unused imports (and unused local variables) are compile errors. gofmt-aware editors usually add/remove imports for you via goimports.'
        },
        {
          prompt: 'Which single command replaces the pytest dependency in a Go project?',
          options: ['go check', 'go run -test', 'go test', 'gotest — a separate install'],
          correct: 2,
          explain: 'The test runner ships with the toolchain: go test ./... runs the whole module.'
        },
        {
          prompt: 'Where do a Go project\'s pinned dependency versions live?',
          options: [
            'In a virtualenv alongside the code',
            'In $GOPATH/pkg, one directory shared by every project on the machine — the pre-modules answer',
            'In go.mod (with checksums in go.sum) inside the module',
            'In a lockfile generated by the IDE'
          ],
          correct: 2,
          explain:
            'go.mod names the module and pins requirements; go.sum holds checksums. Nothing global, nothing to activate.'
        },
        {
          prompt: 'What is the entry point of a Go executable?',
          options: [
            'Any function marked with //go:main',
            'func main() in package main',
            'The first function in the first file, like a script',
            'An __init__-style function per package'
          ],
          correct: 1,
          explain: 'Executables are package main with a func main(). Libraries are every other package.'
        }
      ]
    },
    {
      key: 'variables-types',
      title: 'Variables, types, zero values',
      body: `# Static types without the ceremony

Go is statically typed but mostly inferred. The workhorse is \`:=\`, which declares AND assigns:

\`\`\`go
name := "rei"          // string
count := 42            // int
ratio := 0.5           // float64
ok := true             // bool
var total int          // declare without a value → zero value
\`\`\`

\`:=\` only works inside functions and only for NEW variables (at least one on the left must be new). At package level you use \`var\` or \`const\`.

## Zero values replace None-checking

Python initializes nothing; Go initializes everything. A declared-but-unassigned variable holds its type's zero value: \`0\` for numbers, \`""\` for strings, \`false\` for bools, \`nil\` for pointers, slices, maps, channels and interfaces. This is a design pillar: a zero value should be USABLE. \`var b strings.Builder\` works immediately; \`var mu sync.Mutex\` is a valid unlocked mutex. Where Python code starts with \`x = None\` and checks \`if x is not None\` later, Go code just uses the zero value.

## No implicit conversions, at all

Python happily adds an int to a float. Go does not — not even between \`int\` and \`int64\`:

\`\`\`go
var n int = 5
var big int64 = 10
sum := int64(n) + big   // explicit conversion required
\`\`\`

This feels pedantic for a week and then saves you from every "it worked until the number got big" bug class. Conversions are always spelled \`T(v)\`.

## Constants are a different animal

\`const\` in Go is compile-time only, and untyped constants are arbitrary-precision until used:

\`\`\`go
const KB = 1 << 10          // untyped — adapts to context
const Pi float64 = 3.14159  // typed

type Level int
const (
    Debug Level = iota      // 0
    Info                    // 1
    Warn                    // 2
)
\`\`\`

\`iota\` is Go's enum idiom — there is no enum keyword. Each line in the const block increments it.

## Naming is semantics

Case is not style in Go, it is visibility: \`Exported\` identifiers (capital first letter) are public outside the package, \`unexported\` ones are private to it. There is no \`_private\` convention because the compiler enforces the real thing. Short names are idiomatic in small scopes (\`i\`, \`err\`, \`buf\`); descriptive names belong to exported API.`,
      questions: [
        {
          prompt: 'What is the value of s after: var s []int',
          options: [
            'An empty slice, same as []int{}',
            'nil — but len(s) is 0 and append(s, 1) works fine',
            'A compile error: slices must be initialized',
            'Undefined until first use'
          ],
          correct: 1,
          explain:
            'The zero value of a slice is nil, and nil slices are designed to be usable: len/cap are 0 and append allocates.'
        },
        {
          prompt: 'Why does count := int32(5); total := count + int64(7) fail to compile?',
          options: [
            'int32 cannot hold 5 on 64-bit platforms',
            ':= cannot mix integer widths on one line',
            'Go never converts numeric types implicitly — you must convert one side explicitly',
            'It compiles; the result is int64 because Go widens the narrower operand automatically'
          ],
          correct: 2,
          explain:
            'There are no implicit numeric conversions, even between integer widths. Write int64(count) + 7.'
        },
        {
          prompt: 'What makes an identifier public (importable from another package)?',
          options: [
            'An export keyword before the declaration',
            'Being listed in the package manifest',
            'A capitalized first letter',
            'Being declared at the top of the file'
          ],
          correct: 2,
          explain: 'Visibility is spelled by case: Foo is exported, foo is package-private.'
        },
        {
          prompt: 'What does iota provide?',
          options: [
            'A random seed for the package',
            'An auto-incrementing counter inside a const block — Go\'s enum idiom',
            'The index variable of range loops, which is why it resets each iteration',
            'A pointer to the current goroutine'
          ],
          correct: 1,
          explain: 'iota starts at 0 in each const block and increments per line; typed consts built on it stand in for enums.'
        }
      ]
    },
    {
      key: 'control-flow',
      title: 'Control flow: for, if, switch, defer',
      body: `# One loop to rule them all

Go has exactly one loop keyword. \`for\` covers every Python loop shape:

\`\`\`go
for i := 0; i < 10; i++ { }        // C-style
for count > 0 { }                  // while loop
for { }                            // while True
for i, v := range items { }        // enumerate(items)
for k, v := range m { }            // dict.items()
\`\`\`

\`range\` over a slice gives index and value; over a map, key and value (in RANDOM order — Go deliberately randomizes map iteration so you never depend on it); over a string, byte-offset and rune. Don't need the index? \`for _, v := range items\`. The blank identifier \`_\` is how you discard any value, and unlike Python's \`_\` convention the compiler enforces that you either use a variable or blank it.

## if with an init statement

The signature Go shape — declare, test, and scope in one line:

\`\`\`go
if err := doThing(); err != nil {
    return err
}
// err does not exist here
\`\`\`

The variable lives only inside the if/else. You will write this fifty times a day.

## switch: better than you remember

Go's switch does not fall through by default (no \`break\` spam), cases can be arbitrary expressions, and a bare switch replaces if/else chains:

\`\`\`go
switch {
case score >= 90:
    grade = "A"
case score >= 80:
    grade = "B"
default:
    grade = "C"
}
\`\`\`

There is also \`switch v := x.(type)\` for switching on an interface's concrete type — the closest thing to Python's \`match\` on types.

## defer: with-blocks, inverted

\`defer\` schedules a call to run when the surrounding FUNCTION returns, however it returns — the role of Python's \`with\` and \`finally\`:

\`\`\`go
f, err := os.Open(path)
if err != nil {
    return err
}
defer f.Close()
// use f for the rest of the function; Close runs on every exit path
\`\`\`

Deferred calls run last-in-first-out, and their arguments are evaluated at the \`defer\` line, not at run time. The idiom is to put the \`defer\` immediately after acquiring the resource, so acquisition and release read as a pair.

One gotcha versus \`with\`: defer is function-scoped, not block-scoped. Opening files in a loop and deferring each close means nothing closes until the whole function ends — hoist the loop body into its own function when that matters.`,
      questions: [
        {
          prompt: 'How do you write a while loop in Go?',
          options: [
            'while cond { }',
            'for cond { }',
            'loop { if !cond { break } }',
            'until !cond { }'
          ],
          correct: 1,
          explain: 'for is the only loop keyword; with just a condition it is a while loop.'
        },
        {
          prompt: 'Why does iterating a map print keys in a different order on each run?',
          options: [
            'Maps rehash on every read',
            'The runtime randomizes map iteration order on purpose so code cannot depend on it',
            'It is a known bug that was kept for backward compatibility with pre-1.0 Go programs',
            'Only maps with pointer keys do this'
          ],
          correct: 1,
          explain:
            'Iteration order is deliberately randomized. If you need order, collect the keys into a slice and sort it.'
        },
        {
          prompt: 'When do the arguments of a deferred call get evaluated?',
          options: [
            'When the deferred call actually runs, at function exit',
            'Lazily, on first use inside the deferred function',
            'At the defer statement itself; only the call is postponed',
            'It depends on whether the argument is a pointer'
          ],
          correct: 2,
          explain:
            'defer fmt.Println(i) captures i\'s value at the defer line. Use a closure — defer func(){ ... }() — to read final values.'
        },
        {
          prompt: 'What replaces Python\'s try/finally for releasing a resource in Go?',
          options: [
            'A finally block on if statements',
            'defer, scheduled right after acquiring the resource',
            'Automatic garbage-collector finalizers, which Go schedules to run deterministically the moment a value goes out of scope',
            'The with keyword'
          ],
          correct: 1,
          explain:
            'defer f.Close() right after a successful Open runs on every return path — panic included.'
        }
      ]
    },
    {
      key: 'functions',
      title: 'Functions, multiple returns, closures',
      body: `# Functions are values, signatures are contracts

\`\`\`go
func split(path string) (dir, file string) { ... }   // two results, named
func sum(nums ...int) int { ... }                    // variadic, like *args
\`\`\`

Types come after names (\`path string\`, not \`string path\`), and results are part of the signature. Multiple return values are the language's core convention — where Python returns tuples occasionally, Go returns \`(value, error)\` constantly:

\`\`\`go
data, err := os.ReadFile(path)
if err != nil {
    return nil, fmt.Errorf("reading config: %w", err)
}
\`\`\`

You must do something with every result: use it or assign it to \`_\`. There is silently ignoring a return value in Python; in Go it is a visible choice.

## Named results and naked returns

Result parameters can be named — \`(dir, file string)\` above — which documents them and pre-declares them as zero-valued variables. A bare \`return\` then returns their current values. Use named results for documentation; use naked returns rarely (they get hard to follow in long functions).

## No default arguments, no keyword arguments, no overloading

This hurts coming from Python. The Go answers are:

- Small fixed variants: two functions (\`NewServer\`, \`NewServerTLS\`)
- Many optional knobs: pass a config struct — \`NewServer(Config{Port: 8080})\` reads like kwargs
- Extensible libraries: functional options (\`NewServer(WithPort(8080), WithTLS(cert))\`)

The struct approach covers 90% of cases and stays boring.

## Closures work like you expect (now)

Functions are first-class and close over variables by reference:

\`\`\`go
func counter() func() int {
    n := 0
    return func() int { n++; return n }
}
\`\`\`

The classic loop-variable capture bug — every closure seeing the final value — was FIXED in Go 1.22: loop variables are now fresh per iteration, matching what everyone expected all along. In older code you will still see the \`i := i\` shadowing workaround; recognize it as history.

## Variadics and slices

\`sum(1, 2, 3)\` and \`sum(nums...)\` mirror \`f(*args)\` — the \`...\` suffix spreads a slice into a variadic call. Note there is no \`**kwargs\` equivalent at all; that pattern becomes a struct.`,
      questions: [
        {
          prompt: 'What is the idiomatic Go replacement for a Python function with many optional keyword arguments?',
          options: [
            'Overloading the function name with different signatures',
            'A map[string]any of options',
            'A config struct parameter (or functional options for libraries)',
            'Global variables set before the call'
          ],
          correct: 2,
          explain:
            'NewServer(Config{Port: 8080}) reads like kwargs, is typed, and zero values cover the defaults.'
        },
        {
          prompt: 'What does the ... do in each of: func f(xs ...int) and f(nums...)?',
          options: [
            'Both mark unbounded recursion depth, letting a variadic function call itself with one extra argument every frame',
            'Declares a variadic parameter; spreads a slice into that parameter',
            'Declares a slice; copies the slice',
            'They are only valid in generic functions'
          ],
          correct: 1,
          explain: 'xs ...int is *args-style collection; nums... is the *-spread at the call site.'
        },
        {
          prompt: 'Since Go 1.22, what does each closure created in a for loop capture?',
          options: [
            'A fresh per-iteration copy of the loop variable',
            'The final value of the loop variable, as before',
            'A pointer to the slice being ranged',
            'Nothing — closures in loops are now a compile error'
          ],
          correct: 0,
          explain:
            'Loop variables are per-iteration since 1.22, so the old i := i shadowing trick is no longer needed.'
        }
      ]
    },
    {
      key: 'errors',
      title: 'Errors: values, not exceptions',
      body: `# The biggest cultural shift

Python signals failure by raising; the caller may or may not catch. Go signals failure by RETURNING an error; the caller must visibly decide what to do:

\`\`\`go
f, err := os.Open(path)
if err != nil {
    return fmt.Errorf("opening config: %w", err)
}
\`\`\`

\`error\` is just an interface — \`interface { Error() string }\` — and \`nil\` means success. The \`if err != nil\` block is not noise to be eliminated; it is the control flow, written where it happens. There is no invisible stack unwinding, so reading a Go function tells you every way it can fail.

## Wrapping: %w builds a chain

\`fmt.Errorf("opening config: %w", err)\` wraps the original error with context. Each layer adds what IT knows — the filename here, the operation there — producing messages like \`loading profile: opening config: open /etc/app.conf: permission denied\`. Wrap with context at each level; never wrap with nothing to add.

## Inspecting: errors.Is and errors.As

String-matching error text is a firing offense. The chain is inspected structurally:

\`\`\`go
if errors.Is(err, os.ErrNotExist) {      // sentinel anywhere in the chain?
    return defaults, nil
}
var pathErr *os.PathError
if errors.As(err, &pathErr) {            // typed error anywhere in the chain?
    log.Println("failed path:", pathErr.Path)
}
\`\`\`

\`errors.Is\` matches sentinel VALUES (like \`ErrNotFound = errors.New("not found")\`); \`errors.As\` extracts a concrete TYPE carrying data. Both walk the whole \`%w\` chain — the equivalent of \`except FileNotFoundError\` working through any number of re-raises.

## panic is not an exception mechanism

\`panic\` exists, and \`recover\` can stop one, but the culture is strict: panic means a BUG (index out of range, nil dereference, impossible state), not a foreseeable failure like a missing file or a bad request. Libraries that panic on bad input are broken. The rare legitimate recover lives at a boundary — an HTTP server keeping one crashed handler from killing the process. If you find yourself designing an API around panic/recover, you are writing Python in Go.

## The discipline that makes it work

Handle an error ONCE. Either handle it (retry, default, log-and-degrade) or return it wrapped — never both log AND return, which double-reports every failure up the stack. And never write \`_ = err\`. The one habit to build immediately: write the failure path first, then the happy path.`,
      questions: [
        {
          prompt: 'What does the %w verb in fmt.Errorf do that %v does not?',
          options: [
            'Formats the error with its stack trace',
            'Wraps the error so errors.Is/errors.As can still find it through the new one',
            'Writes the error to stderr as a side effect, in addition to formatting the message',
            'Marks the error as fatal'
          ],
          correct: 1,
          explain: '%w records the wrapped error in the chain; %v only interpolates its text and breaks Is/As.'
        },
        {
          prompt: 'You want to know whether err (possibly wrapped many times) is ultimately a *json.SyntaxError so you can read its Offset. Which tool?',
          options: [
            'errors.Is(err, &json.SyntaxError{})',
            'strings.Contains(err.Error(), "syntax")',
            'var se *json.SyntaxError; errors.As(err, &se)',
            'err.(*json.SyntaxError) directly'
          ],
          correct: 2,
          explain:
            'errors.As walks the chain looking for that concrete type and fills your pointer. A direct type assertion misses wrapped errors.'
        },
        {
          prompt: 'When is panic appropriate in idiomatic Go?',
          options: [
            'For any error the caller is likely to ignore',
            'For programmer bugs / impossible states — not for foreseeable failures',
            'Whenever an error crosses a package boundary, since panic unwinds cleanly through call stacks in a way returned errors cannot',
            'Never; panic is deprecated'
          ],
          correct: 1,
          explain:
            'Foreseeable failures return errors. panic is for bugs; recover belongs only at process-protecting boundaries.'
        },
        {
          prompt: 'What is wrong with logging an error AND returning it?',
          options: [
            'Nothing — it is the recommended belt-and-braces style for long-running production services',
            'The compiler rejects it',
            'Every layer doing both means each failure gets reported multiple times — handle once',
            'log calls are not allowed outside main'
          ],
          correct: 2,
          explain: 'Handle an error exactly once: either deal with it or pass it up (wrapped). Both = duplicate noise.'
        }
      ]
    },
    {
      key: 'slices-arrays',
      title: 'Slices: the machinery under the list',
      body: `# A slice is a view, not a container

Python's list owns its storage. A Go slice is a small header — pointer, length, capacity — VIEWING a chunk of a backing array. Everything surprising about slices follows from that one fact.

\`\`\`go
nums := []int{1, 2, 3}       // slice literal
part := nums[0:2]            // [1 2] — SHARES nums' backing array
part[0] = 99                 // nums is now [99 2 3]
\`\`\`

Slicing is O(1) and copies nothing — which is fast, and also means writes through one slice are visible through every slice sharing that array. Python's \`nums[0:2]\` copies; Go's does not. (Arrays — \`[3]int\` — are fixed-size values that copy on assignment; you will use them rarely and mostly by accident.)

## len, cap, and how append really works

\`len\` is what you can see; \`cap\` is how far the backing array extends past your window.

\`\`\`go
s := make([]int, 0, 10)   // len 0, cap 10
s = append(s, 1)          // fits in capacity: same array
\`\`\`

\`append\` writes at the end if capacity allows; if not, it allocates a NEW array (roughly doubling), copies, and returns a slice over the new array. Two consequences:

- ALWAYS write \`s = append(s, x)\` — the returned header may point somewhere new.
- Whether two slices still share storage depends on whether an append has reallocated — which is why you never let two slices append into the same backing array. The aliasing bug: \`b := a[:2]; b = append(b, 99)\` can OVERWRITE \`a[2]\` if capacity allowed.

When you need an independent copy, make one explicitly: \`c := make([]int, len(s)); copy(c, s)\` — or \`slices.Clone(s)\`.

## Growing a slice from zero

\`var s []int\` (nil) works with append immediately; there is no need for \`make\` unless you want to pre-size. Pre-sizing with \`make([]T, 0, n)\` when you know n avoids the reallocation churn — the equivalent of knowing better than \`list.append\` in a hot loop.

## List comprehensions do not exist

The Python one-liner becomes a loop, every time:

\`\`\`go
evens := make([]int, 0, len(nums))
for _, n := range nums {
    if n%2 == 0 {
        evens = append(evens, n)
    }
}
\`\`\`

The \`slices\` package (1.21+) covers the rest of the list toolkit: \`slices.Contains\`, \`slices.Sort\`, \`slices.Index\`, \`slices.Reverse\`. Filter/map one-liners stay loops by design — Go chose readable-and-boring over expressive here, and after a month you stop noticing.`,
      questions: [
        {
          prompt: 'After a := []int{1,2,3}; b := a[:1]; b[0] = 9 — what is a[0]?',
          options: [
            '1 — slicing copies in Go like in Python',
            '9 — b views the same backing array as a',
            'Undefined behavior',
            'A compile error: b is read-only'
          ],
          correct: 1,
          explain: 'Slicing creates a view, not a copy. Writes through b are visible in a.'
        },
        {
          prompt: 'Why must append\'s result be assigned back (s = append(s, x))?',
          options: [
            'Style only — append mutates s in place either way, so the assignment back is redundant',
            'append may allocate a new backing array, and only the returned header points at it',
            'Because slices are immutable',
            'To increment the reference count'
          ],
          correct: 1,
          explain:
            'When capacity is exceeded, append reallocates and copies; the old header still points at the old array.'
        },
        {
          prompt: 'What is cap(s) for s := make([]int, 3, 8)?',
          options: ['3', '8', '11', 'Unknowable until first append'],
          correct: 1,
          explain: 'make(type, len, cap): len 3 (three usable zero-valued elements), cap 8 (room before reallocation).'
        },
        {
          prompt: 'How do you get a genuinely independent copy of slice s?',
          options: [
            'c := s — a second reference to the exact same backing array, not a copy',
            'c := s[:] — still a full slice of the same backing array',
            'c := slices.Clone(s), or make+copy — allocates fresh backing storage',
            'c := *s — does not compile; slices are not pointers to dereference'
          ],
          correct: 2,
          explain: 'Assignment and full slicing both share the array. Clone/copy allocate fresh storage.'
        }
      ]
    },
    {
      key: 'maps-strings',
      title: 'Maps, strings, runes',
      body: `# Maps: dicts with sharper edges

\`\`\`go
ages := map[string]int{"rei": 14, "asuka": 14}
ages["shinji"] = 14
delete(ages, "asuka")
\`\`\`

Two behaviors differ from \`dict\` in ways that matter:

Reading a missing key does not raise — it returns the value type's ZERO value. \`ages["nobody"]\` is \`0\`. When zero is a legitimate value you need the two-result form, the "comma ok" idiom:

\`\`\`go
age, ok := ages["nobody"]   // 0, false
if !ok { ... }
\`\`\`

And a nil map (\`var m map[string]int\`) is readable but WRITING to it panics — the one zero value that is not fully usable. Always \`make(map[string]int)\` (or use a literal) before writing.

Maps have no order (iteration is randomized, as you saw), no \`.keys()\` method — collect keys with a loop or \`maps.Keys\` (1.23+), sort explicitly. There is also no \`defaultdict\`; the zero-value read covers the common counter case for free:

\`\`\`go
counts := map[string]int{}
for _, w := range words {
    counts[w]++          // missing key reads as 0, then increments
}
\`\`\`

## Strings are bytes; runes are code points

A Go string is an immutable byte slice, usually UTF-8. Indexing gives you BYTES:

\`\`\`go
s := "日本語"
len(s)        // 9 — bytes, not characters
s[0]          // 230 — a byte
\`\`\`

Iterating with \`range\` decodes UTF-8 and yields runes (int32 code points) with their byte offsets:

\`\`\`go
for i, r := range "日本語" {
    fmt.Printf("%d: %c\\n", i, r)   // 0: 日  3: 本  6: 語
}
\`\`\`

Rules of thumb: \`len\` and indexing are byte operations; \`range\` and \`[]rune(s)\` are character operations; \`utf8.RuneCountInString\` is the character count. Python 3 hid this distinction by decoding at the boundary; Go keeps strings as bytes and makes you say when you mean characters — for a media app full of Japanese titles, this distinction is load-bearing.

## The strings toolbox

\`strings.Split\`, \`strings.Join\`, \`strings.TrimSpace\`, \`strings.HasPrefix\`, \`strings.ReplaceAll\`, \`strings.Contains\` cover the str methods you use daily. Building a string in a loop uses \`strings.Builder\` (append with \`b.WriteString\`, finish with \`b.String()\`) — the \`"".join(parts)\` of Go. \`fmt.Sprintf\` is your f-string, with \`%s %d %v %q\` instead of braces; \`%v\` formats anything, \`%+v\` adds struct field names, \`%q\` quotes.`,
      questions: [
        {
          prompt: 'What does age := ages["missing"] give you when the key is absent?',
          options: [
            'A panic, like KeyError',
            'nil',
            'The zero value of the value type — plus ok=false only in the two-result form',
            'A compile error, unless you explicitly request the two-result comma-ok form with v, ok := ages[key]'
          ],
          correct: 2,
          explain:
            'Missing reads yield the zero value silently; use v, ok := m[k] when zero is also a legal stored value.'
        },
        {
          prompt: 'What happens on write to a nil map (var m map[string]int; m["a"] = 1)?',
          options: [
            'The map auto-allocates like append does for slices',
            'A runtime panic — make it first',
            'The write is silently discarded',
            'Compile error'
          ],
          correct: 1,
          explain: 'nil maps are read-only-as-empty; writing panics. Slices auto-grow via append, maps never do.'
        },
        {
          prompt: 'For s := "日本語", what are len(s) and utf8.RuneCountInString(s)?',
          options: ['3 and 3', '9 and 3', '9 and 9', '3 and 9'],
          correct: 1,
          explain: 'len counts bytes (3 chars × 3 bytes in UTF-8); rune count counts code points.'
        },
        {
          prompt: 'What is the idiomatic way to build a large string from many pieces in a loop?',
          options: [
            's += piece each iteration',
            'strings.Builder with WriteString, then String()',
            'fmt.Sprintf accumulating the result into a new variable each pass, which the compiler optimizes into one allocation',
            'A []rune you append to'
          ],
          correct: 1,
          explain:
            'Builder amortizes allocation like "".join; += copies the whole string every iteration.'
        }
      ]
    },
    {
      key: 'structs-methods',
      title: 'Structs & methods: classes, decomposed',
      body: `# Data and behavior, separately declared

A Python class bundles fields, constructor, and methods. Go splits them: a struct declares data, methods attach to it separately, and constructors are plain functions by convention:

\`\`\`go
type Track struct {
    Title    string
    Artist   string
    Plays    int
    liked    bool      // unexported: private to the package
}

func NewTrack(title, artist string) *Track {
    return &Track{Title: title, Artist: artist}
}

func (t *Track) Like()            { t.liked = true }
func (t Track) String() string    { return t.Artist + " – " + t.Title }
\`\`\`

\`(t *Track)\` is the receiver — the explicit \`self\`. \`NewTrack\` is nothing special to the language; it is just a function named by convention (\`NewX\`), because struct literals \`Track{Title: "Tank!"}\` already construct values and every field you omit is zero-valued. Design structs so the zero value is useful and half your constructors disappear.

## Value receiver vs pointer receiver — the decision Python never asks

Everything in Go is passed by copy. A method with a VALUE receiver \`(t Track)\` operates on a copy — mutations vanish. A POINTER receiver \`(t *Track)\` operates on the original:

\`\`\`go
func (t Track) BumpBroken()  { t.Plays++ }   // increments a copy, useless
func (t *Track) Bump()       { t.Plays++ }   // increments the real one
\`\`\`

Rules: if any method needs to mutate, use pointer receivers; if the struct is big, use pointer receivers to avoid copying; and be CONSISTENT across a type's method set — mixing both is a lint warning and a design smell. Go auto-takes addresses for you (\`track.Bump()\` works on an addressable \`Track\` variable), so calls look identical either way.

## Embedding is composition with sugar, not inheritance

There is no inheritance. Embedding a type promotes its fields and methods:

\`\`\`go
type Logger struct{ prefix string }
func (l Logger) Log(msg string) { fmt.Println(l.prefix, msg) }

type Server struct {
    Logger            // embedded: Server gets .Log(...)
    addr string
}
\`\`\`

\`server.Log("up")\` forwards to the embedded Logger. But this is delegation, not subtyping: a \`Server\` is not assignable where a \`Logger\` is expected, there is no \`super\`, and no overriding with dynamic dispatch — if Server defines its own \`Log\`, the outer one simply shadows the inner, and nothing that calls \`Logger.Log\` internally will see it. Where Python reaches for a base class, Go reaches for embedding a concrete type or — better — accepting an interface (next-lesson material).

Struct tags (metadata strings like json field names on struct fields) round out the picture — you will meet them the first time you touch \`encoding/json\`, where \`json:"title"\` on a field controls its serialized name.`,
      questions: [
        {
          prompt: 'A method with receiver (c Counter) does c.n++. What happens at the call site?',
          options: [
            'The caller\'s Counter increments',
            'A copy increments and is thrown away — the caller sees nothing',
            'Compile error: value receivers are read-only',
            'It increments only if Counter is small enough to be inlined'
          ],
          correct: 1,
          explain: 'Value receivers get a copy. Mutating methods need a *Counter receiver.'
        },
        {
          prompt: 'What does embedding (type Server struct { Logger }) give you?',
          options: [
            'Subtyping: a Server can be passed where a Logger is required',
            'Promotion: Logger\'s methods/fields are callable on Server, by delegation',
            'Dynamic dispatch: Server\'s overrides are seen by Logger\'s own methods',
            'A compile-time mixin that copies Logger\'s code into Server'
          ],
          correct: 1,
          explain:
            'Embedding forwards, it does not subtype or override. server.Log calls the embedded Logger\'s method.'
        },
        {
          prompt: 'Why can half of Go\'s constructor functions be deleted in well-designed code?',
          options: [
            'Because generics generate constructors',
            'Because a struct literal + a useful zero value already construct a working object',
            'Because the runtime lazily initializes every struct field on first method call, so the constructor\'s work happens automatically later',
            'They cannot — every struct needs a NewX'
          ],
          correct: 1,
          explain:
            'NewX is only a convention. If the zero value works (like sync.Mutex, strings.Builder), a literal is enough.'
        },
        {
          prompt: 'When must you choose pointer receivers for a type?',
          options: [
            'When the type has unexported fields',
            'When any method mutates the receiver (and then be consistent everywhere)',
            'When the type will be stored in a map, since map values are not addressable',
            'When the type has more than one method'
          ],
          correct: 1,
          explain:
            'Mutation requires a pointer receiver; size is the other reason. Mixed receiver sets are a smell.'
        }
      ]
    },
    {
      key: 'pointers',
      title: 'Pointers for Pythonistas',
      body: `# You already use references — now they are visible

Python passes object references everywhere implicitly: hand a list to a function, mutations show. Go passes COPIES everywhere, and a pointer is how you opt back in to sharing. That is the entire mental model: \`&x\` takes the address of x, \`*T\` is the type "pointer to T", and \`p.Field\` dereferences automatically (no \`->\`).

\`\`\`go
func rename(t *Track, title string) {
    t.Title = title          // auto-dereference: (*t).Title
}

track := Track{Title: "old"}
rename(&track, "Tank!")      // pass the address
\`\`\`

No pointer arithmetic exists — a Go pointer is Python's object reference made explicit, not C's raw memory.

## When to use a pointer

- The callee must MUTATE the caller's value (as above)
- The struct is large and copying is wasteful
- You need "absent" as a state: a \`*int\` can be nil where an \`int\` cannot — the Optional[int] of Go, common at JSON and database boundaries (this app's TypeScript has the same \`| null\` pattern)
- Consistency: the type's methods use pointer receivers, so store and pass it as \`*T\` throughout

Otherwise pass values. Small structs copy cheaply, copies cannot be mutated behind your back, and value semantics are easier to reason about — Python does not even offer you that safety.

## nil is your None, and it bites the same way

The zero value of every pointer is \`nil\`; dereferencing nil panics (\`runtime error: invalid memory address\`) — Go's AttributeError-on-None. Guard at the boundaries where nil is meaningful (\`if t == nil { return }\`), and design so most code paths deal in values that cannot be nil rather than sprinkling checks everywhere.

## new, &T{}, and escape analysis

\`new(T)\` allocates a zeroed T and returns \`*T\`, but idiomatic code mostly writes \`&Track{Title: "Tank!"}\` — literal plus address. And unlike C, returning \`&local\` from a function is completely safe:

\`\`\`go
func NewTrack(title string) *Track {
    t := Track{Title: title}
    return &t                // fine — escapes to the heap automatically
}
\`\`\`

The compiler's escape analysis notices the address outlives the function and heap-allocates it. You never think about stack vs heap; you also never free anything — Go is garbage-collected like Python.

One more habit to drop: no \`is\` operator. Pointer equality is just \`==\` on pointers; value equality is \`==\` on comparable values (structs compare field-by-field if all fields are comparable — no \`__eq__\` needed).`,
      questions: [
        {
          prompt: 'Why does passing a struct to a function and mutating a field there not affect the caller (without pointers)?',
          options: [
            'Structs are immutable in function scope',
            'Go passes a copy of the struct; the function mutates the copy',
            'The garbage collector isolates function arguments',
            'It does affect the caller — structs behave like Python objects'
          ],
          correct: 1,
          explain: 'Everything passes by copy. Share the one value by passing &struct instead.'
        },
        {
          prompt: 'Is returning &localVariable from a Go function safe?',
          options: [
            'No — it dangles once the stack frame is gone, exactly as in C, so every Go program must avoid returning addresses of locals',
            'Yes — escape analysis moves it to the heap and the GC manages it',
            'Only for structs smaller than a pointer',
            'Only inside methods'
          ],
          correct: 1,
          explain:
            'The compiler heap-allocates anything whose address outlives the function. This is the standard constructor shape.'
        },
        {
          prompt: 'You need an integer field that can be "absent" (not just 0) when decoding JSON. Idiomatic representation?',
          options: [
            'int with -1 as the sentinel',
            'A second bool field named hasValue',
            '*int — nil means absent',
            'interface{} holding either int or nil'
          ],
          correct: 2,
          explain:
            'Pointer types add a nil state to value types — the Optional of Go, standard at serialization boundaries.'
        }
      ]
    },
    {
      key: 'interfaces',
      title: 'Interfaces: duck typing, checked',
      body: `# Python's protocols, enforced at compile time

An interface lists methods; ANY type with those methods satisfies it — no declaration, no inheritance, no registration:

\`\`\`go
type Storer interface {
    Save(item Item) error
    Load(id int) (Item, error)
}
\`\`\`

If \`*SqliteStore\` happens to have both methods, it IS a Storer — the compiler checks structurally, exactly like duck typing except a typo in a method name fails the build instead of failing in production at 3am. Satisfaction is implicit: \`SqliteStore\` does not know or say that it implements \`Storer\`, which means you can define an interface AFTER the fact for types you do not own.

## Define interfaces where they are USED

The idiom inverted from Java/C#: the consumer declares the interface, listing only what IT needs, and concrete types are returned by producers. \`func Process(r io.Reader)\` accepts files, network connections, buffers, gzip streams — anything with \`Read\`. Keep them tiny: the standard library's most-used interfaces have one or two methods (\`io.Reader\`, \`io.Writer\`, \`fmt.Stringer\`, \`error\` itself). "Accept interfaces, return structs."

\`\`\`go
// This function tests with a bytes.Buffer, runs with an *os.File.
func countLines(r io.Reader) (int, error) { ... }
\`\`\`

That one habit is Go's dependency injection: no framework, just parameters typed as small interfaces, satisfied by fakes in tests.

## any, type assertions, type switches

\`any\` (alias for \`interface{}\`, the empty interface) is satisfied by everything — Go's escape hatch back to dynamic typing. Getting the concrete value back out is explicit:

\`\`\`go
v, ok := x.(string)        // assertion, comma-ok — no panic on mismatch
switch v := x.(type) {     // type switch
case string:  ...
case int:     ...
default:      ...
}
\`\`\`

Reach for \`any\` about as often as you would reach for \`typing.Any\` in well-typed Python — rarely, at true boundaries like JSON of unknown shape.

## The nil-interface trap (worth memorizing now)

An interface value is a pair: (concrete type, value). It is \`== nil\` only when BOTH are nil. Storing a nil \`*MyErr\` pointer into an \`error\` interface produces an interface whose type part is \`*MyErr\` — NOT nil:

\`\`\`go
func do() error {
    var e *MyErr = nil
    return e                 // != nil at the caller!
}
\`\`\`

Every Go developer hits this once. The fix: return the literal \`nil\`, never a typed nil pointer, from functions whose result is an interface.`,
      questions: [
        {
          prompt: 'What must a type do to satisfy an interface in Go?',
          options: [
            'Declare "implements InterfaceName"',
            'Embed the interface in its struct',
            'Simply have all the interface\'s methods — satisfaction is implicit and structural',
            'Be registered in the same package as the interface, which is what the compiler checks'
          ],
          correct: 2,
          explain:
            'Compile-time duck typing: matching method set = satisfies. You can even define interfaces for types you do not own.'
        },
        {
          prompt: 'Where does idiomatic Go declare an interface?',
          options: [
            'Next to each concrete type, exporting one interface per struct',
            'In the consuming package, listing only the methods that consumer needs',
            'In a central interfaces.go shared by the whole project',
            'Interfaces are discouraged entirely'
          ],
          correct: 1,
          explain:
            '"Accept interfaces, return structs" — consumers define small needs-based interfaces, which fakes satisfy in tests.'
        },
        {
          prompt: 'func f() error { var p *PathErr; return p } — what does f() == nil evaluate to?',
          options: [
            'true — p is nil',
            'false — the interface holds (type *PathErr, value nil), and a typed interface is never == nil',
            'It panics',
            'true, but only because PathErr implements error and the inner pointer happens to be nil'
          ],
          correct: 1,
          explain:
            'An interface is nil only when type AND value are nil. Return literal nil from interface-returning functions.'
        },
        {
          prompt: 'What is the safe way to check whether any-typed x holds a string?',
          options: [
            's := x.(string) and recover from the panic',
            's, ok := x.(string)',
            'reflect.TypeOf(x).Kind() == reflect.String, then cast',
            'fmt.Sprintf("%T", x) == "string"'
          ],
          correct: 1,
          explain: 'The comma-ok assertion never panics; the single-result form panics on mismatch.'
        }
      ]
    },
    {
      key: 'packages-modules',
      title: 'Packages, modules, project layout',
      body: `# The unit of code is the package, not the file

Every file in a directory belongs to ONE package, and the package is the unit of compilation, visibility, and import. Files in the same package share a namespace — no imports between them, no per-file privacy. This is unlike Python, where every file is its own module. Split code across files freely; it changes nothing semantically.

Import paths are module path + directory:

\`\`\`go
import (
    "fmt"                                  // stdlib
    "os"

    "github.com/you/navihub-cli/internal/library"   // your own
    "github.com/mattn/go-isatty"                    // third-party
)
\`\`\`

You refer to imported names through the package name: \`library.Scan(...)\`. There is no \`from x import y\` — every use says where it came from, which is why Go code is greppable. (Dot-imports exist and are effectively banned by convention.)

## Visibility recap, because it is the whole access-control system

Capitalized = exported from the package. Lowercase = internal to it. That is it — applied to functions, types, struct fields, methods. A struct can be exported with unexported fields, which is how you make opaque handles.

Additionally the special directory name \`internal/\` is enforced by the compiler: packages under \`internal/\` are importable only by code sharing the parent — a whole subtree private to your module. Use it by default for anything you do not want to support as public API.

## Layout: resist the ceremony

A small tool is one \`main.go\` at the root, and that is fine. Growth pattern:

\`\`\`
go.mod
main.go              // or cmd/<name>/main.go once there are two binaries
internal/
  library/           // one package per domain area
    scan.go
    scan_test.go
\`\`\`

Guidelines that matter: package names are short, lowercase, singular (\`library\`, not \`libraryUtils\`); the name is part of every call site, so \`library.Scan\` not \`library.LibraryScan\`; no \`util\` or \`common\` dumping grounds; and cyclic imports are a compile ERROR, not a runtime surprise — the compiler forces the layering Python only encourages.

## Init order, and the init function

Package-level \`var\`s initialize in dependency order, then each package's \`init()\` functions run, dependencies first, before \`main\`. \`init\` exists for registering drivers and similar; treat it like module-level code in Python — a little is normal, a lot is a design smell (hidden work at import time).

\`go doc fmt.Println\` and pkg.go.dev give you the docs culture: a comment directly above an exported declaration IS its documentation, no docstring syntax needed — just start the sentence with the identifier's name.`,
      questions: [
        {
          prompt: 'Two files in the same directory/package — how does one use a function from the other?',
          options: [
            'import "./other"',
            'Just call it — files in a package share one namespace',
            'Via a package-level registry',
            'Only if the function is capitalized, exactly the same export rule that applies across package boundaries'
          ],
          correct: 1,
          explain:
            'The package is the unit, not the file. Same-package files need no imports and see unexported names.'
        },
        {
          prompt: 'What does placing code under internal/ do?',
          options: [
            'Hides it from godoc only',
            'Compiler-enforced privacy: only the subtree above internal/ can import it',
            'Marks it as unstable API in tooling, which is why go vet warns about importing it',
            'Nothing — it is convention only'
          ],
          correct: 1,
          explain:
            'internal/ is enforced by the toolchain — external modules cannot import those packages at all.'
        },
        {
          prompt: 'Why does Go reject your import at compile time when package a imports b and b imports a?',
          options: [
            'It does not — cycles resolve lazily at import time, exactly like Python\'s circular-import handling with partial modules',
            'Cyclic imports are a hard compile error; the dependency graph must be a DAG',
            'Only cycles through internal/ are rejected',
            'It is a warning promoted to error by go vet'
          ],
          correct: 1,
          explain:
            'The compiler forces acyclic package structure — the layering discipline is built in.'
        },
        {
          prompt: 'How do you document an exported function for go doc / pkg.go.dev?',
          options: [
            'A """docstring""" as the first statement in the function body, exactly as in Python',
            'A @doc annotation',
            'A regular comment immediately above it, conventionally starting with its name',
            'A separate .md file per package'
          ],
          correct: 2,
          explain: '// Scan walks the library root... directly above func Scan is the documentation.'
        }
      ]
    },
    {
      key: 'goroutines',
      title: 'Goroutines: concurrency for the price of a keyword',
      body: `# go f() — that is the API

A goroutine is a function running concurrently with the rest of the program:

\`\`\`go
go fetchCover(url)           // returns immediately; fetchCover runs concurrently
go func() {
    log.Println("inline")
}()
\`\`\`

Goroutines are runtime-scheduled green threads: starting one costs a few KB of stack (it grows as needed), so hundreds of thousands are normal. Compare the Python landscape you know: threads are OS-heavy and GIL-throttled for CPU work; asyncio needs the async/await coloring through your whole call stack and one blocking call stalls the loop. Go has neither problem — goroutines use real parallelism across cores (GOMAXPROCS defaults to core count), and blocking calls (file IO, network, sleep) just park the goroutine while the OS thread moves on. There are no colored functions: any function can be launched concurrently, none needs an \`async\` marker.

## main does not wait

When \`main\` returns, the process exits — running goroutines are killed mid-flight, no warning:

\`\`\`go
func main() {
    go work()
    // main returns here; work() likely never ran
}
\`\`\`

Something must wait. The two standard tools are channels (next lesson) and \`sync.WaitGroup\`:

\`\`\`go
var wg sync.WaitGroup
for _, url := range urls {
    wg.Add(1)
    go func() {
        defer wg.Done()
        fetch(url)
    }()
}
wg.Wait()
\`\`\`

\`Add\` before starting, \`defer wg.Done()\` first line inside, \`Wait\` to block until the count drains. This is the fan-out/fan-in skeleton you will write constantly (it is asyncio.gather, without the await coloring).

## Shared memory is now actually shared

The GIL quietly serialized your Python threads; Go runs goroutines in parallel for real, so unsynchronized concurrent access to shared data is a DATA RACE — undefined behavior, not just stale reads. Two goroutines doing \`counter++\` can lose increments; concurrent map writes crash the program outright.

The verdict tool is built in: \`go test -race\` / \`go run -race\` instruments the binary and reports races with stack traces. Run the race detector in CI always. Fixes come in two schools — mutexes (\`sync.Mutex\` around the shared thing) and channels (give the data one owner and communicate) — both next lesson. The slogan to internalize: do not communicate by sharing memory; share memory by communicating.`,
      questions: [
        {
          prompt: 'What happens to running goroutines when main returns?',
          options: [
            'The runtime waits for them to finish',
            'They are killed immediately — the process just exits',
            'They keep running as daemon threads',
            'main cannot return while goroutines exist — the compiler inserts an implicit wait at the end of main'
          ],
          correct: 1,
          explain:
            'Nothing waits implicitly. Use a WaitGroup or channel to hold main open until work completes.'
        },
        {
          prompt: 'Why can Go handle 100k concurrent goroutines where 100k Python threads would fall over?',
          options: [
            'Goroutines cannot block at all, so they never hold an OS thread hostage while waiting on IO',
            'Goroutines are runtime-scheduled with tiny growable stacks, multiplexed onto few OS threads',
            'Go limits each goroutine to 1ms timeslices',
            'It cannot — the practical ceiling is similar'
          ],
          correct: 1,
          explain:
            'A few KB per goroutine and m:n scheduling make massive concurrency cheap; blocking parks the goroutine, not the thread.'
        },
        {
          prompt: 'Two goroutines increment the same int without synchronization. What is this?',
          options: [
            'Safe — int operations are atomic on 64-bit platforms',
            'A data race: undefined behavior, detectable with go test -race',
            'Safe but slow due to cache contention',
            'A compile error'
          ],
          correct: 1,
          explain:
            'No GIL protects you now. counter++ is read-modify-write; races are UB. The race detector exists for exactly this.'
        },
        {
          prompt: 'Where does wg.Add(1) belong in the WaitGroup pattern?',
          options: [
            'First line inside the goroutine',
            'Before launching the goroutine, in the spawning code',
            'Right before wg.Wait()',
            'Anywhere — Add is order-independent as long as the total count matches the Done calls before Wait returns'
          ],
          correct: 1,
          explain:
            'Add inside the goroutine races with Wait: Wait can pass before the goroutine gets scheduled to Add.'
        }
      ]
    },
    {
      key: 'channels',
      title: 'Channels & select',
      body: `# Typed pipes between goroutines

A channel is a typed conduit: one goroutine sends, another receives, and the handoff is the synchronization — no locks needed for data that moves through a channel.

\`\`\`go
results := make(chan string)     // unbuffered
go func() { results <- scan(dir) }()
r := <-results                   // blocks until the send happens
\`\`\`

The arrow points the way data flows: \`ch <- v\` sends, \`v := <-ch\` receives. An UNBUFFERED channel is a rendezvous — send blocks until a receiver is ready and vice versa. \`make(chan T, n)\` adds a buffer: sends only block when it is full, receives when empty. Rule of thumb: start unbuffered (the synchronization is the point); add a small buffer only for a measured reason, not superstition.

## range, close, and who closes

\`\`\`go
jobs := make(chan string)
go func() {
    for _, path := range paths {
        jobs <- path
    }
    close(jobs)                  // "no more values"
}()
for p := range jobs {            // receives until closed AND drained
    process(p)
}
\`\`\`

\`close\` is a broadcast of "done sending", not a destructor. The rules: only the SENDER closes; sending on a closed channel panics; receiving from a closed channel yields zero values immediately (with \`v, ok := <-ch\` telling you \`ok=false\`); and you do not need to close channels you abandon — the GC collects them. Closing matters exactly when a receiver ranges or needs the done signal.

## select: wait on several things at once

\`select\` is switch for channel operations — it blocks until ONE case can proceed, choosing randomly among ready cases:

\`\`\`go
select {
case r := <-results:
    handle(r)
case <-time.After(5 * time.Second):
    return errors.New("scan timed out")
case <-ctx.Done():               // cancellation — next lesson
    return ctx.Err()
}
\`\`\`

That shape — result, timeout, cancellation — is the heart of production Go. A \`default\` case makes select non-blocking (do something else if nothing is ready). This is the capability asyncio builds a whole event loop to provide, available as a control-flow statement.

## nil channel weirdness (useful, eventually)

Send and receive on a NIL channel block forever. That sounds like a footgun and occasionally is, but inside a select it is a feature: set a case's channel variable to nil and that case switches off — the standard trick for disabling a completed source in a multi-source select loop. File it away; you will meet it in real code.`,
      questions: [
        {
          prompt: 'On an unbuffered channel, what does ch <- v do if no receiver is waiting?',
          options: [
            'Drops the value',
            'Queues it in an unbounded internal buffer that grows automatically, the same way Python\'s queue.Queue does',
            'Blocks the sending goroutine until a receiver takes it',
            'Panics'
          ],
          correct: 2,
          explain:
            'Unbuffered = rendezvous. The blocking IS the synchronization between the two goroutines.'
        },
        {
          prompt: 'Who should close a channel, and what happens if you send on a closed one?',
          options: [
            'The receiver closes; sends on closed return an error',
            'The sender closes; sending on a closed channel panics',
            'Either side; the runtime dedups closes',
            'The GC closes channels automatically when needed for range loops'
          ],
          correct: 1,
          explain:
            'Close means "no more sends", so only the sender can know when. Double-close and send-on-closed both panic.'
        },
        {
          prompt: 'What does a for p := range jobs loop over a channel do?',
          options: [
            'Iterates the values currently buffered, then exits',
            'Receives values until the channel is closed and drained',
            'Spins forever unless you break',
            'Requires the channel to be buffered'
          ],
          correct: 1,
          explain: 'range receives until close(jobs) has been called and the buffer is empty — the natural consumer loop.'
        },
        {
          prompt: 'If two cases of a select are ready at the same moment, which runs?',
          options: [
            'The one declared first',
            'Both, in declaration order',
            'One chosen at random',
            'The one whose channel has more buffered values'
          ],
          correct: 2,
          explain: 'Uniform random among ready cases — deliberate, so no source starves the others.'
        }
      ]
    },
    {
      key: 'concurrency-patterns',
      title: 'Concurrency patterns: WaitGroup, Mutex, context, worker pools',
      body: `# The four tools that cover 95% of real code

## sync.Mutex — when sharing is simpler than channeling

Channels move data between owners; sometimes you genuinely want shared state (a cache, a counter, a status struct). Then you lock:

\`\`\`go
type Library struct {
    mu     sync.Mutex
    covers map[int]string
}

func (l *Library) SetCover(id int, path string) {
    l.mu.Lock()
    defer l.mu.Unlock()
    l.covers[id] = path
}
\`\`\`

Conventions: the mutex sits ABOVE the fields it guards; every access to those fields goes through Lock/Unlock; \`defer Unlock\` immediately after Lock so early returns cannot leak the lock. \`sync.RWMutex\` adds RLock for read-heavy data. For a lone counter, \`sync/atomic\` is lighter still. (This app's main process uses exactly this shape — the module-level status objects its renderer polls.)

## context.Context — cancellation as a first-class value

Python's asyncio cancels tasks; Go threads cancellation through an explicit parameter. \`ctx\` is always the FIRST parameter, and long operations check it:

\`\`\`go
func scanAll(ctx context.Context, dirs []string) error {
    for _, d := range dirs {
        select {
        case <-ctx.Done():
            return ctx.Err()      // context.Canceled or DeadlineExceeded
        default:
        }
        scan(d)
    }
    return nil
}

ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
defer cancel()
err := scanAll(ctx, dirs)
\`\`\`

\`WithCancel\`, \`WithTimeout\`, \`WithDeadline\` derive child contexts; cancelling a parent cancels every descendant. All real IO APIs accept a ctx — HTTP requests, database queries — so one timeout at the top bounds a whole call tree. Always \`defer cancel()\` to release the timer.

## Worker pool — bounded fan-out

Unbounded \`go\` per item can swamp a remote API (this app's image downloader uses a 5-worker pool for exactly that reason). The shape:

\`\`\`go
jobs := make(chan string)
var wg sync.WaitGroup
for i := 0; i < 5; i++ {          // 5 workers
    wg.Add(1)
    go func() {
        defer wg.Done()
        for url := range jobs {
            download(url)
        }
    }()
}
for _, u := range urls {
    jobs <- u
}
close(jobs)                        // workers' range loops end
wg.Wait()
\`\`\`

Producer feeds the channel and closes it; N workers range until it drains; WaitGroup holds the door. Memorize this — it is the single most-reused concurrent shape in Go.

## errgroup — the gather() you were missing

\`golang.org/x/sync/errgroup\` wraps WaitGroup with error collection and shared cancellation: \`g, ctx := errgroup.WithContext(ctx)\`, launch with \`g.Go(func() error {...})\`, then \`err := g.Wait()\` returns the first error after everything stops — the closest analogue to \`asyncio.gather\` with fail-fast. \`g.SetLimit(n)\` even builds the worker pool for you.`,
      questions: [
        {
          prompt: 'Why does the idiomatic mutex-guarded method start with lock-then-defer-unlock?',
          options: [
            'defer makes the unlock atomic',
            'So every return path (and panic) releases the lock — no leak on early return',
            'Because Unlock must run on the same line count as Lock for the race detector',
            'It is required by the compiler for RWMutex'
          ],
          correct: 1,
          explain: 'defer ties release to function exit however it happens; forgetting an unlock on one path deadlocks later.'
        },
        {
          prompt: 'Where does context.Context go in a function signature, by convention?',
          options: [
            'Last parameter',
            'First parameter, named ctx',
            'Inside a config struct',
            'A package-level variable'
          ],
          correct: 1,
          explain: 'func f(ctx context.Context, ...) — always first, always explicit, never stored in a struct.'
        },
        {
          prompt: 'In the worker-pool pattern, what makes the workers\' for range jobs loops terminate?',
          options: [
            'wg.Wait() signals them',
            'The producer calling close(jobs) after sending everything',
            'A sentinel value like nil sent once per worker',
            'They time out when the channel is empty'
          ],
          correct: 1,
          explain:
            'range on a channel ends when it is closed and drained. Sender closes; WaitGroup then confirms the workers exited.'
        },
        {
          prompt: 'What does cancelling a parent context do to contexts derived from it?',
          options: [
            'Nothing — each must be cancelled individually',
            'Cancels every descendant, unblocking anything selecting on their Done()',
            'Only cancels children created with WithCancel, not WithTimeout',
            'Resets their deadlines'
          ],
          correct: 1,
          explain:
            'Cancellation propagates down the derivation tree — one top-level timeout bounds the whole call graph.'
        }
      ]
    },
    {
      key: 'testing',
      title: 'Testing: table-driven, race-checked, benchmarked',
      body: `# The runner is built in; the assertions are just code

A test is a file ending \`_test.go\` with functions \`func TestXxx(t *testing.T)\`. No pytest, no fixtures framework, no assertion DSL:

\`\`\`go
func TestSlugify(t *testing.T) {
    got := Slugify("Cowboy Bebop!")
    if got != "cowboy-bebop" {
        t.Errorf("Slugify() = %q, want %q", got, "cowboy-bebop")
    }
}
\`\`\`

\`t.Errorf\` reports and continues; \`t.Fatalf\` reports and stops this test. There is no assertEqual — you write \`if got != want\` and a GOOD failure message. (Deep comparisons: \`reflect.DeepEqual\` or the widely-used go-cmp package.)

## Table-driven tests: the house style

Where pytest uses parametrize, Go uses a slice of cases and subtests:

\`\`\`go
func TestSlugify(t *testing.T) {
    tests := []struct {
        name, in, want string
    }{
        {"spaces", "Cowboy Bebop", "cowboy-bebop"},
        {"punctuation", "Tank!", "tank"},
        {"japanese kept", "日本語 OK", "日本語-ok"},
    }
    for _, tt := range tests {
        t.Run(tt.name, func(t *testing.T) {
            if got := Slugify(tt.in); got != tt.want {
                t.Errorf("Slugify(%q) = %q, want %q", tt.in, got, tt.want)
            }
        })
    }
}
\`\`\`

\`t.Run\` makes each row a named subtest: failures name the row, and \`go test -run TestSlugify/japanese\` runs one. Adding a case = adding a line, so edge cases actually get added.

## The flags that matter

- \`go test ./...\` — everything
- \`go test -run TestName\` — filter by regex
- \`go test -race ./...\` — race detector on: non-negotiable for concurrent code
- \`go test -cover\` — coverage percentage
- \`go test -v\` — verbose (only when debugging; quiet is the norm)

\`t.Helper()\` marks a function as a test helper so failures blame the caller's line. \`t.Cleanup(f)\` is defer for tests (runs after subtests too). \`t.TempDir()\` gives a self-deleting directory — half your filesystem fixtures for free.

## Benchmarks and fuzzing, same file

\`\`\`go
func BenchmarkSlugify(b *testing.B) {
    for b.Loop() {
        Slugify("Cowboy Bebop")
    }
}
\`\`\`

\`b.Loop()\` is Go 1.24+. Before that the idiom was \`for range b.N\` (or \`for i := 0; i < b.N; i++\`), which you will still see everywhere.

\`go test -bench .\` runs it, reporting ns/op (add \`-benchmem\` for allocations). Fuzzing is built in too: \`func FuzzSlugify(f *testing.F)\` + \`go test -fuzz\` generates adversarial inputs — no hypothesis dependency.

Design note you already live by in this codebase: pure functions with injectable IO test without mocks. Go's version of that discipline is accepting small interfaces (\`io.Reader\`, your own \`Storer\`) so tests pass in fakes — no monkeypatching exists, and its absence is a feature: if it is hard to test, the design says so at compile time.`,
      questions: [
        {
          prompt: 'What is the difference between t.Errorf and t.Fatalf?',
          options: [
            'Errorf is for warnings only and never marks the test as failed; only Fatalf can fail a test',
            'Both fail the test; Fatalf also stops executing it, Errorf continues',
            'Fatalf aborts the whole package\'s tests',
            'Errorf only prints when -v is set'
          ],
          correct: 1,
          explain:
            'Both mark failure. Fatalf returns immediately (use when continuing is pointless, e.g. setup failed).'
        },
        {
          prompt: 'What does t.Run give a table-driven test?',
          options: [
            'Parallel execution by default, so every row of the table runs on its own goroutine',
            'Named subtests — failures identify the row, and -run can target one case',
            'Automatic retry of flaky rows',
            'Nothing; it is legacy API'
          ],
          correct: 1,
          explain:
            'Each row becomes TestX/row-name, individually reported and individually runnable.'
        },
        {
          prompt: 'How does Go testing culture replace unittest.mock.patch?',
          options: [
            'The testing/mock stdlib package',
            'Build-tag-swapped implementations',
            'It does not patch: code accepts small interfaces, tests pass fake implementations',
            'Reflection-based stubbing of package-level functions, provided by the testing package'
          ],
          correct: 2,
          explain:
            'No monkeypatching exists. Dependencies arrive as interface parameters, so a test hands in a fake — design pressure toward testable code.'
        },
        {
          prompt: 'Which invocation must be in CI for any codebase with goroutines?',
          options: ['go test -v ./...', 'go test -race ./...', 'go test -bench . ./...', 'go vet -tests ./...'],
          correct: 1,
          explain: 'The race detector catches real data races at test time; without it they ship and corrupt state in production.'
        }
      ]
    },
    {
      key: 'generics',
      title: 'Generics: type parameters, used sparingly',
      body: `# The feature Go resisted for a decade

Since 1.18, functions and types can take type parameters in square brackets:

\`\`\`go
func Map[T, U any](xs []T, f func(T) U) []U {
    out := make([]U, 0, len(xs))
    for _, x := range xs {
        out = append(out, f(x))
    }
    return out
}

titles := Map(tracks, func(t Track) string { return t.Title })
\`\`\`

\`[T, U any]\` declares type parameters; \`any\` is their constraint (anything goes). Call sites almost never name the types — inference fills them in. Unlike Python's hints, these are compile-time enforced and monomorphized: real typed code, not annotations.

## Constraints say what a T can do

A constraint is an interface used at compile time. Beyond \`any\`, the common ones:

\`\`\`go
import "cmp"

func Max[T cmp.Ordered](a, b T) T {   // any type with < <= > >=
    if a > b { return a }
    return b
}

type Number interface {
    ~int | ~int64 | ~float64          // union of types; ~ includes named variants
}
func Sum[T Number](xs []T) T { ... }
\`\`\`

\`cmp.Ordered\` covers everything comparable with \`<\`. Union elements (\`int | float64\`) list allowed types, and the tilde \`~int\` admits user-defined types whose underlying type is int (your \`type Level int\` from lesson two). Ordinary method-listing interfaces work as constraints too.

## Where generics actually get used

- The stdlib you already met: \`slices.Contains\`, \`slices.Sort\`, \`maps.Keys\` — all generic, all just work
- Data structures: a typed \`Set[T]\`, \`Stack[T]\`, an LRU cache — the real win, killing the interface{}-and-cast pattern of old Go
- Small algorithm helpers like Map/Filter above — though note the stdlib deliberately does NOT ship Map/Filter; the community still often prefers the explicit loop

And where they do not: if a plain interface parameter works, use it. \`func Process(r io.Reader)\` needs no type parameter — the interface already abstracts. Generics earn their keep when the RELATIONSHIP between types matters (the same T going in and coming out, or a container's element type). A function generic over one parameter it merely calls methods on should have been an interface.

## The tell of over-generic code

Coming from Python's TypeVar-everywhere culture, resist decorating every helper with [T any]. Go review culture pushes back hard on speculative genericity: write the concrete version, generalize on the second or third real use. Boring first, abstract when forced — the same instinct as the rest of the language.`,
      questions: [
        {
          prompt: 'What does the constraint in func Max[T cmp.Ordered](a, b T) T buy over any?',
          options: [
            'Faster compilation',
            'It permits a > b inside the body — the compiler knows T supports ordering',
            'It allows T to be inferred at the call site',
            'It restricts Max to the stdlib\'s built-in numeric types only, excluding any user-defined type even if it satisfies the same operations'
          ],
          correct: 1,
          explain:
            'Constraints define available operations. With any, comparing a > b would not compile; Ordered admits all <-comparable types.'
        },
        {
          prompt: 'What does the tilde in ~int mean inside a constraint union?',
          options: [
            'Approximately int-sized types such as int32 and int64, the same numeric-widening rule Python\'s int applies automatically',
            'Any type whose underlying type is int, like type Level int',
            'A pointer to int',
            'int, but only on 64-bit platforms'
          ],
          correct: 1,
          explain: '~int includes named types built on int; bare int in a union admits only int itself.'
        },
        {
          prompt: 'A function takes one argument and only calls its .Close() method. Generic type parameter or interface?',
          options: [
            'Generic — [T io.Closer] is more reusable because it keeps the concrete type around',
            'Interface — func f(c io.Closer); generics add nothing without a type relationship',
            'Either is equally idiomatic',
            'Neither — take *os.File concretely'
          ],
          correct: 1,
          explain:
            'Generics pay off when types relate (T in, T out; containers of T). Pure behavior abstraction is what interfaces are for.'
        }
      ]
    },
    {
      key: 'idioms-gotchas',
      title: 'Idioms, gotchas, and a stdlib tour',
      body: `# The gotcha shortlist

You have met the big ones; here is the consolidated list to re-read after your first week of real Go:

- **Typed nil in an interface** — an interface holding a nil *T is not == nil. Return literal nil.
- **append aliasing** — two slices sharing a backing array; append through one can overwrite the other's view. Clone when handing slices across API boundaries.
- **Value receiver mutation** — silently edits a copy. If a "setter" does nothing, look at the receiver.
- **Nil map writes panic** — make it first; nil slices are fine.
- **defer in a loop** — releases pile up until the function ends; extract the body into a function.
- **range copies** — for _, v := range items gives you a COPY of each element; mutating v changes nothing. Use the index (items[i].X = ...) to mutate in place.
- **Shadowing with :=** — if x, err := f() inside a block creates a NEW err, an outer err stays nil. go vet catches some; eyes catch the rest.
- **time.Format** — no strftime. The reference moment is literal: ts.Format("2006-01-02 15:04:05"). Yes really: month 1, day 2, hour 3 (15), minute 4, second 5, year 6.

## Idioms that mark fluent Go

- Guard clauses over nesting: handle the error, return early; the happy path hugs the left margin.
- Small interfaces at the consumer; concrete types from the producer.
- Zero values that work, so constructors stay rare.
- Composition (embedding, interfaces) — nobody misses inheritance after month one.
- Comments explain WHY; the code, gofmt-ed, explains what. Exported things get doc comments starting with their name.

## Stdlib tour: what replaces your pip favorites

- \`net/http\` — client AND production-grade server. requests + Flask, in the box: http.HandleFunc plus http.ListenAndServe is a deployable service.
- \`encoding/json\` — Marshal/Unmarshal onto structs with field tags; pydantic's core use case, minus the validation layer.
- \`os\`, \`path/filepath\` — files, walking trees (filepath.WalkDir), path joining that respects the OS.
- \`time\` — durations are typed (5 * time.Second), timers, tickers; no naive-vs-aware datetime schism.
- \`flag\` — argparse for the common cases.
- \`log/slog\` — structured logging, stdlib since 1.21.
- \`database/sql\` — the DB-API; add a driver import and go.
- \`strconv\` — string ↔ number, faster and stricter than fmt.
- \`sync\`, \`context\`, \`errors\`, \`slices\`, \`maps\`, \`cmp\` — you know these now.

The habit shift: check the stdlib BEFORE searching for a package. Go's culture runs dependency-light — a go.mod with six requirements is normal, and half of those pull in nothing transitively. Coming from a lockfile with 400 entries, this is the quiet luxury of the ecosystem.

## Where to go from here

Read real code: the stdlib itself is readable (go doc -src strings.Builder), and Effective Go plus the Go Code Review Comments wiki encode the culture. Then port something you know — a script, a small service — and let the compiler and go vet argue with you. The language is small; fluency is mostly unlearning workarounds Python taught you to need.`,
      questions: [
        {
          prompt: 'Why is ts.Format("%Y-%m-%d") wrong in Go?',
          options: [
            'Format takes an enum of layout constants only, so arbitrary strings are rejected',
            'Go layouts use the literal reference time 2006-01-02 15:04:05 instead of % verbs',
            'strftime verbs need a leading 0 in Go',
            'It is right — Go supports strftime'
          ],
          correct: 1,
          explain:
            'The layout IS an example: Format("2006-01-02") for dates. Mnemonic ordering 1..7 (month day hour minute second year zone).'
        },
        {
          prompt: 'for _, item := range items { item.Count++ } — why does nothing change?',
          options: [
            'range locks the slice as read-only',
            'item is a copy of each element; mutate via items[i].Count++ instead',
            'Count++ on struct fields needs a pointer receiver method, which this range loop never calls',
            'It does change items'
          ],
          correct: 1,
          explain: 'range yields copies of elements. Index into the slice (or store pointers) to mutate in place.'
        },
        {
          prompt: 'An if-block does x, err := f() while an outer err exists. What is the shadowing risk?',
          options: [
            'A compile error: err is redeclared',
            'The block creates a NEW err; the outer one stays nil and later checks pass wrongly',
            'The outer err is overwritten unexpectedly, so an earlier failure is silently lost here',
            ':= cannot appear inside if blocks'
          ],
          correct: 1,
          explain:
            ':= declares fresh variables in the inner scope when paired with any new name. The outer err silently never gets the failure.'
        },
        {
          prompt: 'Which stdlib package makes a deployable HTTP service without any framework?',
          options: ['net/rpc', 'net/http', 'html/template', 'encoding/gob'],
          correct: 1,
          explain:
            'net/http\'s server is production-grade: HandleFunc + ListenAndServe is how plenty of real services ship.'
        }
      ]
    }
  ]
}
