import { defineInterpretation } from '../../schema'

export default defineInterpretation({
  id: 'franco-prussian-war-responsibility',
  about: ['event:franco-prussian-war'],
  topic: 'responsibility',
  researched: '2026-10-06',
  positions: [
    {
      id: 'bismarck-engineered',
      category: 'scholarly',
      holders: [
        { kind: 'organization', name: 'Library of Congress, Federal Research Division' }
      ],
      statements: [
        {
          id: 'q1',
          text: 'In 1870 Bismarck engineered another war, this time against France.',
          lang: 'en',
          cite: {
            source: 'loc-germany-country-study-1995',
            loc: { section: 'Bismarck and Unification', para: '5' }
          },
          provenance: { via: 'web', at: '2026-10-06', url: 'http://countrystudies.us/germany/27.htm' }
        },
        {
          id: 'q2',
          text: 'Bismarck\'s major war aim--the voluntary entry of the south German states into a constitutional German nation-state--occurred during the patriotic frenzy generated by stunning military victories against French forces in the fall of 1870.',
          lang: 'en',
          cite: {
            source: 'loc-germany-country-study-1995',
            loc: { section: 'Bismarck and Unification', para: '5' }
          },
          provenance: { via: 'web', at: '2026-10-06', url: 'http://countrystudies.us/germany/27.htm' }
        }
      ]
    },
    {
      id: 'affront-and-declaration',
      category: 'scholarly',
      holders: [
        { kind: 'organization', name: 'Deutsches Historisches Museum' }
      ],
      statements: [
        {
          id: 'q3',
          text: 'Die französische Regierung ist empört über diesen erneuten Affront Bismarcks.',
          lang: 'de',
          cite: { source: 'lemo-chronik-1870', loc: { section: 'Chronik 1870', para: '24' } },
          provenance: {
            via: 'web',
            at: '2026-10-06',
            url: 'https://www.dhm.de/lemo/jahreschronik/1870.html'
          }
        }
      ]
    },
    {
      id: 'thiers-for-peace',
      category: 'official',
      holders: [
        { kind: 'organization', name: 'Présidence de la République' }
      ],
      statements: [
        {
          id: 'q4',
          text: 'Hostile à la guerre contre la Prusse, il milite pour la paix.',
          lang: 'fr',
          cite: { source: 'elysee-adolphe-thiers', loc: { section: 'Adolphe Thiers' } },
          provenance: {
            via: 'web',
            at: '2026-10-06',
            url: 'https://www.elysee.fr/la-presidence/adolphe-thiers'
          }
        }
      ]
    }
  ]
})
