import { defineInterpretation } from '../../schema'

export default defineInterpretation({
  id: 'franco-prussian-war-responsibility',
  about: ['event:franco-prussian-war'],
  topic: 'responsibility',
  researched: '2026-10-08',
  positions: [
    {
      id: 'bismarck-engineered',
      category: 'scholarly',
      holders: [
        { kind: 'organization', name: 'Library of Congress, Federal Research Division' }
      ],
      statements: [
        {
          id: 'q1',
          text: 'In 1870 Bismarck engineered another war, this time against France.',
          lang: 'en',
          cite: {
            source: 'loc-germany-country-study-1995',
            loc: { section: 'Bismarck and Unification', para: '5' }
          },
          provenance: { via: 'web', at: '2026-10-06', url: 'http://countrystudies.us/germany/27.htm' }
        },
        {
          id: 'q2',
          text: 'Bismarck\'s major war aim--the voluntary entry of the south German states into a constitutional German nation-state--occurred during the patriotic frenzy generated by stunning military victories against French forces in the fall of 1870.',
          lang: 'en',
          cite: {
            source: 'loc-germany-country-study-1995',
            loc: { section: 'Bismarck and Unification', para: '5' }
          },
          provenance: { via: 'web', at: '2026-10-06', url: 'http://countrystudies.us/germany/27.htm' }
        }
      ]
    },
    {
      id: 'ems-telegram-to-be-attacked',
      category: 'contemporary',
      holders: [
        { kind: 'participant', name: 'Otto von Bismarck', ref: 'person:otto-von-bismarck' }
      ],
      statements: [
        {
          id: 'q3',
          text: 'After I had read out the concentrated edition to my two guests, Moltke remarked : \' Now it has a different ring; it sounded before like a parley; now it is like a flourish in answer to a challenge.\'',
          lang: 'en',
          cite: {
            source: 'bismarck-1898-man-and-statesman-vol-2',
            loc: { section: 'Chapter XXII. The Ems Telegram' }
          },
          provenance: {
            via: 'web',
            at: '2026-10-08',
            url: 'https://archive.org/download/bismarckmanstate02bismuoft/bismarckmanstate02bismuoft_djvu.txt'
          }
        },
        {
          id: 'q4',
          text: 'Fight we must if we do not want to act the part of the vanquished without a battle. Success, however, essentially depends upon the impression which the origination of the war makes upon us and others ; it is important that we should be the party attacked',
          lang: 'en',
          cite: {
            source: 'bismarck-1898-man-and-statesman-vol-2',
            loc: { section: 'Chapter XXII. The Ems Telegram' }
          },
          provenance: {
            via: 'web',
            at: '2026-10-08',
            url: 'https://archive.org/download/bismarckmanstate02bismuoft/bismarckmanstate02bismuoft_djvu.txt'
          }
        }
      ]
    },
    {
      id: 'war-forced-on-france',
      category: 'contemporary',
      holders: [
        { kind: 'participant', name: 'Émile Ollivier' }
      ],
      statements: [
        {
          id: 'q5',
          text: '« Oui, d’un cœur léger, et n’équivoquez pas sur cette parole, et ne croyez pas que je veuille dire avec joie ; je vous ai dit moi-même mon chagrin d’être condamné à la guerre, je veux dire d’un cœur que le remords n’alourdit pas, d’un cœur confiant, parce que la guerre que nous ferons, nous la subissons, parce que nous avons fait tout ce qu’il était humainement et honorablement possible de tenter pour l’éviter ; et enfin parce que notre cause est juste et qu’elle est confiée à l’armée française. »',
          lang: 'fr',
          cite: {
            source: 'ollivier-1909-notre-reponse-au-soufflet-de-bismarck',
            loc: {
              section: 'Notre réponse au soufflet de Bismarck. Déclaration du 15 juillet',
              para: '12'
            }
          },
          provenance: {
            via: 'web',
            at: '2026-10-08',
            url: 'https://fr.wikisource.org/wiki/Notre_R%C3%A9ponse_au_soufflet_de_Bismarck_-_D%C3%A9claration_du_15_juillet'
          }
        },
        {
          id: 'q6',
          text: 'D’où la guerre est-elle sortie ? De la candidature Hohenzollern, d’abord, puis de la divulgation faite par Bismarck du refus du Roi de recevoir notre ambassadeur. Pas de candidature Hohenzollern, pas de guerre. Même après la candidature Hohenzollern, pas de divulgation du refus du Roi, pas de guerre. Or, est-ce le gouvernement de l’Empereur qui a suscité la candidature Hohenzollern ? Est-ce le gouvernement de l’Empereur qui a divulgué le refus d’Ems ?',
          lang: 'fr',
          cite: {
            source: 'ollivier-1909-notre-reponse-au-soufflet-de-bismarck',
            loc: {
              section: 'Notre réponse au soufflet de Bismarck. Déclaration du 15 juillet',
              para: '62'
            }
          },
          provenance: {
            via: 'web',
            at: '2026-10-08',
            url: 'https://fr.wikisource.org/wiki/Notre_R%C3%A9ponse_au_soufflet_de_Bismarck_-_D%C3%A9claration_du_15_juillet'
          }
        }
      ]
    }
  ]
})
