// Bundled artwork for the theme interaction layer. Sources and licences are
// listed in assets/themes/README.md.
import lainDancing from '../assets/themes/fx/lain-dancing.png'
import lainCoplandEye from '../assets/themes/fx/lain-copland-eye.png'
import lainNavi from '../assets/themes/fx/lain-navi.jpg'
import lainPortrait from '../assets/themes/fx/lain-portrait.png'
import lainSignalLost from '../assets/themes/fx/lain-signal-lost.jpg'
import lainLogo from '../assets/themes/fx/lain-logo.png'
import lainSite from '../assets/themes/fx/lain-site.jpg'
import mgsNaomi from '../assets/themes/fx/mgs-codec-naomi.png'
import mgsSnake from '../assets/themes/fx/mgs-codec-snake.png'
import mgsMeiLing from '../assets/themes/fx/mgs-codec-meiling.png'
import mgsFreq from '../assets/themes/fx/mgs-codec-freq.png'
import mgsGameOver from '../assets/themes/fx/mgs-gameover.jpg'
import mgsBox from '../assets/themes/fx/mgs-box.png'
import mgsRation from '../assets/themes/fx/mgs-item-ration.png'
import mgsScope from '../assets/themes/fx/mgs-item-scope.png'
import mgsThermal from '../assets/themes/fx/mgs-item-thermal-goggles.png'
import mgsCard from '../assets/themes/fx/mgs-item-card.png'
import mgsBandage from '../assets/themes/fx/mgs-item-bandage.png'
import mgsSuppressor from '../assets/themes/fx/mgs-item-suppressor.png'
import mgsRadar from '../assets/themes/fx/mgs-radar.png'
import mgsSnakeWalk from '../assets/themes/fx/mgs-snake-walk.png'
import mikuHachuneBusy from '../assets/themes/fx/miku-hachune-busy.png'
import mikuHachuneWork from '../assets/themes/fx/miku-hachune-work.png'
import mikuCool from '../assets/themes/fx/miku-cool.png'
import mikuNote from '../assets/themes/fx/miku-note.png'
import mikuSingerMiku from '../assets/themes/fx/miku-singer-miku.png'
import mikuSingerRin from '../assets/themes/fx/miku-singer-rin.png'
import mikuSingerKaito from '../assets/themes/fx/miku-singer-kaito.png'
import mikuSingerMeiko from '../assets/themes/fx/miku-singer-meiko.png'
import mikuHachune from '../assets/themes/fx/miku-hachune.png'
import mikuHachunePanic from '../assets/themes/fx/miku-hachune-panic.jpg'
import mikuSongSelect from '../assets/themes/fx/miku-song-select.jpg'
import peaksRedRoom from '../assets/themes/fx/peaks-red-room.jpg'
import peaksCurtain from '../assets/themes/fx/peaks-curtain.jpg'
import peaksWhiteHorse from '../assets/themes/fx/peaks-white-horse.jpg'
import peaksWren from '../assets/themes/fx/peaks-wren.jpg'
import peaksFalls from '../assets/themes/fx/peaks-falls.jpg'
import peaksMist from '../assets/themes/fx/peaks-mist.jpg'
import peaksLogo from '../assets/themes/fx/peaks-logo.png'
import peaksDoubleR from '../assets/themes/fx/peaks-double-r.jpg'
import peaksDiane from '../assets/themes/fx/peaks-diane.jpg'

import sfLogo from '../assets/themes/fx/seinfeld-logo.png'
import sfStandup from '../assets/themes/fx/seinfeld-standup.jpg'
import sfJerry from '../assets/themes/fx/seinfeld-jerry.jpg'
import sfGeorge from '../assets/themes/fx/seinfeld-george.jpg'
import sfElaine from '../assets/themes/fx/seinfeld-elaine.jpg'
import sfKramer from '../assets/themes/fx/seinfeld-kramer.jpg'
import sfNewman from '../assets/themes/fx/seinfeld-newman.jpg'
import sfSoupNazi from '../assets/themes/fx/seinfeld-soup-nazi.jpg'
import sfPuddy from '../assets/themes/fx/seinfeld-puddy.jpg'
import sfFestivus from '../assets/themes/fx/seinfeld-festivus.jpg'
import sfMenu from '../assets/themes/fx/seinfeld-menu.jpg'
import sfElaineDance from '../assets/themes/fx/seinfeld-elaine-dance.gif'
import sfElaineStill from '../assets/themes/fx/seinfeld-elaine-still.jpg'
import sfGang from '../assets/themes/fx/seinfeld-gang.jpg'
import sfKramerEntrance from '../assets/themes/fx/seinfeld-kramer-entrance.jpg'

import bzCloak from '../assets/themes/fx/berserk-cloak.jpg'
import bzEmboss from '../assets/themes/fx/berserk-emboss.jpg'
import bzMark from '../assets/themes/fx/berserk-mark.png'
import bzCasca from '../assets/themes/fx/berserk-casca.jpg'
import bzGuts from '../assets/themes/fx/berserk-guts.jpg'
import bzSkull from '../assets/themes/fx/berserk-skull.jpg'
import bzBrand from '../assets/themes/fx/berserk-brand.jpg'
import bzBrandPanel from '../assets/themes/fx/berserk-brand-panel.jpg'
import bzBehelitAwake from '../assets/themes/fx/berserk-behelit-awake.jpg'
import bzBehelitDormant from '../assets/themes/fx/berserk-behelit-dormant.jpg'
import bzElfhelm from '../assets/themes/fx/berserk-elfhelm.jpg'
import bzEclipse from '../assets/themes/fx/berserk-eclipse.jpg'
import bzSpread from '../assets/themes/fx/berserk-spread.jpg'

import opCrew from '../assets/themes/fx/onepiece-crew.jpg'
import opJolly from '../assets/themes/fx/onepiece-jolly.png'
import opLuffy from '../assets/themes/fx/onepiece-luffy.jpg'
import opNami from '../assets/themes/fx/onepiece-nami.jpg'
import opChopper from '../assets/themes/fx/onepiece-chopper.jpg'
import opUsopp from '../assets/themes/fx/onepiece-usopp.jpg'
import opSmoker from '../assets/themes/fx/onepiece-smoker.jpg'
import opDenden from '../assets/themes/fx/onepiece-denden.png'
import opLogpose from '../assets/themes/fx/onepiece-logpose.jpg'
import opSunset from '../assets/themes/fx/onepiece-sunset.jpg'
import opTsuzuku from '../assets/themes/fx/onepiece-tsuzuku.jpg'
import opEyecatch from '../assets/themes/fx/onepiece-eyecatch.jpg'
import opMeat from '../assets/themes/fx/onepiece-meat.jpg'
import opIslandWhiskyPeak from '../assets/themes/fx/onepiece-island-whisky-peak.jpg'
import opIslandDrum from '../assets/themes/fx/onepiece-island-drum.jpg'
import opIslandAlabasta from '../assets/themes/fx/onepiece-island-alabasta.jpg'
import opIslandSkypiea from '../assets/themes/fx/onepiece-island-skypiea.jpg'
import opIslandThrillerBark from '../assets/themes/fx/onepiece-island-thriller-bark.jpg'
import opIslandMarineford from '../assets/themes/fx/onepiece-island-marineford.jpg'
import jjScHero from '../assets/themes/fx/jojo-sc-hero.jpg'
import jjDiuHero from '../assets/themes/fx/jojo-diu-hero.jpg'
import jjGwHero from '../assets/themes/fx/jojo-gw-hero.jpg'
import jjScMark from '../assets/themes/fx/jojo-sc-mark.png'
import jjDiuMark from '../assets/themes/fx/jojo-diu-mark.png'
import jjGwMark from '../assets/themes/fx/jojo-gw-mark.png'
import jjJotaro from '../assets/themes/fx/jojo-jotaro.jpg'
import jjJoseph from '../assets/themes/fx/jojo-joseph.jpg'
import jjPolnareff from '../assets/themes/fx/jojo-polnareff.jpg'
import jjDio from '../assets/themes/fx/jojo-dio.jpg'
import jjJosuke from '../assets/themes/fx/jojo-josuke.jpg'
import jjKoichi from '../assets/themes/fx/jojo-koichi.jpg'
import jjRohan from '../assets/themes/fx/jojo-rohan.jpg'
import jjKira from '../assets/themes/fx/jojo-kira.jpg'
import jjGiorno from '../assets/themes/fx/jojo-giorno.jpg'
import jjMista from '../assets/themes/fx/jojo-mista.jpg'
import jjBucciarati from '../assets/themes/fx/jojo-bucciarati.jpg'
import jjKingcrimson from '../assets/themes/fx/jojo-kingcrimson.jpg'
import jjTbcArrow from '../assets/themes/fx/jojo-tbc-arrow.png'
import jjScCard from '../assets/themes/fx/jojo-sc-card.jpg'
import jjDiuCard from '../assets/themes/fx/jojo-diu-card.jpg'
import jjGwCard from '../assets/themes/fx/jojo-gw-card.jpg'
import jjScPlate from '../assets/themes/fx/jojo-sc-plate.jpg'
import jjDiuPlate from '../assets/themes/fx/jojo-diu-plate.jpg'
import jjGwPlate from '../assets/themes/fx/jojo-gw-plate.jpg'
import jjScVillain from '../assets/themes/fx/jojo-sc-villain.jpg'
import jjDiuVillain from '../assets/themes/fx/jojo-diu-villain.jpg'
import jjGwVillain from '../assets/themes/fx/jojo-gw-villain.jpg'
import jjScTitle from '../assets/themes/fx/jojo-sc-title.jpg'
import jjDiuTitle from '../assets/themes/fx/jojo-diu-title.jpg'

export const FX_ART = {
  lainDancing, lainCoplandEye, lainNavi, lainPortrait, lainSignalLost, lainLogo, lainSite,
  mgsNaomi, mgsSnake, mgsMeiLing, mgsFreq, mgsGameOver, mgsBox, mgsRadar, mgsSnakeWalk,
  mgsItems: { ration: mgsRation, scope: mgsScope, thermal: mgsThermal, card: mgsCard, bandage: mgsBandage, suppressor: mgsSuppressor },
  mikuHachuneBusy, mikuHachuneWork, mikuCool, mikuNote, mikuHachune, mikuHachunePanic, mikuSongSelect,
  mikuSingers: { miku: mikuSingerMiku, rin: mikuSingerRin, kaito: mikuSingerKaito, meiko: mikuSingerMeiko },
  sfLogo, sfStandup, sfJerry, sfGeorge, sfElaine, sfKramer, sfNewman, sfSoupNazi, sfPuddy, sfFestivus, sfMenu, sfElaineDance, sfElaineStill, sfGang, sfKramerEntrance,
  bzCloak, bzEmboss, bzMark, bzCasca, bzGuts, bzSkull, bzBrand, bzBrandPanel, bzBehelitAwake, bzBehelitDormant, bzElfhelm, bzEclipse, bzSpread,
  opCrew, opJolly, opLuffy, opNami, opChopper, opUsopp, opSmoker, opDenden, opLogpose, opSunset, opTsuzuku, opEyecatch, opMeat, opIslandWhiskyPeak, opIslandDrum, opIslandAlabasta, opIslandSkypiea, opIslandThrillerBark, opIslandMarineford,
  jjScHero, jjDiuHero, jjGwHero, jjScMark, jjDiuMark, jjGwMark, jjJotaro, jjJoseph, jjPolnareff, jjDio, jjJosuke, jjKoichi, jjRohan, jjKira, jjGiorno, jjMista, jjBucciarati, jjKingcrimson, jjTbcArrow, jjScCard, jjDiuCard, jjGwCard, jjScPlate, jjDiuPlate, jjGwPlate, jjScVillain, jjDiuVillain, jjGwVillain, jjScTitle, jjDiuTitle,
  peaksRedRoom, peaksCurtain, peaksWhiteHorse, peaksWren, peaksFalls, peaksMist, peaksLogo, peaksDoubleR, peaksDiane
}
